Kumburin ciki: Wasu hanyoyi da za ka rage radadi ya hada shan kwayar Anise
Alkarsa ga cutar damuwa ba arashi ba ne.
Mutanen da ke dauke da cutarIBS, wata cuta wacce alamunta shine ciwon murdewar ciki, kumburin ciki, tusa, wuyar fitar bahaya da kuma gudawa a kai-a kai, na fama da faduwar gaba da damuwa, wanda hakan zai iya tazarra alamomin cutar, a cewar Kungiyar masu fama da cutar damuwa da kuma faduwar gaba ta Amurka (ADAA).
"Saboda wani bangare na babban hanji yana karbar umarni daga jijiyoyi masu isar da sakonnni wadanda da zarar sun samu sako na damuwa sai su kai dauki" A cewar wani bayani na kugiyar ADAA.
Idan kumburin cikin naka ya cigaba, hakan na iya zama wata alama ce ta rashin karbar abincin da ya shiga cikinka.
An yanki a jaruma Spencer Grammer a kofar wani gidan cin abinci
NEW YORK - Jaruma Spencer Grammer ta ce lokacin da ta ke kokarin kwantar da hankalin wani mutum da ke cikin tashin hankali ne, sai ya kawai ya yanke ta a hannu sannan kuma ya dabawa kawarta wuka a baya a ranar Juma'a a kofar wani gidan cin abinci a birnin New York.
Grammer 'yar shekara 36 da haihuwa ta fadawa jariadar US WEEKLY cewa ita da kawarta "sun yi duk wani abin da wani ya kamata ya yi idan ya samu kansa a cikin irin wannan hali" haka kuma suna "kokarin hana cacarbakin daga karuwa" sai aka far musu.
Grammer ita da kawarta 'yar shekara 32 na cin abinci ne a wani teburi a waje na wani gidan cin abinci mai suna Black Ant a Manhattan a wata unguwa da ke gabashi da misalin karfe 11:30 na dare.
A ranar Juma'a ne a daidai lokacin da gidan abincin ke shirin rufewa sai mutum ya taho kamar mai sanda ya bukaci da a bashi abinci.
Grammer da kawarta ba sun raunin ne a"kokarin da suka yi raba gardamar da ta so tsakanin mutumin da ba a gane ko wanene ba da kuma sauran masu abincin a wurin " in ji 'yan sanda.
Mutumin ya gudu bayan ya ji wa Grammer rauni a hannunta na dama da kuma kawarta a bayanta da wani abu mai kaifi da ba san komene ba, in ji 'yansanda.
Babu wanda aka kama.
Grammer wacce ta yi muryar Summer a shirin "Rick and Morty" ta kuma fito a shirin mai dogon zango "Greek" na kallon iyali a matsayin 'ya ga "Fraser" Jaruma Kesley Grammer da kuma Doreen Alderman.
Grammer ta ce ita da kawarta ana sa rai za su warke cikin sauri.
Duk su biyu babu wacce ta samu wani rauni na ciki fata.
A cikin bayaninta ga US Weekly, Grammer ta godewa wadanda suka kai musu taimakon gaggawa fara da kuma ma’aikatan Asibitin Bellevue wadanda suka kula da su sannan ta lura da cewa sun yi “yakin da ba zai misaltu ba” da cutar ta Koronavirus.
"Grammer ta ce "Yana matukar girgiza mu da muka samu damar yi musu godiya kai tsaye.
'Yan majalisa daga jam'iyyar masu ra'ayin rikau na zargin shugabannin kungiyoyin kwadago da cewa suna so ne ma'aikata da su 'zauna a gida hara abada'
'Yan jam'iyyar masu ra'ayin rikau a majalisar dokokin Brutaniya na zargin shugabannin kungiyoyin kwadago da son ma'aikata da su 'zauna a gida na hara abada' bayan sun bijirewa kiran Boris Johnson na cewa su koma bakin aikinsu
Shugabannin kwadagon a daren jiya an zargesu da cewa suna so ma'aikata so "zauna a gida na har abada" bayan da ma'aikatan suka yi kunnen uwar shegu da kiran da Boris Johnson yayi musu na ma'aikatan su koma bakin aikinsu.
'Yan Majalisara daga jam'iyyara 'yan mazan jiya sun mayar da maratani ne cikin fushi bayan da shugabannin kungiyar ma'aikatan kula da harkokin kasuwanci na jama'a suka umarci 'ya'yan kungiyar da su kalubalanci shugabanninsu a wurin aiki da suka umarce su da su dawo bakin aiki.
Tsohon Minista Andrew Percy na cewa "ba za mu amince da wannan ba" wannan bangare ba jama'a mai matukar muhimmanci da ke gudanar ayyuka kamar bayar da Fasfo na tafiye-tafiye a daina bayan ma'aikata kamfanoni masu zaman kansu na faman sahan wahalar ciyar da kasar gaba a lokacin da ake tsaka da fama da cutar Koronabirus.
"Ba zamu amince da rashin komawarsu bakin aiki ba a yayin da wuraren da ake rarraba abinci da kuma masana'antu na cigaba da aiki domin ciyar da ma'aikatan gwamnati a wannan a hali da ake ciki" yana mai cewa.
"Yawancin wadannan ma'aikata za kuka suce daga bayab suna bukatar su tafi hutu kuma ba za a basu ba saboda kin komawa bakin aikin da suka yi wanda kuma za su iya yin haka ba tare da jefa kansu cikin hadari ba.
" Shgabannin kwadago ba za su fito da wannan tsirfa ta a cigaba da zama a gida ba na har abada - ba dai a yanzu ba da musamman mu ka san cewa ma'aikata za su iaya komawa bakin aikinsu lafiya ba tare da fuskantara wani hadari ba."
Bayana kiran da Shugaba na Britaniya ya yi, Alex Chisholm ssabon shugaban ma'aikata na kasar a makon jiya ya fadawa duk ma'akatun gwamanati cewa "yanzu lokacin ne da za a sauya daga yadda aka saba na ma'aikata su rika aiki daga gida, su yi gaggawan komawa ofisoshinsu daga 1 watan Agusta."
Sai da kungiyar kwadagon ya ma'aikaytan da ke kula da kasuwanci da al'amura na jama'a ta fadawa 'ya'yanta da suka kai 200,000 da cewa su ba sua amince da wannan umarni ba, kungiyar na mai ikirarin cewa wanann batu ne na siyasa.
Wani mai magana da yawun PC, wata kungiyar kwadago ta ma'aikatan gwamanati wacce ita ce mafi girma a Britaniya na cewa, "wannan kira na a koma aiki a ofisoshi "bai yi la'akari da lafiyar 'ya 'yanmu ba" da kawara da su daga shiaga hadari da kuma taimakawa tattalin arzikin kasa.
Wannan kira an dora shi ne kacokan a kan matsin lamba na siyasa da 'a majalisa 'yan jam'iyyar masu ra'ayin rikau wadanda ke da bukatar ganin cewa sun yi amfani da ma'aikatan gwamnati a matsayin misali domin su sa kowa ya koma da ayyukansa ofis.
"shawararmu ga 'yan kungiya a bayyane ya ke: duk lokacin da ka ke aikinka daga gida kuma wani ya tunkare ka daga wurin aikinka da maganar cewa ka koma gida, kar ma ka saurare shi"
Wannan takaddama na zuwa ne yayin da ake tsaka damuwa mai karuwa kan jinkirin da ake samu na fasfon tafiye-tafiye sakamakon halin aiki daga gida da ake yi. Sama da mutane 400,000 ne da suka cika takardun neman fasfon ke jira a ba su.
Ma'aikatar da harkokin cikin gida ta kasar yanzu ta ce za ta san yadda "gaggauta" duba takardun neman fasfon daga 'yan asalinn kasar wadanda suke shirin yin tafiya a cikin kwanaki 14 kuma suna kan jira a duba bukatun nasu a ofishin bayar da fasfo din har tsawon sama da makwannni huɗu.
Kungiyar kwadagon ta PC ta yarda da cewa wasu mutanen sun mika bukatunsu na fasfo din har na tsawon kwanaki 143, amma kuma ta dage cewa "kananan ofisoshi da wasu lokutun ke fama da cikowa" na hana a nisantar juna kamar yadda ya kamata ga ma'aikatan ofishin su 4,000.
Wani tsohon minista a gwamnatin kasar David Davis ya yi kira ga shugabannin kungiyar kwadago da su yi rika "sara suna duba bakin gatari" tare da hada hannu da gwamnati don yin aiki tare don samo yadda za a gano hanyar da mutane za su koma bakin aikinsu.
Sannan ya kuma kara da cewa da ina cikin gwamnati, tambayar shugabannin 'yan kwadagon zai yi:"mecece shawararku? Na ku zauna [a gida] duk tsawon lokacin hunturu?"
Sai dai kiran da Mista Johnson ya yi na ma'aikata su koma ofisoshinsu bai sa wasu manya-manyan kamfanoni na kasar ta Brtianiya sun yi aiki da shi ba.
Wani nazari da aka yi na kamfanonin da suke da yawan ma'aikata 40,000 a tskaninsu an gano cewa ma'aikata 400,000 ne kawai suka koma bakin aikinsu.
Yanayin Gareth Bale a Real Madrid 'bai gamsar da kowa ba', in ji Toni Kroos
Dan wasan tsakiya na Real Madrid Toni Kroos ya ce halin da Gareth Bale ke ciki a kungiyar ta Sipaniya 'bai gamsar da kowa ba'.
Bale bai taka rawar a zo a gani ba a duk wasanni bakwai da suka gabata, kuma ya kasance mutum ne na daban a bikin da Los Blancos ke yi na bikin LaLiga gabanin tsawaita lokacin bazara yayin da dan wasan ke son ci gaba da zama tare da ganin kwantiraginsa kuma kungiyar na fatan zai tafi.
"Babu wata hanyar da za a kaucewa lamarin kasancewar bai gamsar da kowa ba," in ji Kroos a hirarsa da Lauschangriff Endlich mit Sport! wani shiri na podcast.
"Tabbas ba su sanya masa hannu ba don ya taka leda a taikaice ba kamar yadda yake a yanzu.
"Ina ganin a ka'ida ya so barin kulob din a bazarar da ta gabata kuma kungiyar ta ce 'eh' bisa manufa sannan kuma 'a'a' bayan haka.
"Ban sani ba ko har yanzu yana ɗan fushi saboda wannan.  Abin da 'yar matsala."
Da aka tambaye shi ko lamarin ya yi wani mummunan tasiri ga yanayin kungiyar ta Real, Kroos ya ce: "Tabbas bai kai yadda za a iya tsammani ba.
"Komai yana tafiya daidai a kungiyar.  Na san shi tsawon shekaru shida kuma mun samu nasara a wasu muhimman abubuwa tare."
Kauyen Aswan sun tattara, da gadin da kuma dawo da lodin kayan da ya tuntsire na alawar chakuleti da ya fadi kan hanyarsa zuwa kasar Sudan
Wata babbar motar daukar kaya mai dauke da lodin halawar Chakulet da ke kan hanyarta zuwa kasar Sudan ta tuntsure kan hanyar Aswan-Abu ranar Lahadi hanya mai sauki ta kasa da kasa a ranar Lahad, a daidai kofar shiga kauyen wadi Karkar, A inda direban motar ya suma ne a sakamakon tsananin zafi.
Kauyawan sun garzaya wurin cikin hanzari tare da kokarin ceton direban da kuma alkinta kayan da motar ke dauke da shi wadanada suka tarwatse.
Daya daga cikinsu mai suna Alaa Bahr, ya na mai bayanin cewa direban motar bako ne wanda hanya ta biyo da shi ta kauyen , a don haka ba za mu kyale shi ba, ba tare da taimaka masa ba.
"Dole ne mu taimaki kowa, ba tare da la'akari da ko su wanene ba, in dai har suna cikin halin bukatar taimako"
Ya kuma ci gaba da cewa, mazauna kauyen sun kirawo motar daukar marasa lafiya don daukar direban, sannan sai suka yi kokarin alkinta kayan babbar motar da yawansu na kai na kimanin LE miliyan uku.
A cewar Bahr, mazuana kauyen sun zauna gadin kayan tun daga safiya har zuwa dare suna ta iya bakin kokarinsu na tattaro kayan da suka tarwatse.
Ya na mai cewa, "Abu ma fi muhimmanci a garemu shine ceto ran direban da kare kayan da motar ke dauke da shi, da kuma bude wannan babbar hanya ta kasa da kasa.
Mutanen kauyen cikin hanzari su ka kawo wa direban da ya ji rauni ruwa da tare da samar masa makwanci, Bahr ya kuma kara da cewa, su dai bukatarsu ita ce yadda direban ya shiga kauyen lafiya, ya fita lafiya da salama.
Mutum 50 ne za'a basu Izini shiga Masallatan a Karnataka a ranar Idi, Babu taron jama'a a ranar Sallar
Sallar idin Layya wacce ake kira Bakrid za a yi ta ne a ranakun 31 ga watan Yuli da kuma ranar 1 ga watan Agusta.
Gwamnatin Karnataka ta kyalle gudanar da Sallar idin Layya kadai a masalltan da yawan jama'ar bai wuce mutane 50 ba a lokaci guda ta kuma ce yin sallar jam'i a Eidgha ya haramta sakamakon barkewar annobar cutar Koronabirus.
Mutanen da ke zuwa masallatai don yin sallah a jam'i sai sun sa takunkumi sun kuma nisanci juna a sahun, a cewar AB Ibrahim Sakataren Sashen Kula da Walwala da waƙafi a wata doka.
Dokar ta kuma ce Kwamitin halal ya zartar da cewa Sallar Idin Layya wacce ake kira da Bakrid za yi ta ne a ranar 31 ga watan Yuli a gudundumin Udupi, da Dakshina, da Kannada da kuma Kodagu yayin da za a yi idin ne a ranar 1 ga watan Agusta a sauran jihohin.
La'akari da cewa sallar jam'i na da daya daga cikin muhimman ibadun da Musulmi ke yi a bikin Bakrid, dokar ta ce la'akari da bullar annobar cutar COVID 19.
Sai dai za a kyale yin Sallah a masallacin da jama'ar cikinsa ba su wuce sama da mutum 50 ba.
Idan yawansu ya fi haka sai dai su Sallar rukuni-rukuni. in ji hukumar a cikin dokar da ta bayar.
Ba kuma za a yi sallat a wasu wurare ba kamar dakunan taro da ire-irensu da kuma "Shadi-mahad" a cewar dokar.
Karnataka ta kyale masu zuwa bauta a sauran wasu wuraren ibada da za a iya budewa ga mabiya wadannan addinai daga ranar 8 ga watan Yuni tar da daukan dukkanin matakai na kariya akan COVID-19.
Malaysia na neman 'yan Rohingya 24 da ake zaton sun nutse daga wajenn tsibirin
Kuala Lumpur, Malaysia (AP) - Mahukuntan Malaysia sun fada jiya Lahadi cewa suna neman wasu ‘yan gudun hijira‘ yan kabilar Rohingya su kimanin dozin biyu wadanda ake fargabar sun nutse bayan sun tsalle daga kwale-kwalensu daga tsibirin shakatawa na arewacin Langkawi.
Zawawi Abdullah, wani babban jami’i a hukumar tabbatar da bin dokar ruwa ta Malaysia, ya ce bayanan ‘yan sanda na farko sun nuna cewa mutum daya ne kawai daga cikin‘ yan Rohingya 25 da suka yi tsalle daga kwale-kwalen ya yi nasarar yin iyo har ya kai gaɓar teku.
Wanda ya tsira shi kadai ya nemi taimako daga 'yan sanda da yammacin ranar Asabar kuma an tsare shi don ci gaba da bincike, in ji Zawawi.
Dubun dubatar musulmin Rohingya sun tsere daga Myanmar saboda wata mamaya da sojojin kasar suka kai musu, kuma da yawa suna zaune ne a sansanonin ‘yan gudun hijira da ke cunkoson mutane a Bangladesh.
Kasar Malesiya da Musulmai suka fi yawa ta kasance wani wuri da jiragen ruwan da masu fataucin mutane ke shiryawa ke yi wa ‘yan gudun hijirar romn baka na samun kyakkyawar rayuwa a kasashen waje.
Zawawi ya ce an tura jiragen ruwa biyu da kuma jirgin sama a binciken da ake na wadanda suka nutsen.
Ya ce hukumar za ta kuma fadakar da masunta na cikin gida da hukumomin makwabciyar kasar Thailand don taimakawa wajen binciken.
Bai bayar da wani karin bayani ba dangane da jirgin ruwan 'yan gudun hijirar ba.
A watan da ya gabata, hukumomin Malaysia sun tsare ‘yan gudun hijirar Rohingya 269 kuma sun gano wata gawa a cikin jirgin da ake zargi na fasakwaurin ne nesa daga Langkawi wanda suka ce da gangan aka lalata shi don a kara juya shi zuwa teku.
Daga baya Hukumar tabbatar da bin dokar ruwa ta Malaysia ta ce mutanen 269 an sauke su ne daga wani babban jirgi wanda aka yi imanin cewa mutane da dama sun mutu kuma an jefa gawarwakinsu cikin teku.
Firayim Minista Muhyiddin Yassin ya ce Malaysia ba za ta iya karbar wasu karin 'yan gudun hijirar Rohingya ba yayin da take fama da koma bayan tattalin arziki saboda bullar annobar cutar Koronabirus.
Amma yace wadanda suke kasar ba za mayar da su cikin Teku ba.
Malaysia ta kasance gida ga sama da baƙin haure miliyan 2 da kuma wasu 'yan gudun hijira 180,000 da masu neman mafaka - gami da' yan Rohingya 101,000 - waɗanda suka yi rajista da hukumar kula da 'yan gudun hijira ta Majalisar Dinkin Duniya.
Mayar da hankali kan tarihi na iya taka muhimmiyar rawa wajen sasantawa
Rarrabawa kawuna sun zurfi a lokacin da fahimta da warkarwa ya yakamata su zama manufofinmu.
Tsarin tafi da makarantunmu na daga cikin wani bangare da za mu zarga na wannan gazawar ilmi da fahimta.
Ba a koyar da tarihin kasar Australiya sosai.
A zahiri, ba tare da aiwatar da tsattsauran ra'ayi ba, makarantar ita kadai ta ke mai da hankali kan tarihinmu - "tarihin Australiya," a shekara ta 12 - zai mutu a cikin shekaru biyar masu zuwa, watakila ma kafin wannan lokacin.
A shekarar da ta wuce, a cikin ɗaliban Victoria 49,324 da suka kammala VCE, 628 ne kadai, ko kashi 1, suka yi tarihin Australiya.
A cikin shekaru shida da suka gabata, wannan adadi ya kusan komawa rabi, tare da kusan ɗalibai ɗari ne suke yin rajista a kowace shekara.
Babban dalilin da yasa dalibai kaɗan ne suka zaɓi yin nazarin tarihin Australiya a shekara ta 12 shine ba a yi komai ba a shekarun da suka gabata donza zaburar da sha'awar yin hakan.
Tarihi ba ma wani fage ban ne fannin karatu mai zaman kansa, amma a hade yake a cikin faffadan al'maura na"dan Adam."
Don haka a tsawon shekaru 7 da 8, ɗalibai sun kammala taƙaitaccen sashe ɗaya tak a kan tsohuwar al'adun mutanen Aborigine da mazauna tsibirin Torres."
Sannnan a wasu shekaru 9 da 10, da akwai kuma wani bangare mai mayar da hankali kan kasar Australiya a lokacin yake-yaken duniya.
Ga yawancin daliban Victoria, wannan shine jimillar tarihin Australiya da ake koyarwa a daukacin a shekarun su na karatun Sakandare.
A shekaru 9 da 10, da akwai wani zabi na wani sashe da ya tattaro tun daga shekarun 1750 zuwa 1918.
Wasu abubuwa guda uku na da bukatar a yi aiki domin ceto tarihin a Australiya a makarantun Victorian.
Da farko a mayar da tarihi ya zama bangaren ilimi mai zaman kansa kamar Ingilishi da Liassafi da kuma kimiyya.
Saboda ana koyar da tarihi kawai a cikin abubuwa na dan adam, an bashi takaittcen gurbi a cikin tsarin mahajjar karatu.
Haka nan a ko dayaushe ana koyar da shi ta hanyar masu nazarin dan adam gama gari waɗanda su ba suyi karatun tarihi ba da kansu.
Kwarewa nazarin tarihi kamar nazarin shaidu, suna da rikitarwa.
Dole ne mu sake daukar kwararrun malaman tarihi don tabbatar da cewa ana koyar da su ta hanya mai sauki da kuma ban sha'awa.
Na uku, nazarin tarihin Australiya daga shekarar 1788 zuwa 1914 dole ne ya zama tilas.
Dalibai suna son abin da suka sabawa.
Da yawa daga tsoffin ɗalibaina sun yanke hukunci cewa ba za su yi tarihin Australiya a shekara ta 12 saboda da sai sun koyi abubuwan da ke ciki tun daga farko.
Sanin tarihinmu kadai ba zai dinke bambancin launin fatarmu ba da ta suka yi zurfi.
Amma ba tare da shi ba, kamar yadda tsarin karatun Victoria ya fito da shi karara, aikin ba zai yiwu.
Dr. Matthew Bach Dan Majalisar Dokokin Victoria ne kuma tsohon sassaucin ra'ayi, kuma mataimakin shugaban makarantar Ivanhoe Girls" Grammar ne.
Jarumar Shirin White Star Laura Haddock 'yar shekara 34 ta tafi neman gida tare da tsohon masoyinta Tom Rhys Harries dan shekara 28
Sun soma soyayyane ne a wajen daukar shirin White Lines, wani wasan kwaikwayo kan rayuwar sheke aya a tsibirin Ibiza - amma daga ranar da Laura Haddock da saurayinta Tom Rhys Harries suka je neman gidan zama a makon jiya, sai suka bayyana a matsayin wandanda ke cikin kwanciyar hankali daban da 'yar rayuwar sharholiyarsa na cikin shirin.
Masoyan da ke fitowa a matsayin wa da kanwa a cikin shirin mai farin jini daukar nauyin kamfanin NETFLIX, an gan su ne a lokacin da suka je kallon wani gidan gona mai dan karen kyau siffar Oxfordshire wanda ake neman fam miliyan 1.2.
Sun iso wurin ne a wata mota kirar Range Rover wacce Laura ke tukawa 'yar shekara 34, tana sanye da gajeren wando na denim, da kuma farar riga a inda dillalin gidan wanda ya shigar da su gidan mai dakunan kawana 5 na alfarma domin su ganewa idonsu.
A cikin shirin na 'white Lines wanda aka dauka da kaka, Zoe Walker wacce ta fito a Laura, ta gano rayuwar sharholiya na Ibiza a lokacin da ta ke binciken kisan gillan da aka yiwa a dan uwanta Axel mai wasan DJ wanda Tom dan shekara 28 ya fito.
Labarin soyayyarsu bai bayyana ba sai farkon watan nan, kasa da shekara guda bayan mutuwar aurenta da Sam Claflin na tsawon shekara shida, wada ya fito a fim din nan mai suna 'The Hunger Games.
Sun haifi da namiji mai shekara hudu mai suna Pip da kuma 'ya mace mai suna Margot 'yar shekara biyu.
A lokacin da suka sanar da rabuwarsu a watan Ogustan da ya wuce, Claflin dan shekara 34 ya rubuta a shafinsa na dandalin sada zumunta na Instagram: "Laura da ni mun yanke shawarar da mu kawo karshen aurenmun.  Babu komai a tsakaninmu yanzu sai abin da ba a rasa ba na kauna da matukar mutunta juna, za kuma ci gaba da kokarin kula da yaranmu tare."
Laura da Sam sun fara haduwa ne a shekarar 2011 a wani gwajin 'yan wasa, sai kuma shi Sam da ya ke fitowa a cikin shirn 'Peaky Blinders' ya kwatanta aurensu a shekarar 2013 a matsayin " wata babbar nasara a rayuwarsa baki dayanta."
Kafi shirin 'White Lines' Laura ta fito a farko a wasu shirye-shiryen fin da kuma shirin wasan kwaikwayo na BBC "The Capture" a inda ta fito a matsayin Lauya Hanna Roberts.
Tom kuma ya fito a cigaban shirin 'Inbetweeners' da kuma wani wasan kwaikwayo na 'Britannia' na gidan talbijin din SKY.
Ma'aurata 'yan Jinin sarauta a da, 'su na jin an yi watsi da su' a lokacin gabatar da sakon Krisimeti na sarauniya, a cewar wani littafi
MEGHAN Markle da Yarima Harry suna jin cewa kakakarsa sarauniyar Ingila ta yi "watsi da su" a yayin gabatar da jawabinta na sakon Krisimeti data saba yi duk shekara.
A wani sabon littafin tarihin rayuwar ma'auratan biyu mai suna 'Finding Freedom' sun ikirari cewa an fitar da su daga jerin hotunan da aka baje a taron na sauraron jawabin na al'ada da aka sayi duk shekara.
Hotunan da ke kan teburin da sarauniyar ta ke zaune sun hada da na Yarima William da Kate Middleton da kuma 'ya'yansu uku, yarima da matarsa Camilla da kuma Yarima Philip.
Amma babu su, babu alamar su bayin sun haifi 'yar su Archie a watan Mayu na shekarar da ta wuce. Ko da yake jaririyar ba 'a ko ambace ta ba a matsayin 'tattaba kunnen sarauniya ta takwas'.
Sabon littafin - wanda ake sa ran fitowarsa cikin watan Agusta - ya kuma bayyana cewa Meghan daKate Middleton "ba su taba zama abokan juna ba"a yayin da "suke fama su wuce ladabin nesa" sun dai taba haduwa a wasu lokuta daban-daban.
An yi ikirarin cewa a jiya, rabuwar yarima Harry da dan uwansa William ya samo asali ne 'yan shekaru da suka wuce kafin soma soyayyarsu da Meghan - kuma hakan ya kai makura ne a lokacin da William ya auri Kate Middleton.
Mai rike da sarautar Duke na Sussex ya na jin kansa tamkar "wukar baya"a duk wani taro da dan uwansa William da Kate Middleton za su je - da hakan yayi ikirari, "tun kafin zuwan Meghan ta zo, ya ke so ya sauya abubuwa."
Maurice Pretty, injniya kuma mai kera inji, dan cikin zauren shahararru, ya rasu yana da shekaru 81 a duniya.
Birni Kansas, Kan  (AP) Maurice Pettu daya daga cikin zuriyar gidan shaharar tseren motoci da ya hada da mahafii Lee da yaya Richard da kuma injiniya na farko da magini da shaharar su ta suka shiga zaurren shararru na NASCA, ya mutu a ranar Asabar.
Shekarunsa 81 da haihuwa.
Iyalan Petty ba su bayyana sanadiyyar mutuwar ta sa ba.
Babu wata sanarwa ta shirye-shiryen janaizarsa
Yayin da sauran 'yan uwansa suka yi fice a irin kwazonsu da kwarewarsu na iya sarrafa stiyarin mota, Maurice Petty kuwa ya samu lakabin "shugaba" ne saboda yadda ya san karfe da kuma sarrafa shi.
Ya taimaki gidansu lashe gasar tsere 198 da kuma gasar fidda zakaru na jerin gasar tsere na NASCA firimi ya kuma kira injinan da gwanayen tuki Halla of famer Buddy Baker, da Jim Paschal, da Hamilton suka hau, suka kai ga nasara da kuma shahara.
"Sarki na daya daga masu basira kera inji da gyaransa a tarihin NASCAR",  a cewar shugaba da kuma babban jami'i Jima France.
"Ya samar da karfin da ya taimakawa kamfanin Petty Enterprises tabbatar da dorewar ci gabansa a wasannin tsere.
Yayin da ya yi suna a aikinsa a karkashin mota, Maurice ya taka muhimmiyar rawa a bayan fage da yawa, yana yin abim da ya sani na taimaka wajen kai motocinsa ga nasara"
An haifi Maurice Petty a rarnar 27 ga watan Maris a shekarar 1939, a wani wuri da ake kira Level Crossing, North Carolina.
A lokacin yana karami, ya ka bi mahaifinsa zuwa wurin tsere, sannu a hankali har ya zama kusa a cikim 'yan Lee Petty da suka lashe gasar tsere 54 da kuma gasar zakaru guda uku.
Ya shiga tsere 26 a gasar cin kofin NASCAR daga shrekarun 1960 zuwa 64,  a inda ya kai ga matak na 5 har sau biyar a inda ya kai 16 a sma da kuma  tser100
Amma cikin sauri ya yanke shawarar ya mayar da hankali kan abinda ke karkashin mota a maimakon abin da ke bayn sitiyari, kuma hakan sai ya kasance shawara mai kyau da zai taimakaw yayansa, wanda zai dogara da karfin injinansa har ya kai ga nasara
Richard, wanda ya ke amsa lakabin "Sarki" ya lashe gasarsa ta farko ta gasar zakarun tare da shuganba yayin da ya yi tuki a gasar Playmouth har zuwa ga gasar shekarar 1964 ta neman suna
Sun kuma sake lashe gasar a shekarar 1967, kai da kai, a shekarar 1970 da kuma 71 , ya kuma sake maimaita wannan nasara kafina shekarar 1970 da ta kawo karshen lamarin,
Nasarorin gasa guda 7 sun kasance a hannun Dale Earnhardt da Jimmie Johnson har zuwa karshen tarihi
"Maurice Petty na daya daga cikin wandanda aka soma da su asali a NASCAR wadanda suka taimaka wajen gina daya daga cikin 'yan wasan NASCAR da suka yi mamaye komai a kamfanin Petty Enterprises". Shugaban zauren shahararru kuma darakta mai cikakken Winston Kelly ya na mai cewa a wata sanarwa da ya fitar,
" Duk da cewa ajiyayyaun bayanai sun nuna nasarori 212, Petty yana da nasarori sama da 250 da ya sanu la'akari da  cewa duk injinan da ya kera dga abokan gasarsa.
Za mu cigaba da tuna sarki a matsayin daya daga cikin kwararraun da suka kera mana injina a NASCAR da aka samu nasarori da su.
Lee petty ya rasu a shekara ta 2000 matar Maurice Petty mai suna Patricia wacce suke tare tsawon shekara 52 ta rasu a shekarar 2014
Kuma shi kawu ne ga tsohon direba kuma mai watsa labarai Kyile Petty da da kuma a Trent Owens shugaban ma'aikatan shirin mai dogon zango mai suna Truck
Kelley ya cigaba da cewa, "yayin da muka yi rashin  daya daga cikin 'yan asali na gaskiya kuma gwarzo a NASCA  abubuwan da ya yi zamu allkintasu, mu kiyayesu, mu kuma yayata su.
"muma mika ta'aziyyarmu tare da matukar juyayi ga iyalan Petty"
Wayar hannu ta Google Pixel 4 da ka iya daukar hoton taurarin samaniya ragdadadau
Baya ga karin abin janyo nesa kusa mai ninki 2, abin daukar hoton na biyu ya ba kyamarar Pixel 4 iya ganin hoto cikin tsarin 3D; ta yadda zai dusashe duk wani abu da ke bayan wanda ake dauka hoto a tsarin portrait, wanda hakana ya doke na irin kirar wayar na baya, wanda suka dogara da wata manhaja don samun wannan tagomashi da ake kira "bokeh" a hoto.
Don kara samun amincewar jama da wannan abar daukar hoto, Kamfanin Google ya gayyato Annie Leibovtz wata fitacciyar mai daukar hoto wani zauren taro don ta yiwa jama'a bayanin irirn yadda ta ji dadin aiki da kyamarar wayar hannun ta Pixel4 a watanni 12 da suka wuce.
Tsarin amfani da na'ura mai kwakwalwa na 'machine learning' ya kasance shine alkiblar inganta sabbin wayoyin hannu na Google, kamfanin ya dogara da salon kididdiga da lissafi a daukar hoto na 'computational photography' don inganta kyawun hoto ya fito ragadaddau a matakin HDR+ ta hanyar harhada hotuna guda tara daban-daban a hoto daya.
Wani sabon nau'in inganta hoto ya samar da madannai daban don inganta haske da kuma inuwa wanda hakan zai ba mai daukar hoton damar ganin hoton kafin a nau'in HDR+ fitar da hoto tangararau kum kai tsaye.
Wayar kuma ta dogara kan tsarin na'ura mai kwakwalwa na 'Machine learning' don inganta fitar da fari ya fita tar, baki kuma ya wuluk wanda ingancinsa zai sa kyamarar ta dauki hoton cincirindon taurari cikin duhu dare su kuma fito rangadadau.
Baya ga abin daukar hoto na biyu, wayar Pixel 4 ta zo da sabuwar fasahar soli wani nau'in 'radar chip' wacce mai amfani da wayar zai iya sauya kida, da kashe sanarwa ta sakonni, da kashe kararrawa, da kuma sa wayar a tsit ta motsa hannu kawai.
Duk wata fasahar na'ura mai kwakwalwa da ke gane motsi na cikin wayar, maimakon a intanet, kamar yadda ta inganta aikatau 'Google Assistant' din ta wanda hakan ya nuna yadda hamshakin kamfanin ya mayar da hankali wajen rage dan lokacin karbar umarnin da kuma kare sirrin mai amfani da wayar.
A dagewar da kamfanin Google ya yi na cin gajiyar fasahar 'Machine learning' ya kikiro tare da yada wata sabuwar na'urar daukar murya wacce ta ke iya mayar da sautin murya zuwa rubutu kai tsaye ba tare da ta aika da shi ta intanet ba.
A yanzu dai wannan manhajar a harshen Turanci kadai ya ke, ana sa ran samar da karin wasu harsuna a nan gaba.
Wayar Pixel4 ita ce waya ta farko da ke dauke da jerin wasanin Google Stadia wada ka aka kaddamar 19 ga watan Nuwamba a Amurka ana dakon kaddamar da shi a Australia nan ba da dadewa ba.
Baya ga sabbin wayoyin hannu na Pixel, kamfamin Google ya fito da sabuwar Komfutar tafi-da-gidan 'Pixelbook Go Chromebook' da kuma abin saurare na kunne 'Google Pixel Buds.
Wacce ake sa rai da fitoworta a shekara mai zuwa, amma ban da a kasar Australia, sabon abin kunne na Bluetooth kirar 5.0 na zamani na dauke da adaptive audio' fasahar da abin kunnen ke sarrafa sauti da kansa wajen karawa ko ragewa ba tare da ka taba shi ba la'akari da inda ka ke.
Sabon abin kunne na Bluetooth kirar 5.0 na zamani marsa aiki da igiyar waya, na dauke fasahar zamani da ke karawa da kuma rage sautin abin da ka ke ji da kan sa, dogaro da inda ka ke.
A hannu daya kuma, Kamfanin Google ya sanar da fitar da sabuwar 'Nest Wifi' na'urar mai rarraba hanyoyin sako na intanet kanana wacce ya inganta ta hanyar hadesu domin yin aiki wuri guda don samar da hanyar hawa intanet a cikin gida ba tare da igiya ba.
Ta hanyar amfani da sunan 'Nest' sabuwar na'rar ta ninka tazarar da inda karfin inda sakon zai je fiye da tsohuwar tare da karin abar daukar magana da kuma lasifikar saurare don nau'in ailkatau na Google mai taimakawa wajen yi maka wasu ayyuka a kowacce karamar hanyar sadarwa ta gida.
An kaddamar da na'urar a kasar Australia ranar 5 Nuwanba a kan farashin $399 ko Wi-Fi point da kuma Wi-Fi point akan $549 AUD.
Wannan na'ura da aka sa mata suna 'Google Home Mini ya kuma da samun ingantawa, a bisa sabon farashin $79 sabuwar na'urar 'Nest Mini na inganta karfin sauti tare da inganta sautin Bass tare da kuma abin makalawa a jikin bango.
Haka ma an shirya samarwa da dukkannin sabbin sipikun Google na zamani wani tsarin da za su iya amsawa da kuma yin kira kamar waya tsakanin gida da kuma na'urar a gida ciki har da kiran nu'urar ta 'Mini Nest daga wajen gida ta hanyar amfani da manhajar 'Google home app.
'Yan sanda: an harbi wani mutum a yayin zanga-zanga a Texas
AUSTIN, Texas (AP) - An yiwa wani mutum mummunan harbi a yayin da ake zanga-zanga a Texas a lokacin da ya tinkari wata mota kuma direban ya bude masa wuta, a cewar 'yan sanda.
Harbin ya faru ne da misalin karfe 10 na yamma a wata zanga - zangar da aka yi a Austin, Katrina Ratliff mai magana da yawun 'yansanda ta fadawa 'yan jarida a safiyar ranar Lahadi.
An garzaya da mutumin Asibiuti a inda likitoci suka tabbatar da cewa ya mutu.
Motar ta yi hon sannan ta yi kwana zuwa wani layi, ta kuma yi cikin masu zanga-zangar cikin sauri, Micheal Capochiano wani da aka yi kan idonsa ya fadawa jaridar Austin American Statesman.
Mutumin da Capochiano ya ce na dauke da wata doguwar bindiga, ya tinkari motar ne sai kuma direban ya harbe shi.
Direban kuma ya yi tafiyarsa, a cewar Capochiano.
Rahotanni na farko na nuna cewa " mutumin da aka harba na dauke da bindiga," Ratliff ya fadawa 'yan jarida, ya kuma kara da cewa ana tsare da wanda ake zargi kuma yana na 'yan sanda hadin kai.
Tarin jama'a ce ta taru a ranar Asabar a wata zanga-zanga kan rayuwar ba bakaken fata ma na muhimmanci, a cewar kafofin yada labarai.
An sa zanga-zangar kai tsaye a shafin sada zumunta na Facebook an kuma dauki sautin hon din motar da kuma karar harbin bindiga a kai-akai da ake iya ji.
Donald Trump ya bayyana cewa wani lokacin yana nadamar sunbatun da ya ke yi a shafinsa dandalin sada zumunta na Tuwita
Donald Trump ya bayyana cewa a wasu lokutan ya na nadamar irin sunbatun da ya ke yi da ke janyo cece-kuce a shafinsa na dandalin sada zumunta na Twita.
Shugaban na Amurka ya furta hakan ne a yayin da ya ke jawabi a wani shirin wasannin na Bartool a ranar Juma'a, Shugaban ya ce sakonnin da ya ke aikawa na rashin mafadi - wadanda cike har da na nuna goyon bayan fararen fata 'yan wariyar launin fata - su suka fi jefa shi cikin tsaka mai wuya.
Da wani dan jarida Dave Portnoy ya tambaye shi ko ya yi nadamar irin wadannan zantuka da ya ke sakawa a shafin nasa, sai Trump ya masa da cewa: "a wasu lokutan, a wasu lokutan a kai-akai.
Ba kamar a da ba, yadda za ka rubuta wasika bayan ka yi nazari sai ka cewa kanka wannan wasika ta girma matuka.
Sai bayan ka bar ta a kan teburinka idan ka sake komawa washe gari sai ka ce da kana "kai gaskiya gwanda da Allah Ya sa ban aika da ita ba," haka ne?
Amma yanzu hakan ba zai yiwu da wannan Tuwitar ba, haka ne?
Nan da nan mu ke sakinta, muna jin cewa mun yi abin kirki, sai kuma ka soma jin kiraye-kiraye a na tambata ka - "Anya kai ne ka fadi haka kuwa?"
Sai ni kuma in ce, " toh sai me in nine?" sai kuma wasu abubuwa su yi ta fitowa."
A watan da jiya, sai da Trump ya janyo cece-ku-ce bayan da ya sake aikawa da wani sako a shafinsa na Tuwita na wa ni hoton bidiyo da na magoya bayansa a wani kauye a jihar Florida tare da wasu tsofaffi mata da miji suna jinjina tare da ihun "Allah Ka daukaki farar fata!"
Haka kuma in shekarar 2017, Trump ya sake aikawa ta shafinsa na Twita, wani sako har guda uku wani sako na kin jinin Musulmai wacce Jayda Fransen, shugabar jam'iyar far-right fringe ta Biritaniya.
Shugaban ya fadawa Portnoy cewa wadannan sakonnin da ta sake aika su a shafinsa sun fi saka shi cikin rikici
Shugaba Trump ya ce: "yayin da ka ga wani abin da ya burgeka kuma ba ka bincike shi ba, ba ka kuma san manufar abin ba, ko kuma dawar garin ba, sai ka zuguguta shin, sai cibi ya zama kari, a wadansu lokuta- na gano cewa kusan a ma fi yawa a kowanne lokaci sakonnin da na sake aikawa daga wasu wuraren, su suke sa janyo min rigima."
Shugaban wani lokacin ya kan yada sakon da ya yabi kansa, ya saki baki kan abokan adawa da kuma zagin makarkashiya ga sama da mutane sama da miliyan 80 da ke bin shafinsa.
Trump yana mai cewa Tuwita ta taimaka masa wajen maganin abin da ya kira "labaran karya" rahotannin gidajen talbijin da shafukan Jaridu da ya ke ce suna cike ne da labarun karya.
Sai dai karerayin Shugaban a yawanacin lokuta a na nazarinsu ne, Dandalin na Tuwita kuwa a bisa hakan ya taimaka wajen yiwa shugaban tsirara a iria furucin nasa.
Jose Morinho ya waiwayi gida yana mai ikirarin cewa komai za zamo cikin sauki ga Tottenham, albishir ga 'yan kallo idan sun dawo kall.
Jose Morinho ya taimaki Tottenham Hotspur ya soma wata sabuwa kuma gagarabadon tafiya tun da aka soma gasar firimiya, amma yana mai cewa dawowa gida da mayar da hankali kan gina gida ba zai yiwu ba in babu taimakon magoya baya.
Kulob din Spurs sun ci sau 12 daga wasannin da suka buga a gida a wannan kakar, amma sun sha kashi sau hudu - daya kadai daga cikin kulob shida da ke samansu da a ka ci su a gida.
Mai horas da 'yan wasan dan asalin Portugal ya ce za a iya samun wasu nasarori ko da babu taimakon magoya baya, amma hakan zai fi kyau a yi a gabansu.
"lallai da akwai bukatar mu yi tare da su". I dan babu su za ka iya samar da wata katanga ce mai duhuwa, amma kawai a tsarin cikin wasan ne kawai" ya na mai cewa.
"Amma ina ganin idan da magoya baya, zaka iya yin sa yadda zai yi karfi saboda yadda abin ya ke kara karsashi da taba su zuci a yayin wasan wannan a cikin filin wasa ne kadai tare da magoya baya ake samunsa"
Mourinho yana mai jin cewa cimma wannan irin tsari mai tsawo kuma gida irin wanda ya ke jin dadin sa a kungiyar Chelsea. ko Liverpool sun ginu ne tsawon kakar wasa har uku, kuma hakam ya na zama abu mai wuya yayin da hamayya ke dada zama mai wahala, kuma abokana hamayya ke kara karfi.
Hakan kuma wani matsa yi na mai mhimmanci a wajen tantance ko wani bangare ne zai iya cimma muradinsa a karshen kakar wasan, muasamman ma a wasannin da aka sha da kyar ko wasannin tsere a yanayin gida ke da matukar tasiri
"Ina jin dai wasan gasar Frimiya na daukar wata alkibla da wadannan nasarorin da aka samu wadansu abubuwa ne da suke dada zama a cimma musu saboda irin matasayin kulob-kulob din suke"
"Amma ka zama gwarzo a gida sannnan kuma ka kai karshen kakar wasa da babban maki a aljihunka daga wasannin da ka buga agida yana da matukar muhimmanci"
"ina jin dai sakamakonmu wasannanin da mu ka yi na gida ba tare da magoya baya ba na da matukar muhimmanci, amma muna da bukatar su dawo mana."
ka dubi irin nasarar da muka samu na doke kungiyar Arsenal da a ce filin wasan nan a cike ya ke da magoya bayan Tottenham ne
Toh, wannan shine irin shiga zucin da za ka iya samarwa daki-daki
An rufe wani sashi na wani babban filin shakatawa da ke Jeronimo da wasu karnukan daji su biyu suka kai wa mutane hari - daga kafar yada labarai ta CBS a Birnin Los Angeles
Wasu karanukan daji sun ciji mutane biyu a kusa da koramar Oso wacce ta mike ta bi titin Jeronimo da ke Mission Viejo da safiyar Asabar. Wanda hakan ya sa a ka rufe wurin.
Laura Wittmer ta ce ta kan ga wadannan karnukan daji kusan a kowacce safiya idan ta fito gudun motsa jiki kuma ta kan kauce musu, anma a wannan ranar Asabar, kawai sai daya daga cikinsu ya nunfota gadan-gadan ya kuma cijeta a kafa.
Yayin da a ka cigaba da bincike kan lamarin, an rufe wurin.
A wani sako a shafinta na dandalin sada zumunta na Twitter hukumar birnin Mission Viejo ta ce, "yau wasu mutane 2 sun kawo rahoton bullar wasu karnukan daji da suka ciji mutane.  Hukumar kula da dabbobi na birnin na aiki tare da sashen kula da kifaye da dabbobin daji kan wannan batu, an kuma rufe wani sashi na babban filin shakatawa na Jeronimo.  Ana kiran jama'a da su kiyaye, su kuma yi taka tsan-tsan a duk lokacin da suka fita zuwa wuraren a ke da dabbobin daji."
Wittmer ta yi kokarin korar karen dajin ta hanyar dukansa da robar ruwa.
Ta kuma kira lambar 911 don samu agajin abin hawa, amma sai ga shi ta iya tuka kanta har zuwa wurin da ake bayar da agajin gaggawa.
Karnukan dajin sun gudu tare da buya a cikin 'yan tsaunukan da ke wurin, amma jam'ai na kokarin bin sawun su tare da kama su don su gudanar da bincike ko suna da ciwon hauka.
Duk da haka, za a yiwa Wittmer maganin kamuwa daga ciwon hauka na mako biyu a matsayin rigakafi.
Wittmer ta kuma ce, harin da wadannan dabbobin daji suka kai mata ya tsorata ta amma hakan ba zai sa ta daina fita gudun motsa jikin da ke yi ba a kowacce safiya, sai dai kawai za ta sauya wani wuri ne.
Sai dai ba a san halin da daya mutumin da wadannan karnukan daji suka ciza ya ke ciki ba.
Kungiyar yaki da yunwa ta fatattaki Yoho bayan lamarin da ya faru a Capitol
WASHINGTON (AP) - Wata kungiya Kiristoci marasa nuna bangaranci da ke kokarin kawo karshen yunwa ta ce a ranar Asabar, ta nema ta kuma karbi takardar barin aikin dan majalisa Ted Yoho daga hukumar daraktocinsa bayan wani abin da ta kira "zagin cin mutunci" da ya yiwa 'yar majalisa Alexandria Ocasio -Cortez.
Ocasio - Cortez, daga gundumar New York, ta zargi Yohi mai wakiltar Florida a majalisar, da amfani da kakkausar kalamai da kuma na isakanci na batanci a gareta a yayin da suke cece-ku-ce a ranar Litinin da ta gabata a kan matakalar zuwa zauren majalisar na Capitol.
Yoho ya musanta yin amafani da kalaman da ta fada, duk da cewa wani dan jarida wanda aka yi abin a gabansa ya tabbatar da cewa ya yi amfani da mummunan kalamai kamar yadda ta bayyana.
A sanarwar da ta fitar, Kungiyar burodi ga duniya ta ce hukumar daraktocinta sun gana a ranar Juma'a da Yoho sun kuma bukaci da ya mika takardarsa ta barin kujerar hukumar "domin wannan ya zama mataki da ke dada tabbatar da aniyarmu ta tafiya mata tare da kuma duk wasu al'umma na launin fata, da kasa daban-daban yayin da suke kokarin jagorantarmu zuwa samun yanayi na duniya daya alumma daya."
A shafin kungiyar na yanar gizo, kungiyar ta ciyar da burodi ga duniya ta ce " hadaddiyar muryar kiristoci" mai zawarcin majalisa da kuma gwamnati kan yaki da yunwa a kasa da kuma duniya baki daya.
"kungiyar kiristoci mai goyon bayan jam'iyyun siyasa da ta mayar da hankali wajen yadda za a kawo karshen yunwa da talauci ta hanyar ingantaccen tsare-tsaren da manufofin jama'a, kungiyar da na mutunta akidu da mutumta, gami da tausayi irin wanda Yesu ya yi kira gare mu da mu yi a yayin da muke tattaunawa da masu rike da ragamar mulki daga kowacce jam'iyya", Sanarwa ta ce.
"Mun yi amanna da cewa abin da danmajalisa Ted Yoho ya aikata da kuma kalamansa kamar yadda aka bayar da rahoto a kafofin yada labarai, ba sa nuni da kima da kuma da'ar da muke so 'ya 'yan wannan hukumar Daraktoci su nuna."
Mai magana da yawun Yoho bai ce komai ba da aka bukaci jin ta bakinsa ta email.
A wani jawabi na ban mamaki a ranar Alhamin a majalisa, Ocsio-Cartez da ta bayar da bayanin abin da ya faru a cikin wani lamari na ban mamaki tare da fadada da a bayanan nata na irin cin zarafi da abin da kira fifikon jinsi na dabi'a "da tursasa mata karbar zalunci da bakaken kalaman zalunci ga mata"
'Yan uwanta 'ya majalisa sama da sha biyu ne suka goya mata baya wajen yin Allah wadai da kuma cewa wannan bisa yawancin halayya ce ta kusan kowanne namiji.
Yoho ya bayyana abin da ya faru da cewa wata 'yar tattaunawa ce kan manufofi sannan ya kuma kara da cewa "babu wani wanda aka yiwa barazana, ko ciwa mutunci ko kai wa hari."
Ya kuma yi nadamar nuna "saurin fushinsa."
Ocasio-Cortez 'yar shekara 30 sabuwar shiga majalisa mai ra'ayin 'yan gaba dai-gaba dai wacce ta samu yabo da kuma suka saboda fito-na fiton da ta ke yi.
Yoho dan shakara 65 na daya daga cikin mafi ra'ayin rikau a majalisar, yana dab da yin ritaya a karshen wa'adin zamansa na majalisa karo na hudu.
Karo tsakanin Sachin Pilot da Ashok Gehlot; BIP ya ce jihar ta shiga hargitsin siyasa: Majalis ta ja daga ja daga kan gwaji a baynar jama'a.
Ashok Gehlot  ya ce idan ta zama dole, Majalisa za ta yi zaman dirshan a kofar gidan Firayi minsta
Hakan ya zo ne bayan da jagorartara wani wasan kwaikwayo a Raj Bhavan a Jaipur, Babban minista Ashok Gehlot a ranr Asabar yana mai cewa idan ya zama dole, 'yna majlisar baki dayansu za za su gana da shugaban kasa  su kuma yi zaman dirsshan a kofara godan Firayi mistnista domin a magnace matsalar siyasar jihar.
A wani taro na jam'iyyar Congres Legislatiyre Party CLP, Mista Gehlot ya  nuna cewa burinsu sihine su na 'yar kashi a zauren majalisar domin su nunwa cewa sauran 'yan majalisar da magoya bayansu na tare da shi a wannan fada da ake yi na nuna iko.
"ya na mai cewa gwamnati ita ta ke da rinjaye kuma ta ke son gwada kwanjinta a zauren majalisa", a wata sanarwa da shugaban masu tsawatarwa na majalisa Manesh Jishi ya fitar bayan wani taron na jam'iyyar CLP ya ce
An yi taron jam'iyyar na CLP ne a wani otal din da 'yan majalisar na bagaren Gehlot suke boya na kwana da kawanaki.
"babbaan ministan ya nememuu da mu zama cikin shirin cigaba da zama a otal din na sai baba ta gani.
idan har bukatar haka ta tas, a cewarsa, za mu je mu gana da shugaban kasa sannan mu yi zaman dirshan a kofar gidan Firayi Minista," Shugabann jam'iyyar ya ce.
Dole ne Gwamnan Rajasthan ya kira wani zaman majalisa domin ya bari majalisa ta tabbatarwa da rinjayenta, shugaban jam'iyyar Rahul Gandhi ya fada a ranar Juma'a, yana mai zargin hadin bakin BIp na kokarin kifar da gwamnatin Ashol Gehlot ya fito karara
Wannan kasa ana milkinta ne bisa tsarin mulki ba kuma doka da oda
Ana kafa gwamnati ne a kuma gudannar da ita a bisa bukatun jama'a.
Hadin bakin na kokarin kifar da gwamnatin Rajasthan ya fito karara
Wannan kuma wani cin fuska ne ga mutanen 8 'yan asalin Rajasthan.
Don hka dole ne gwamna ya kira zaman majalisa a inda gaskiya za ta bayyana a gaban kowa da kowa a wannan kasa" Mista Gandhi ya aika ta sakon Tuwita a harshen Hindi.
Babban minista Ashok Gehlot ya fadawa 'yan jam'iyyar Congress a majalisa a ranar Asabafr cewa a shirye ya ke ya je ya sami shugaban kasar Indiya domin ya tabbatar da cewa abin da ya kira "hadin baki"  don gwada karfin a majalisa bai ci nasara ba.
Mista Gehlot, wanda ya gudanar da zanga-zangar na awowi a gidan Gwamna Kalraj Mishra a ranar Juma'a, don matsa lamba don yin babban taro ranar Asabar daga bisani aka bada sabuwar bukatar da gida suka amince da ita.
Mista Mishra a daren jiya ya tambayi Mista Gehlot da ya sake mika bukatarsa ta neman a kira majalisa ta zauna, yana mai lissafa wassu dalilai guda shida na kin amincewa da haka
Wannan bukatar zaman za a aikata zuwa ga gwamana nan ba da jimawa ba.
Mista Gehlot ya zargi gwamna da jan kafa kan zaman majalisar saboda "ya na cikin matsin lamba" ya dakile nuna karfin nuna ikon gwamnati.
Kamar yadda Mista Gehlot ya hadu da 'yan majalisar zartarwansa, wata tawaga ta jam'iyyar BIP a karkashin shugabanta na Rajasthan Satish Poonia da kuma shugaban 'yan adawa Gulab Chandra Katria sun gana da gwamna don tattauna matsalar cutar COVID-19 a jihar.
Hadarin jirgin sama na Utah: wani jariri da wasu magidanta 2 sun rasa ransu a bayan gidansu
Hadarin ya faru ne a ranar Asabar bayan azahar yayin da wani jirgin sama kirar PA-32 mai dauke da mutane shida ya rikito a bayan wani gida a birnin Jordan ta yamma, wani mai magana da yawun hukumar kula da zirga-zirgan jiragen sama ta kasa da kasa, Allen Kenitszer ya na mai cewa.
Mutame uku da ke cikin jirgen sun mutu ciki har da matukin jirgin wanda 'yan sanda suka gano da cewa sunansa  Lee Wyckloff ne dan shekara 43 da 'yarsa mai watanni 9 da haihuwa da Mlda Shbonis mai shekaru 36 da haihuwa a cewar 'yan sandan yammacin Jordan.
Matar matukin jirgin na cikin halin rai kwakwai-mutu kwakwai da kuma wani yaro dan shekara 2 wanda ya kone sosai.
An ba wani dan shekara 12 magani a wani asibiti na unguwa an kuma sallame shi, wata mai magana da yawun 'yan sanda birnin yammacin Jordan mai suna Jennifer Worthen ta fadawa gidan Talbijin na CNN ranar Lahadi.
Wata mata 'yar shekara 72 wacce ta ke gidan a lokacin da jirgin saman ya rikito a kai nma cikin wani mummnuna hali a asibiti a cewar wani sako da hukumar 'yan sanda ta sa dandalin sada zumunta na Tuwita a ranar Lahadi.
Jirgin da ta fado ya kuma lalata wasu gidaje guda uku, a cewar Tim baker mai magana da yawun rundunar 'yan sandan birni yammacin Jordan .
Ba a san dai musabbabin hadarin jirgin ba.
Hukumar kula da zirga-zirgan jirgen sama ta kasa da kuma hukumar kula da kiyaye hadarin ababen hawa ta kasa na bincike.
Masu saye na rubibi kan gidajen alfarma na lovely Banks
Karin maganar da ke cewa inda kudinka za ka sha shagalinka ta zama gaskiya ga sabbin wadanda suka mallaki katarfaren gidan da ke Lovely Banks da aka sayar a bisa fasarashin miliyan $1.277.
Masu aniyar saye da wadanda ke neman wurin zama abin kwatance wanda ba shi da nisa da daga tsakiyar Gelong sun yi turuwa don ganin katafaren gida a tsakiyar fili mai hekta 1.35 da ke da wurin ajiye motoci 14 da tafkin ninkaya, da kuma kallon bakin gabar Corio.
Kamfamin Harcourts, wakili na rewacin Geelong Joe Grgic ya ce daya daga cikin manyan wuraren 1 Cuddihy Court an saye shi kwanaki 10 da sa shi a kasuwa.
Ocean Groves ya gyara gidan Broome ya kuma sa shi a kasuwa
Gidajen da suka dace da kebe - kai
"Mun samu tayi daga mutane da yawa daga kuma wurare daban-daban," Mista Grgic ya ce.
"Mun sayarwa wani mutum ne da ya ke cike da farin ciki."
Gidan mai hawa biyu ne mai dakuna hudu da ya kunshi da wani babban falo mai girman da zai iya dauke doguwar kujera.
Sabbin masu wurin za su ji more wurin hutawa guda uku, da wurin dafa abinci da aka gyara, da kuma wurin shakatawa a farfajiya da ke kallon wani tafkin ninkaya.
"Wani hadi ne na kawa da jin dadin rayuwa, kasancewar wurin mai fadin eka 3 kuma yana nan ba a wani wuri ba", a cewar Mista Grgic.
"Na samu wasu masu saye daga Melbourne da suka zo nan, suna cike da mamakin kusacinsa ga komai da komai, amma kuma yana da wani abu na karkara.
"Ina da mutanen da ke taikaicin rashin sayen wurin, kuma har yanzu da akwai masu sayen da ke ta lalube."
Ya ce yalwataccen rumfar wacce ta kunshi wurin ajiye motoci biyu da kuma wata rumfar da za ta iya ajiye motoci 10-12, wurin ya dace da ajiyar kananan ababen hawa da majanye na da ake makalawa a mota na zuwa nishadi.
Daruruwan Masu Zanga-zanga Sun Taru a Cikin Garin LA don nina goyon bayansu ga masu Zanga-zangar Portland
LOS ANGELES (CBSLA) - Kimanin masu zanga-zanga 300 ne suka hallara a cikin garin Los Angeles a ranar Asabar da rana don nuna goyon baya ga wani gangami na tsawon watanni biyu a Portland, Oregon, inda jami'an tsaro na tarayya ake bincikar su bayan wata arangama da suka yi da masu zanga-zangar.
An yi irin wadannan taron a duk fadin Amurka a Boston, da Chicago, da Cleveland, da New York da kuma sauran wasu biranen.
Kungiyoyin ƙin jin jinin mulkin kama-karya da na samar da 'yancin matasa ne suka shirya zanga-zangar ta LA.
Gangamin taron Jama’ar sun yi tattaki ne zuwa hedkwatar Ofishin ‘yan sanda na Los Angeles da ke Farkon da kuma Babban tituna, sannan zuwa Cibiyar Tsare jama'a ta cikin birni.
Har ila yau masu zanga-zangar sun koma zuwa ga filin Alameda na babar hanyar 101, amma daga baya suka tafi.
Wasu daga cikin masu zanga-zangar an gansu suna farfasa tagogin gine-ginen gwamanatin tarayya na cikin gari da alamomin hanya da kuma allunan sunayen wurare na hukumomin tarayya wadanda suka zazzane su da kalaman batanci.
Aƙalla an kama mutum ɗaya a yayin zanga-zangar.
'Yar Majalisar Wakilai Val Demings ta yi magana kan takarar mataimakin shugabana kasa, ta kuma caccaki Trunp kan batun gafartawa masu laifi
'Yar majalisar Wakilai Val Demings (Gundumar Florida) ba ta yi kasa a gwiwa ba wajen nuna aniyarta ta zama 'yar takarar neman kujerar mataimakiyar Shugaban kasa a karkashin Joe Biden, ta kuma tsaya tsayin daka na neman hakan.
A wata hira da a ka yi da BlackPressUSA a cikin wani kamfe da ta ke yi da ta yiwa lakabi da #FIYAH!  A wani jerin bayanai na kai-tsaye, fitacciyar 'yar majalisar kuma 'yar kungiyar 'yan majalisa bakar fata, ta bayyana tarihin rayuwarta da kuma ayyukanta da ta yi na sadaukarwa da suka kawo ta wannan matsayi, tana mai cewa "duk kun san tarihi na".  Ni ubana mai aikin share-share da goge-goge ne uwata kuma aikin boyi-boyi ta ke yi a Jacksonville da ke Florida."
Demings na daya daga cikin 'yan kwamitin mutum bakwai na majalisar dattawa a Janairu kan batun tsige Donald Trump.
Duk da cewa Majalisar Dattawa ta wanke shi, tarihi ba zai taba mantawa da cewa shugaban na Amurka shine na hudu a jerin wadanda aka yi yunkurin tsigewa ba.
Tsohuwar shugabar kwamitin tsige shugaban kasa, a wata hira da ta yi da NPR a ofishinta na Capitol Hill a watan Fabarairu na cewa, "shin kwalliya ta biya kudin sabulu kuwa?  " A kowacce rana kwalliya na biyan kudin sabulu"
Bugu da kari, duk da cewa sakamakon ba yadda aka so ba ne, 'yan jam'iyyar Democrats na da damar da bin kadin batun ba tare da la'akari sakamakon ba.
A yayin hirar da ita, Demings ta fito karara ta bayyana cewa ba ta goyon bayan matakin da Shugaba Trump ya dauka na canzawa Roger Stone hukuncin da kotu ta yi na yin karya a gaban majalisar dattawa (cikin daya daga sauran shaidar zur da ya yi) da kuma yafewa sauran wadanda suka aikata laifin tare, sannan ta ci gaba da cewa, "wannan tsaurin ido da rashin hankali na yafewa abokanka, wadanda suka yi karya suka kuma yi shaidar zur don kawai su yi rufa-rufar barnar da ka ke yi."
Demings ce ke kan gaba a jerin wadanda Biden dauka a matsayin abokiyar takararsa, sauran sune shugaban CBC Kren Bass (Gundumar Califnia), tsohon dan majalisa mai wakiltar Geogia, Stacey Admas,Sanata Kamarla Harris (gudumar Califonia) da kuma Tammya Duckworth (gundumar Illinios), da Magajin garin AtlantaKeisha Lance Bottms, da tsohon jakadan Amurka Ambasada Susan Rice da kuma arin wasu mutanen.
Daga karshe ta na mai cewa, duk dai mutum daya ne kadai zai zartar da wanda zai marawa Joe Biden baya a wannan takara.
Wannan mutumun kuwa shine Joe Biden
Sannna, tana dariya sai ta kai hannunta zuwa bakinta cikin raha wai tana rada, ga maus kallon hira kai-tsaye, tana mai cewa "idan kun ga za ku kira shi don kamun kafa... sai ku yi"
Babu makawa dai, ko ma ina mutum ya karkata a siyasa, tarihi ba zai manta da wannan lokaci ba a matsayin wani yanayi na sauyi a siyasar Amurka da kuma fahimtar inda aka sa gaba.
Ana ganin tasirin hakan a kan Demnings.
Ta ce samun mata da yawa su firo takarar Mataimakin dan takarar shugaban kasa na nuni ne ga cewa wata dama ce ta kunno kai don ratsa shigen da ya rage - musamman kan batun mata Amurkawa 'yan asalin Africa.
" wadannan su ne damarmakin da na dade ina hari a rayuwata, watau in samar da wata dama ga matasa maza da mata wadanda a ka dade ana fada musu cewa ba irin launin fatar ikin da ake bukata ba ne, ko ba ku da kudi, ko kuma ku ba irin jinsin da ake so bane." tana mai cewa.
'yar majalisar ta yi alkawarin cewa za ta tabbatar da cewa 'yan kwamitin Jam'iyyar Democrat na kasa da kuma kwamitin yakin nema zaben Biden su yayata sun kuma amince da su yi aiki da kungiyar 'yan jarida bakar fata ta Amurka don ta yadda za a samu mutne da yawa su fita su kada kuri'arsu.
"Zan kirra ta wayar tarho ga [Shugaban kwamintin jami'yya] Tom Perez kuma ba wannan muhimmanci matuka," Demings ta alkawari.
Ta kuma yarda da cewa wannan wani abu ne da ya kamata a yi shi yanzu, a maimakon a a bari sai zuwa wani lokaci tsakiyar yakin neman zabe.
A martaninta ga tsohurwar sakatariyar kula da harkokin kasar waje Hillary Clinton cikin wata shawara da ta bayar da cewa, Trump zai iya kin barin fadar gwamnati na Whte House idan ya sha kaye a zabe, haka kuma a wani sharhi jaridar ba ke cewa Shugaban kasa na dabarun yadda zai yafewa kansa, Demings ta harzuka tana mai cewa" "a ma yi tunaninncewa zai gafartawa kansa, hakan ya sa ni tsanarsa matuka"
"Amma in ban da Trump, waye zai taba tunanin yin hakan?
Ina tunanin dai yana aikin ne kamar an sa shi tilas.
Domin wannan ba aikin da za a sa maka ido kawai ka rika karya doka yadda ka ga dama, ka kuma yi watsi da tsarin mulki.
Ina ganin dai dan dole ya ke aikin nan, amma ba ya son ya fadi zabe.
Daga dukkannin alamu wannan shugabana kasa ba ya so barin fadar White House, amma mun san yadda za mu yi maganinsa, ina ma za a sani a cikin 'yan kwaitin da za su yi haka"
An takaddama ta faru a motar bus yayin da direba ya fusata a sa-in-sa mai zafin kan takunkumi
A cikin wani gajeren hoton bidiyo wasu fasinjoji da direban a cikin motar bus ta Arriva a Liverpool sun kaure da fada akan amfani da takunkumi.
A na jin Direban Bus din na yiwa wata mata bayanin cewa ba aikinsa bane ya fadawa fasinjojin cewa su sa takunkumi.
Direban Bus din na mai cewa: "Ba fa aikina ba ne in fadawa duk wani wanda ya hau motar nan ya sa takunkumi."
A cewar wani wanda ya aka yi abin a gabansa yana mai cewa: "wani mutum da wata mace dattijuwa da suka soma sa baki da mayar mata da magana sai wata gagarumar hayaniya ta barke"
" Da hayaniyar ta yi yawa direban motar tasowa ya yi daga kujerarsa ya kuma zo ya tambayi me ke faruwa sannan ya fadawa matar cewa ba ta ma iya sa takunkumin ba yadda ya kamata"
"Wannan mata cikin fushi ta sauka daga motar tana mai ikirarin cewa za ta je ta kai karar abin da ya faru"
Wani mai magana da yawun kamfanin Arriva a cewa: "Kariyar lafiyar abokan huldarmu da kuma ma'aikatanmu a kullum shine fifikonmu.
"Yin amfani da kyallen rufe fuska zai cigaba da zama tilas ga kwastominmu a yayin da suke amfani abin hawa na jama'a (an kebance wasu da hakan da ta kama)"
"Muna da tsari karara da kuma alamu na fadakarwa ga kwastomominmu su fahimta kan wannan da kuma duk wasu matakan nisantar juna da cikin motocinmu. Wadannan bayanai na shafukanmu da kuma dandalinmu na sada zumunta"
Ya zama dole a sa kyallen rufe fuska a yayin da mutum ke cikin abin hawa na jama'a tun ranar 15 ga watan Yuni.
Yawan adadin wadanda suka kamu da cutar COVID-19 a yanzu a duniya ya kai sama da miliyan 16.3.
Yawan wadanda suka mutu sakamakon kamuwa da cutar ya kai sama da 650,000.
Mutane sama da 9,900,000 ne suka warke daga cutar a fadin duniya.
Amurka ita ke da yawan wadanda suka kamu da cutar COVID -19 a duniya da yawan adadinsu ya zarta miliyan 4.3.
Labarin Yarima Harry: Abokin mai sarautar Duke ya mayar da martani mai zafi kan wasu ikirari masu ta da hankali game mai sarautar a wani sabon littafi
Mista Stott ya fadawa shirin labarai na gidan Talbijin na SKY cewa abin da ke cikin littafin game da yarima Harry da kuma Meghan Markle ba shi da wani banbancin da abin da ke cikin jaridun labaran karin gishiri.
Tsoho sojin ya yi kira da cewa kamata ya yi a mayar da hankali kan abubuwan alheri da ma'auratan ke yi wanda ya hada da ayyukan da su ke yi na taimakon al'umma.
Mista Stott ya na mai cewa: "ina ganin abin da mu ke karantawa a nan ba shi da banbanci da abin da mu ke karantawa a shafukan jaridun labaran karin gishiri da kawai a ka mayar da shi littafi."
"Akwai ra'ayin marubuci kan yadda ya ke kallon mutum a nan, wannan abin da ya rubuta babu tabbacin cewa daga garesu ya ke"
"Ni dai ina ganin wannan kawai wani sabon hari ne kamar yadda sauran jaridun masu labaran karin gishiri ke kokarin yanke hukunci a kan su."
"Na fahimci cewa hankalin jama'a yanzu ya na kansu kuma mutane su na so su ji abin da suke yi, amma da zan so a ce an mayar da hankali ne kan irin abubuwan alheri da suke yi da ayyukan taimakon jama'a, a maimakon wanni abin da ya shafi rayuwarsu ta kashin kansu"
"amma saboda kawai suna kan wannan matsayi shikenan ba za su tsira daga sa ido ba."
A ranar Asabar ne wani mai bibiyar tarihin gidan sarautan ya ke fadin cewa mai Yariman mai rike da sarautar Duke na Susssex da kuma matarsa da ke rakiyar Sarauniya, sun "shugaban" sauran 'ya'yan gidan sarautar.
Dakta Williams ta fadawa shirin labarai na gidan talbijin na Sky cewa 'ya 'yan gidan sarautar sun kasa cin gajiyar irin baiwar ta farin jinin Yarima Harry da Meghan Markle ke da shi.
Mai sharhi a kan al'amuran gidan sarauta ta kara da cewa gidana sarautar na da wani tsari na fifiko, amma hankalin jama'a dangane da abin da suke so ba za a iya yi masa shamaki ko dakile shi ba.
Ta kuma cigaba da cewa: "gaskiyar mangana shine duk abin da suka yi don tallafawa saraunniya sai hakan ya dankwafar da abubuwan da sauran 'ya 'yan gidan sarautar ke yi, hakan kuma sai a rika ganinsa a matsayin wata matsala."
"Suna da wannan gagarimin farin jini."
"Sun bikin aurenu na rufin asiri babu wata kasaiata kasa da sauran 'ya 'yan gidan sarautar da suke matsayi daya, Andrew yayi ksauataccen biki, Anne ta yi kasaitaccen biki a aurenta."
"Sun yi dan kwarya-kwaryar biki amma duk da haka irin yadda aka yayata bikin Harray da Meghan duk da cewa bai kai na sauran William da Kate kasaita ba, amma saboda sun dauki hankalin duniya sai ya samu yayatarwa da na sauran ya samu."
Yarjejeniyar tsagaita wuta a gabashin kasar Ukraine wacce yaki ya daidaita za ta soma aiki da tsakar dare.
KYIV, Kasar Ukraine - Sojojin Ukraine da na 'yan tawaye da ke gabashin Ukraine sun  soma shirye-shiryen a aiki da wata "cikakkekiyar" yarjejeniyar tsagata wuta da aka shirtya za ta soma aiki a tsakar daren, wani yunkuri ne da jami'ai ke fatan zai kai ga wasu karin matakan samar da zaman lafiya a rikicin da su da ya kai shekara 6.
Shugabannin 'yan tawaye sun ce a ranar Lahadi, sun umarci dakarunsu da su shirya tsagaita wuta, sun kuma kafa dokar haramta amfani da makamai
Sojojin Kasar Ukraine sun ce  dakarunsu sun soma shirye-shiryen soma aikin da tsakaita wuta.
Idan ka yi da yarjejeneiyar, hakan zai "samar da hanyar da za ayi aiki da wasu saddarorin" daga cikin yarjejeniiyar da aka kulla a birnin Minsk, ofishin shugaban kasar Ukraine ya ce a farkon a wanna mako. yana mai kiran wannan tsagaita wuta da cewa "babban cigaba"
Kasashen Fransa da Jamus da suka shiga tsakani a 2015, Yarjejeniyar da aka kulla ta shirya sasanta rikicin da ke tsakanin Ukraine da 'ya awaren da kasar Rasha ta ke goyawa baya, rikicin da ya brake a shekarar 2014 bayan da kasar Rasha ta mamaye yankin Crimea da kuma goyawa 'yan tawaye baya.
Rikicin dai ya yi sanadiyyar mutuwar mutane sama da 14,000.
Shugabannin kasar Rasha da na Ukaraine duk sun yi san barka da yarjejeniyar tsagaita wutar da aka cimma a wata hira ta wayar tarho da aka yi da su a ranar Lahadi wanda hakan ya nuna muhimmancin aiki da yarjejeniyarda aka cimma a watan Disamba a wani taro a birnin Farisa.
Shugaban Kasar Rasha Vladamir Putiin ya nuna damuwarsa na kiraye-kiraye da Kyiv ta ke yi na a sake duba yarajejeniyoyin da aka yi a MInsk, ya kuma ce shugaban kasar Ukraine Volodymyr Zelenskiy " matsayinsa na babu madadi ga yarjejeniyoyin Minsk, ya sake fada wayar da aka yi da shi, toh ya kamata a yi aiki da su sau da kafa. A fadar ta Kremlin ta sanar.
Daga bangarensa kuwa Zelenskiy, jaddada bukatar "sake samun matsayi na zahiri ya yi wadanda za su kai ga sakin 'yan Ukraine da ke hannun 'yan tawayen gabashin Ukraine, da ke cikin yakin Crimea da Rasha ta mamaye da kuma a can cikin Rashan, a cewar ata sanarawa ta da fito daga ofishinsa.
A yarjejeniyar ta shekarar 2015 a na sa rai cewa Ukraine za ta iya mado da ikonta kan bakin iyakokinta da Rasha a wuraren da ke hannun 'yan yawaye ne kawai bayan ta ba su 'yancin cin gashin kansu an kuma gudanar da zabuka na cikin gida.
Yarjejeniyuar dai ta taimaka wajen rage yawan fadace-fadace, Sai dai sojojin Ukraine da kuma na 'yan tawaye sun cigaba da musayar wuta da manya - manyan bindigogin atileri da kuma kanana.
A watan Disamba ne, shuagabanin Kuraine da na Rasha da na Faransan da kuma na Jamus suka hadu a birnin Farisa dona sake wani zagayen tattaunawa, suna masu bayyana goyon bayansu ga yarajejeniyar Minsk da kuma yarda da farfado da matakan yarajejeniyar zaman lafiya.
Zelenskiy wanda ya lashe zaben 2019 bisa alkawarain da ya yi na kawo karshen rikicin na son Ukraine da farako ta samu damar iko da iyakokinta  kafin a fara zabn cikin gida, amma fadara Kremlin ta dage kan cewa a yi da yarjejeniyar ba tare da an sake yin bitar ta ba.
An dai cimma sabuwar yarjejeniyar tsagaita wutar ne a ranar Laraba tare da wata 'yan kungiyar tuntubar juna ta Tripartite da ta kunshi wakilan Rasha da Ukraine da kuma Kungiyar Kula da Tsaro da kuma Hadin kan kasasashen Turai, ta kuma samu karbuwa daga jami'an Tarayyara Turai.
A addua'r da ya saba yi duk ranar Lahadi a dandalin St Peters, Papa Roma Francis ya yabawa yarjejeniyar tsagaita wutar da ka kulla, yan mai addu'ar Allah Ya sa su yi aiki da ita "don ta sake gina karfin gwiwa ta kuma assasa ginshikin da zai samar da abin ada ake da bukata, na sasanta juna da a ke bukata da kuma neman zaman jira.″
Shin ko yarima Andrew zai shiga cikin jerin masu abin kunyar neman mata?
Masarauta na shirin mayar da martani kan wata yiwuwar bankada da ake shirin yi a bisa wasu takardu na Kotu kan samartakansa da Jeffery Epstein da Ghislaine Maxwell
Wani alkali a Amurka ya bayar da umarnin bayyana wasu takardu na sirri da suka danganci Epstein da kuma Maxwell
Takardun masu shafi 80 na dauke da sassa na shaidar da Maxwell ya bayar a shekarar 2016
Fito da takardun a na iya sa Yarima Andrew cikin matsin lamba saboda suna dauke da wasu wasiku tsakanin Maxwell da Epstien daga watan Janairu 2015
Virginia Roberts wacce a ke zargin dadiron attajiri mai abin kunyar nan, ta yi ikirarin cewa a shekarar 2015 a cikin takardun na Kotu cewa, an tilasta mata yin jama'i da yarima Andrew
Yarima ya yi shirin yakar yiwuwar sakin wadannan bayanai a wannan mako na jerin tonon asiri masu zub da mutunci game da alakarsa da mai lalata da yara kanana Jeffery Eptein da kuma wanda ake zargin suna tare Ghislain Maxwell.
Alkalin wata Kotu a Amurka Loretta Preska a makon da ya wuce ta bayar da umarnin fitar da takardun na sirri masu shafuka 80 na sharia, wadanda suka kai shafuka ɗari masu alaka da Maxwell da kuma Epstein.
Wallafa wadannan takardu zai zama wani babban nakasu ga Maxwell dan shekara 58, domin sun kunshi wasu sassa masu yawa na shaidar da ta bayar ga lauyoyi a shekarar 2016, ciki har da abin da nata lauyoyin suka kira "tambayoyin kwakwa" kan rayuwar jam'inta.
Hakan kuma zai iya kai wa ga matsin lamba kan Yarima Andrew saboda daya daga cikin takaradun ya kunshi wasiku tsakanin Maxwell da Epstein tun daga watan Janairun shekarar 2015 a lokacin da Virgina Roberts wata dadiron da ake zargi ta attajiri mai abin kunya, a ikirarin da ta yi kamar yadda ya kunsa a cikin takardun na Kotu cewa an tilasta mata yin jima'i da Yarima a lokuta daban-daban har sau uku.
Yariman ya tsaya kai da fata, a kuma lokuta da yawa ya karyata wannan ikirarin.
A wata wasika ta emel da aka tsegunta ta a shekarar 2015 wacce kuma BBC ta yada, na nuna cewe Andrew ya nemi taimakon Maxwell kan yadda zai yi da ikirarin da Virginia Roberts yi game da shi.
Ba ma tantanma cewa gaskiyar Yariman mai rike da sarautar Duke za ta bayyana
A cikin ta, yana mai harkar shakatawa na jama'a: "Ka sanar dani lokacin da za mu yi magana.  Ina da wasu tambayoyi ne da na ke so zan yi maka kan Virginia Roberts."
Maxwell ya amsa da cewa: "Ina da wasu bayanai.  Ka kira ni a duk da ka ke da lokaci."
A daren jiya, a cewar wata majiya da ke kusa da Andrew na mai cewa: Yariman mai sarautar hakimin York ba wani abu da ya yi na Allah wadai, don haka mu babu da wani abu da ya daga mana hankali dangane da sakin wasu takardu na Kotu.
Kamar yadda kotunan Amurka suke ta fama da kokarin nunawa, don kawai an shigar da wani zargi a takardun kotu hakan bai sa zarge-zargen sun zama gaskiya ba.
"Kotunan na Amurka sun yi kira ga kafofin yada labarai da kuma jama'ar gari da su yi matukar taka tsan-tsan da duk wasu zarge-zarge da ke cikin takardun na kotu.
Mu ma mun amince da hakan kacokam.
Mu ba ma haufin cewa gaskiyar yarima zata fito ne kuma za a wanke shi cikin 'yan makonni masu zuwa."
Ana tsare da Maxwell ne a wata cibiyar tsare jama'a ta Manhattan da ke tsakiyar birni, a na tsare da shi ne bisa jiran sharia'a da ya ke yi kan laifin da ake zarginsa da aikatawa na dauka da kuma shirya wasu daga cikin yara masu kananan shekaru da Epstein ya ribato a tsakanin shekarun 1994 da kuma 1997.
An kuma zarge shi da laifin yin shaidar zur da kuma karyar da ta yi na nuna rashin sanin matsayin shari'a kan cin zarafin da yake yi.
Ta musanta duk tuhume-tuhumen da ake yi mata.
Wasu Lauyoyi sun yi hira da ita cikin watan Afrilu da Yuli shekarar 2016 a cikin wani bangare na karar bata suna da Misisi Robert ta shigar, wacce yanzu ta ke amsa sunan mijin da ta aura Giuffre.
Kimanin shafuka 40 cikin adadin shafuka 418 na shaidar da aka bayar aka kuma fito da su baynar jama'a a shekarar da ta wuce, amma bayan yanke hukuncin kotu wacce mai shari'a Preska ta yi a New York, za a iya sakin wasu sassan nan da ranar Alhamis.
An ba Lauyoyin Maxwell mako guda su daukaka kara.
An gano gawar Epstein a dakinsa a gidan yarin da ya ke tsare a New York a shekara da ta wuce, ya mutu yana jiran yanke hukuncin alkali a zarge-zargen da ake yi masa kan laifukan da suka shafi jima'i.
Afrika ta kudu: Prince Ashwell da Marsha Cox tun yi magana kan yadda aka nuna musu wariyar launin fata
A wasu makoni da suka wuce ta bayyana cewa da akwai wasu abubuwan ban kunya da aka boye da kuma ke fitowa fli dangane da nuna wariyar launin fata a wasannin motsa jiki na Afrika ta Kudu.
Da akwai bukatar tattaunawa mai ma'ana da kuma daukar mataki kwakkwara domin samar da yanayin wasannin motsa jikin na kowa da kowa.
Tsohon tauraron Proteas maia tsaron gida a wasan cricket Aswell Prince ya caccaki tsaffin abokan wasansa fararen fata yana mai zarginsu da nuna masa wariyar launin fata ta lakabin da suke yi masa da shi da sauran 'yan wasan bakaken fata sunan "'yann wasan cike gurbi."
Prince ya na mai cewa 'yan wasan Proteas fararen fata na kiran bakakken fata kararada " 'yan wasan ciki gurbi".
Ya kara da cewa abin takaici ne cewa hatta manyan 'yan wasa bakaken fata kamar su Makhaya Ntini da yanzu kuma Kasigo Rababa wadanda suka kai kolowa na shahara a wasan, har yanzu wasu mutane na ci gaba da lika musu wannan suna na kaskanci.
Prince, wanda shine mai horas da 'yan wasa na kungiyuar Cape Cobras Franchise, ya furta wannan ne a wani taron karawa juna sani ta hanyar yanar gizo da Haddiyar Kungiyar Wasanni da kuma kungiyoyin cikin al'umma (UCSBO) ta gudanar a daren Alhamis.
Kungiyar na kokarin fadada tattaunawar da ake yi na wariyar al'umma a wasanni a Afrika ta Kudu wanda ya samo asali a tarihin kasar.
"Kamar yadda na fada a sakonnina a shafukan sada zumunta, ba niyyata ba ce na fitowa in bata sunan mutane ba ne, amma wadannan abubuwan da gaske sun faru...
RANARWASA: Ranar karshe ta gasar firmiya; juve zai dauki kanbi
Duba da irin abubuwan da ke faruwa a gasar kwallon kafa ta Nahiyar Turai a ranar Lahadi:
Rana ce ta karshe a kakar gasar wasannin kwallon kafa kuma da akwai abubuwa da yawa suke kan gaba: gasar zakarun turai da kuma gasar fidda gwani na cin kofin Europa, da gurabe biyu na karshe a gudun yada kanin wani, da kuma takalmin zinare da na wanda ya fi cin kwallo.
Kungiyar Kwallon kafa ta Manchester United, da Chelsea, da kuma Leicester na fafatawa kan sauran gurabe biyu na gasar wasan zakarun fidda gwani na champions league a bayan zakaru Liverpool da masu mara musu baya Manchester city.
Kungoyin guda biyu da mak daya ne ya raba tsakninsu yayin da kungiyar Leicester ta karbi bakuncin United.
Wolverhampton da Tottenham na fafaftawa don kaiwa ga matakin karshe a gurbin gasan wasanEuropa.
Aston Villa da Watford da kuma Bournemouth tuni suna ta neman kaucewa gurabe biyu da suka rage na koma baya, wanda tuni wacce Norwhich take wannan matsayin.
Da sauran wasa daya tak da ya rage musu, dan kulob din Leicester Jamie Vardy shine kan gaba a cin kwallaye 23, a inda ya zarta Danny Ings na Southampton da biyu, ya kuma ba dan Arsenal Pierre-Emerick Aubameyang rata da kwallaye uku.
Wasannin share fage na tallata gasar ta firimiya ta soma ne da Swansea a inda ta karbi bakuncina Brentford a bugun farko na wasansu na zagayen kusa da na karshe.
Fulham ta kara da Cardiff a wata karawa ta kusa da na karshe somawa daga ranar Litinin.
Leeds da West Bromwich tuni likkafarsu ta daga, daga gurbi na biyu a gasar fidda zakaru.
Kungiyar Juventus za ta iya maimata lashe gasar serie A wanda ta ke yi a karo na tara a jere da doke kungiyar Sampdoria.
Wannan zai fitar da Bianconeri da maki bakwai akan Intermilan masu mataki na biyu da wasannin biyu ne kadai suka rage musu.
A can karshen jerin kungiyoyin, Lecce na bukatar ta doke Bologna domin ta inganta damanmakinta da zai kautar da ita daga faduwa.
Kungiyar na maki hudu kasa da Genoa wacce take mataki na 17, wacce ta buga wasanni da yawa.
'Yan sanada masu binciken laifi na farautar wasu gungun matasa bayan da suka kai wani 'mummunan' hari a Edingburgh
An jiwa wani mutum mummunan rauni da ka iaya nakastashi bayan da wasu su uku suka afka mi a Edingburgh.
Mutumin dan shekara 29 an ji masa mummuman rauni ne a kan titin Drum da ke unguwar Gilmaton a tsakani karfe 11:00 zuwa 11:30 na daren Asabar.
'Yan sandan Scotland sun ce an kai mutumin asibitin City Riyal Infimary da munanan raunuka.
Det Con Miles jami'in da ke jagorantar binciken ya ce "wannan mummunam hari an yi shi ne cikin ruwan sanyi ba tare da wata tsokana ba."
Wandanda ake zargi sun ranta a kare ta wajen layin Newtoft.
An kwantanta kamanninn daya da cewa dan shakaru 30 ne, mai tsawon kafa 6 kakkaura.
Yana da gashin kai maras yawa, yana sanye da farar riga da bakin wando da kuma bakin takalmi.
Det Con Miles ya kuma da kara da cewa:' " ina kira ga duk wanda ke yankin a kima lokacin da abin ya faru, ya kuma ga wani abin da bai yarada da shi ba ya zo ya yi mana bayani."
Wani mutum ya ji mummunan rauni yayin da motar shanu ta tuntsire a Wexford
Wani mutum ya samu munanan raunuka a wani hadarin mota na taho-mu-gama da ya faru a safiyar yau a kan gadar Ferrycarrig da ke Wexford.
Wata motar shanu wacce ta kwacewa direbanta ta daki wata gada ta kuma tintsira tare faduwa a wani filin ajiye motocin da babu kowa.
Direban motar dan shekara 34 ya ji munanan raunuka a hadarin da ya faru da misalin 1.50 na yamman yau.
An garzaya da shi babban asibitin Wexford kuma yana cikinn wani mummunan hali.
Masu bincike na shari'a a halin yanzu suna nazarin inda hadarin ya faru da kuma rufe gadar, an kuma samar da wata hanya ta daban a maimakon wannan.
Shanu da yawa sun mutu a hadarin na taho-mu-gama.
Gardai na kira ga duk wani wanda ya ke tafiya kan hanyar daga karfe 1.45 na yamma zuwa karfe 2 - ko kuma duka wani wanda ya kasance a wannan yankin da Allah Ya sa ya ga faruwar hadarin - da su tuntubi ofishin Garda na Wexford a kan lamba 053 916 5200, layin sirri na Garda shine 1800 666 111 ko kuma ko wane ofishin na Garda.
Jeetandra, Shobha Ekata da kuma Tusshar Kapoor sun tuna baya ciki kasaita
Jarumin fina-finai Tusshar Kapoor a ranar Lahadi ya yada wasu hotuna kuciyarsa cikin kasaita don murnar bikin zagayowar ranara iyaye ta duniya.
Jarumin ya yada wasu jerin hotuna da suka kunshi hotunansa yana yaro shi da mahaifinsa Jeetendra da babansa Shobha da kuma kuna kaawarsa Ekta Kapoor da kuma wani na baya-bayannan da ke dauke da shi da dansa.
A tsohon hoton maras launi, an ga jarumi Jeetendra ya yi tsayuwar daukar hoto yana rike dan jariri Tusshar da Ekta Kapoor a hannunsa.
Ana iya ganin matar Jeetendra a tsaye kusa da mutanen uku a cikin hoton.
A hoto na biyu Tusshar Kappor da dansa Laksshya na tsaye cikin fara'a da annashuwa suna kallon Kamara.
A rubutun da ya saka a jikin hoton da ya yada, ya rubuta "Ina taya ku murnar zagayowar ranar tunawa da iyaye"
Tusshar Kapoor yana zaune da 'ya'yansa da ba uwa.
An haifi Lakshiya ne ta hanyar daukar cikinta a wajen mahaifa a shakarar 2016.
Wadansu lokutan jarimin na yada hotunan da bidiyon karamin dan na sa a shafukan sada zumunta na Instagram.
A bangaren aiki kuwa, ganin karshe da aka yiwa Tusshar Kapoor shine a Sabki Phategi.
Ana sa ran sake ganinsa ne a fim din 'Laxmmi Bomb' wanda Raghava Lawarence ya bayar da umarni.
A cikin fin din da akwai kuma Akshay Kumar da Kiara Advani.
A daya bangaren kuma Ekita Kapoor ya shirya wasu shirya-shiryen Talbijin da kuma Fim kamar su Dream Girl da Hum Paanch da Dolly Kitty aur Chamakte Sitare, da Ye Hai Mohabbatein, da Kahaani Ghar Ghar Kii da kuma Kasturi da sauransu.
Bayan wania tsawon lokaci da ma'aikacin dan majalisar wakilia Vern Bucahnann ya mutu sakamakon kamuwarsa da cutar Koronabirau
"Gary cikakken ma'aikaci ne da kwarai wanda kuma ya sadaukar da kans ga aikinsa na jam'a gaba da baya", Bucahnan ya ce a shafinsa na Facebook.
" Ya taba rayuwar kowa, wadanda suka yi mu'amilla da shi ta kuasa da kusa suna kaunarsa.
Ba zan taba manta sakin fuskarsa ba da fara'arsa da kuma ganin irin jin dadin da ya ke yi wajen taimakon mutane"
Ofishin Dan Majalisar Wakilai Buchanan ya aika da wani sako ta shafinsa na dandalin sada zumunta na Twitter a farkon watan nan ida sakon ke cewa Tibbets bai yi wata mu'amilla ta aiki ba da kowa a wannan ofishi a baya-bayan nan.
Tibbets, mai wakiltar Dan Majalisar a ayyukansa na waje, ya yi aiki da Buchanan tun shekarar 2011.
Birnin Florida ta bayar da rahoton bullar alkalumman wadanda suka kamu da cutar 414,511 tun lokacin da aka bayar da labarin annobar, wannan ya haura na birnin New York da 411,200, a cewar hukiumomin lafiya na jihar.
Yawan adadin wadanda aka kwamtar a asibitit ya karu da 79% tun ranar hudu ga watan Yuli, kamar yadda alkaluma daga ma'aikatar Lafiya ana jiha ya nuna.
Sashen kula da marasa lafiya da ke bukatar kulawa ta musammam na asibitoci 50 ne suka cika taf a ranar Asabar, kamar yadda bayanan ya kunsa.
"Mun fito da wani tsarin da zai iaya tasiri" A cewar DeSantis a watan Yuni.
" A lokaci guda kuma, mu yi aikin 'yan sanda tare da sa tara kan masu aikata laifuka, wani abu ne da ba zai haifara da, da mai ido ba."
Mai shari'a ya musanta zarginsa da ake yi na hana aiwatar da umarnin kotu da ta yi umarnin sakim yaran da ke tsare a hannun jami'an kula da shiga da fice.
A hukuncin da ta yanke a zaman da ta ranar Asabar, mai shari'a Dolly Gee  ta yi amai ta lashe dangane da matsayar da ta dauka ta na mai cewa hukumar kula da shige da fice ta Amurka ba sai ta saki yaran nan da ke hannunta ba idan har hanyoyin guda uku da ta zana ba kawo su a hunkuncin da ta yanke a baya kan wannan batun ba.
Amma mai shari'ar ta jaddada a umarnin da ta bayar cewa duk da haka hukumar kula da shige da ficen ICE ta na da hakkin sakin yaran a lokacin da ya dace.
Hanyoyin da Mai shari'ar ta zayyana sun hada da sakim iyalan da ke tsare a hannun hukumar ICE a tare, sakin yaran ga wani wanda zai dauki nauyinsu ko sakin iyalai a bisa dogaro da wani umarnin kotun tarayya
Shalyn Fluharty, daraktan Proyeco Dilley, wata kungiya da ta ke bayar da taimako ta fuska doka ga iyalan da ke tsare, ta yi Allah wadai da yunkurin da zai ba hukumar ICE damar daukan hukuncin ko su ci gaba da tsare yara a wurnsu.
Fluharty na mai cewa "Ni a wurina hakan na nufi cewa za iya tsare yara har illa ma shaAllah kuma ba su da wata hanyar fita sai har hukumar ICE ta yarda da hakan ko kuma iyali sun amince su rabu tukunna.
Ana tsare iyalai a wasu wuraren tsare mutane da hukumar ICE ba kula da su-Berks da ke Pennsylvania, da Texas ta kudu, (Dilley) da kuma gundumar Karnes shima a Texas.
Shekarun yaran da ake tsare da su a wuraren su n kama ne daga shekara 1 zuwa 12, a cewar lauyoyi da kuma masu bayar da shawara wadan da ke bayar da taikmako ta fuskar shari'a.
Gee - wacce ta ke sa ido kan aiki da yarjejeniyar Flores wacce ta shardanta kiula da yaran da ke tsare --  tana mai cewa a watan Yuni " rashin aiki yadda ya kamata da yarjejeniyar ko kuma banager-bangera  da kuma kin aiki da ka'idar sa takunkumi da bayar da tazara da juna ", hakan zai tilasta a dauke kula da yaran zuwa wani wuri daban
Da akwai wadanda ake tsare da su 969 a hannun hukumar ICE da ke dauke da cutar Koronabirus wadanda ko an killacesu ko kuma an sa musu ido har zuwa ranar 23 na watan Yuli, a cewar hukumar ICE.
Cikin wadannan adadi, da akwai 25 da aka tabbatar suna dauke da cutar a Karnes, daya a Dillsy, biyu daga cikin wuraren tsare da iyalai.
A baki daya dai, an samu a sama da mutane 3,700 wadanda ake da tabbacin cewa sun kamu a yayin da suke tsare
Wani mai gabatar da shirye -shirye a radiyo a birnin Seattle wanda ya yiwa shugaba Trump zanbo kan martanin da ya yi ga masu zanga-zanga, yanzu ya dawoa ya na mai cewa ina da bukatar a bani bindiga bayan da aka yi raga-raga da kantin sah shayi na Starbucks da ke karrkashin benen inda ya ke
Paul Gallanta na yiwa mummunan zanga-zangar da aka yi a Seattle wani irin kallo bayan yiwa Domald Trump zambo a watan Yuni a inda ya ke cewa 'yan ta da zaune tsaye na kone-kone da kwasar ganima a birnin Seattle.
Ba a dade ba, masu tarzoma su ka iso kusa da gidan mai gabatar da shirin radiyon.
" Sai na ji ina da bukatar in mallaki bindiga saboda wannan ya nuna karara cewa haka wannan abin zai yi ta faruwa" Gallant ya fadi haka ne a shafinsa na sada zumunta na Twitter a ranar Asabar da dare bayan da ya dawo gida ya taras da wani kantin shan shayi na Starbucks da ke kasan gidansa an yi "raga-raga" da shi. Aikin wasu masu barna.
"Abin ya isa haka.   Sai abin ya zama min kamar wani wurin da aka yi taron sharholiya na 'yan unguwa bayan taro ya watse.  Yanzu haka ina cikin fushi."
Wannan martani sai ya fito da cikin hannun riga karara a inda a watan jiya Trump ya koka da cewa Magajin garin Seattle ya kau da kai masu zanga -zanga cikin tashin hankali na kokarin kwace garin.
Yana mai cewa. "Wadannan masu sassaucin ra'ayi ba su san abin da suke yi ba".
" Wadannan 'yan ta'addan na kone-kone da kwasar ganimar kayan mutane a biranenmu, sun dauka hakan daidaine ko a cikin kabarinsu"
Gallant wanda ke gabatar da shirin Danny & Galant a tashar Radiyo ta Seattle ESPN, ya mayar da martani a shafinsa na Twitter yana mai cewa: "Na zagaya yawon gani da ido da kafa jiya da dare, nidai ban ga inda aka yi kon-kone, ko barnata kayan jama'a, ko kuma rasa rai ba.  A yi Kurum."
"Yan sanda sun gargadi Galant da ya kuracewa gidansa saboda gudun cewa watakila an dasa nakiya a kantin shayin Starbucks na kasansa da aka yiwa raga-raga.
Gallant ya aika hotunan barnar da 'yan zanga-zanga su kayi, yana mai cewa "aiki ya yi kyau a - sai dai" sannan ya ci gaba da fadin cewa, ya ga wuta na ci a wani nesa da shi kadan.
" ban san abinda ke faruwa ba, amma za mu je sansane-sansane irirn na mage don gano abin da ke faruwa."
Wannan saurin juya akala da Gallant yayii ashe shuka ne a idon makwarwa, 'yan jamiyyar conservatives sun rika tsokanar Gallant kan abin da ya fada a baya, aika sakwanni ta Twitter irinsu "a yi kurum" da kuma "huh, watakila fa Trump na ya yi gaskiya."
Jason Rants, wani mai gabatar da shirye-shirye a radiyo a Seattle ya na mai cewa, "Daga dukkan alammu daga karshe dai zamu dan je kewaya da muka tattauna."
Gallant ya gane raha ya na mai mayar da maratani: " Yau na farka da wasu jerin sakonni na Tuwita daga wasu jama'u a da ke ce min 'asha kuruminka kawai' gare ni.   Dariya na ke ta yi."
Ya ce, yana kan bakansa dangane da abin da ya fada, kamar yadda ya yi dan tattaki a yanki mai cin gashin kansa ta da 'yan tayar da kayar baya suka kikira bayan sun ankara sun kuma gano cewa bai kai yadda suke zato ba.
" sai ga a shi an barke da kone-kone da kuma kwasar ganima," yace.  "Kasaitacce"
Fiye da cutar Koronabirus dubu 13.85 ne a Indiya har zuwa yanzu, mutane 32,063 suka mutu, kashi 63.91% ne suka warke
Adadin mutane 8,85,577 ne suka warke kuma adadin kaso da suka warke ya kai kashi 63.91 cikin dari.
Garin New Delhi: Indiya ta ba da rahoton wadanda suka kamu da kwayar cutar ta coronabirus 48,661 a cikin awanni 24 da suka gabata, suna ɗaukar jimillar zuwa 13,85,522, kamar yadda bayanan gwamnati sun nuna.
Adadin wadanda suka mutu ya haura 32,063, a inda mutane 705 suka mutu a cikin awanni 24 da suka gabata.
Adadin wadanda suka kamu da kwayar cutar coronabirus ya ninka sau biyu a kusan makonni uku tun daga ranar 2 ga watan Yulin, a lokacin da kasar ta tsallake matakin dubu dari shida.
Yawan adadi na wadanda suka kamu da cutar Covid-19 na kasar ya kai makin dubu dari a ranar Juma'ar da ta gabata.
Tun daga wannan lokacin, an sami rahoton sabbin kamuwa da ya kai dubu uku. Wannan ita ce rana ta huɗu a jere lokacin da masu kamuwa da cutar COVID-19 suka ƙaru da fiye da 45,000.
Maharashtra a ranar Asabar ta ba da rahoton sabbin kamuwa da cutar 9,251 wadanda suka kamu da cutar ta COVID-19, inda suka dauki adadin a jihar zuwa 3,66,368 yayin da wadanda suka mutu suka kai 257, ciki har da 116 a yankin Mumbai yakin tsakiyar birni (MMR), zuwa 13,389, in ji Ma'aikatar Kiwon Lafiya ta jihar.
An sallami adadin marasa lafiya 7,227 a rana, inda aka dauki adadin wadanda suka warke zuwa 2,07,194.
Kimanin marasa lafiya dubu 8.85 ne suka warke ya zuwa yanzu; darajar farfadowa ya tsaya a kashi 63.91 bisa dari a safiyar yau.
Kaso na yawan wadanda suka kamu da cutar - yawan marasa lafiya waɗanda aka gwada aka kuma tabbatar sun kamu da kwayar cutar - shine kashi 11 cikin ɗari.
A farkon wannan makon ne, gwamnati ta ce tana da niyyar saukar da adadin wadanda suka kamu da ƙimar zuwa kashi 5 cikin 100.
Jihar Karnataka a ranar Asabar ya yi rajistar a sabbin wadanda suka kamu da cutar ta Koronavirus 5,000 a rana ta uku a jere, wanda hakan ya kai adadin ya haura 90,000 baki daya.
A Bengaluru kadai an bayar da rahoton sabbin mutanen da suka kamu da cutar zuwa 2,036 da suka kai jimillar adadin zuwa 43,503.
Matsayin birnin Delhi ya haura a cikin yawan wadanda aka samu da cutar COVID-19 kuma a halin yanzu birnin na matsayi na takwas tsakanin jihohi da yankuna da ke karkashin ikon gwmanatin tarayya a kasar, Babban Ministan Arvind Kejriwal ne ya faɗa a ranar Asabar.
A cikin wani karuwar adadi da aka taba samu a rana daya har zuwa yanzu, Kerala a ranar Asabar ta ba da rahoton mutane 1,103 sabbbi da suka kamu da COVID-19, wanada hakan ya daga adadin masu dauke da cutar zuwa 18,098, yayin da sama da dubban mutane 1.5 ake lura da su.
Kimanin mutane 9,420 ne ke karbar maganin cutar Koronabirus.
Yawan wadanda suka kanu da cutar Coronavirus a Tamil Nadu ya tsallake makin dubu dari tare da sabbin wadanda suka kamuwa da cutar 6,989 da aka rawaito a cikin awanni 24 da suka gabata, wanda kuma shi ne mafi girma a rana guda, kamar yadda bayanan gwamnati ya nuna.
Mutane tamanin da tara sun mutu kuma 7,758 sun warke a cikin awanni 24 da suka gabata.
Yawana adadin wadanda suka kamu a yanzu ya kai 2,06,737.
Gujarat a ranar Asabar ta shigar da bayanai mafi yawaa rana guda na adadin wadanda suka kamu da cutar Koronavirus da 1,081 na sabbin wadanda suka kamu da cutar, wanda hakan ya kai jimlar zuwa 54,712 yayin da marasa lafiya 22 suka mutu, ciki har da aka samu 11 a cikin Surat, a cewar ma'aikatar kiwon lafiya ta jihar.
Babban Ministan Maharashtra Uddhav Thackeray zai ƙaddamar da shirin bayar da gudummawar plasma a ranar 27 ga watan Yuli, bayan "Plasma Daan Sankalp Abhiyan" don binciken farko na marasa lafiyar COVID-19 da suka warke a yankin Dharavi na Mumbai.
Indiya ce ta uku a cikin kasashe masu fama da cutar Koronavirus a duniya bayan Amurka da Brazil, a hankali ta kara karfin gwajin cutar ta COVID-19 kuma ta gudanar da gwaje-gwaje sama da dubu dari 4.2 a cikin yini daya, Ma'aikatar Lafiya ta Tarayyar ta ce a ranar Asabar, tana mai yaba karuwar tare da danganaa samun wannan nasara ga yawan dakunan gawaje-gwaje da aka samu.
Annobar ta hallaka sama da mutane 6,33,000 a fadin duniya tun lokacin da cutar da bayyana a kasar Chima a shekarar da ta wuce, da samun yawan mutane sama da miliyan 15.5 wadanda suka kamu dac cutar, a cewar kamfanin dillancin labarai na AFP.
Coles ya yi watsi da kayan wasan yara ya rungumi littafai a wani sabon gangami saye-sayen kayyaki.
"Mun yi sauraro na hakika, kuma yana daga cikin muhimman abubuwa da suka sa muka tsara wannan shiri", a cewar Ms Ronson.
"Ba ma tunanin cewa mutane za su sake fito da tsaffin littafansu don sake amfani da su - muna tunanin za su so su ajiye kayansu, amma za su sake amfani da su a gudajensu idan suna son yin haka."
Ms Ronson ta ce wannan sabon gangamin wayar da kai an dade ana tunanin yin sa tun kafin bullar cutar COVID - 19, kuma duk da annobar, ta yarda da cewa yanzu lokacin yin wannan gangamin "ya yi daidai"  don soma wannan sabon gangami ganin wadatar lokaci da iyayen da ke da na zama tare da iyayensu.
Masu nazartar lamari na nuna damuwarsu kan yadda masu siyayya   kantuna ke nuna gazawa wajen damunsu da aka yi na sayen kayayyaki  barkatai daga maya-mayan kantuna, amma Ms Ronson ta ce su dai babu a garesu babu alamar gajiyawa dai.
"Mu ba mu soma ganin komai ba daga wannan abin da ake fada ba, amma mun sa ido" ta na mai cewa.
" Mun yi nazarin bayanai masu yawa, na mako-mako,da wata-wata, domin mu tabbatar mun kaddamar da abubuwan da abokanmu cinikanmu za su so" .
Gangamin sayar da kayayyaki na zabi irin hasali ma dai Coles ne ya soma shi a Australia da sunan Little shop wanda ya kadamar a tsakiyar shekarar 2015 tare da a cigaba da maimaita shi, wanda hakan ya samar da wata guguwar ciniki na ban mamaki a lokaci guda a tsakiyar shekara.
Tuni Woolworths ya biyo baya da nasa gangamin da ya kira 'Lion king Ooshiess wanda ya taimakawa manyan kantuna farfado da cinikinsu , kuma a baya-bayan nan wasu jerin kayayyakin kawa na lambu wanda a tsarin za a ba duk wanda ya saya kyautar filawowi da itatuwan magani su shuka.
Sai dai, duk da hashen manazarta na UBS da ke nuna cewa bangaren manya-manya kantunan sayra da kaya na Australia za su samu tashin farashin kayayyaki sakamakon cutar COVID -19 har zuwa karshen shekarar kudi ta 2021. Tasirin sabon tsarin kayan zanbi na sayarwa na Coles ba zai iaya tasiri ba.
Ms Ronson tace masu sayen kayayyaki sai su sa rai da karin wasu nau'in sayar zababbun kayyaki a gangami na gaba wanda hakan zai sa tsarin irin na 'little shop ' zai ja baya.
"Akwai irin wadannan ganganmin sayen zababbun kayayyaki da za su bullo a duniya, mu dai muna dada samun kwarin gwiwra ne daga irin wadannan abuwa daga kasashen waje.
"Ya kamata mu rika yin irin wadannan abiubuwan donmin mu tabbatar da cewa mun daga darajarmiu da kuma tarin maus cinikin da muke da shi
Masifa kan masifa: Texas na fama da ambaliyar ruwa sakamakon guguwar Hanna sai ga wata sabuwar masifar Korona birus ta bullaʻ
Masu hasashen yanayi na hasashen afkuwar "masifar ambaliyar ruwa" a kudancin Texas bayan da guguwar Hanna ta haddasa zaizaiyar wasu tuddai biyu, da kuma haifar da zubar ruwan sama kamar da bakin kwarya, da iska mai karfi da ke gudun mil 90 a cikin awa guda.
Guguwar ta iso gaba ne ranar Asabar a matsayina hadari mai mataki na daya (mafi kusaci ga doron kasa a cikin matakai biyar) daga bayan da ya rikide zuwa hadari mai tafiya kasa-kasa da kuma karfi, duk da haka zai iya zubar da ruwan saman na santimita 15 - 30 (inci 6-12) a ranar Lahadi tare da iska mai gudu a mil 60 cikin awa daya.
Wasu wuraren tuni sun soma bayar da rahotanni samun ruwan saman da ya kai santimita 23 (inci 9), ciki har da gundunmar Cameron wacce ke iyaka da kasar Mexico.
Guguwa iska mai dauke da ruwan sama ita ce mabudin kakkar jerrin guguwar da ake yiwa lakabi da Atlantic ta shekarar 2020, Chris Birchfield wani masanin yanayi ya gargadi mazauna yankin da su sa ido da bi a hankali, yana mai cewa "Da sauran aiki a gabanmu".   Har yanzu muna sa rai da afkuwar mummunan ambaliyar ruwa."
Jihar Texas ta sha fama da karuwar wadanda suka kamu da cutar Koronabirus a cikin 'yan kwankin nan.
Gwamna Greg Abbott ya fitar da wata sanarwa gargadin afkuwar bala'i ga gundumomi 32 wadanda ke kan hanyar guguwar, cikin hara da Harris, da fort Bend, da Galveston, da kuma Brazoria.
Yana mai cewa: "Duk wata guguwa ba karamar kalubale ba ce.
Wannan kalaubale na da sarkakiya, yanzu ya sake tabarbarewa gnuncewa guguwa ta ratsa ne a wajenda a ka yi fama da cutar COVID-19."
Zaizayewar tuddai nafarako ya faru ne da misalin karfe 5 na yamma a ranara Asabar mil 15 arewa da Port Mansfield, wanda ya ke kimanin mil 130 kudu daga Corpus christi.
Na biyn ya faru ne a kusa a gabashin gudumar Kennedy.
Sama da mutane 43,700 ne a kudancin Texas, cikin har da Corpus Christi, da Harlingen, da kuma Brownsville sue fana da rashin wutar lantarki a yammacin Asabar.
Masu bayar da agajin gaggawa a Corpus Christi sun sassaka jinshikai kuma mahada a shirin ko ta kwana idan ambaliyar ya ci tituna.
A wani sako da ya aika ta shifinsa na Tuwita, Shugaba Trump ya ce gwamnatinsa na sa ido kan guguwar Hannatare da Guguwar Douglas wacce take kan hanyarta ta zuwa tsbirin Hawaii dake tekun Atlantis.
Sherry Behme wacce ta ke zaune a bakin gabar tekun Coirpus Criti na mai cewa, wannan guguwar da ke dosowa ta kara mana damuwa da muke ji a lokacin annobar.
'Yar shekara 67 wacce ta ke yawan zama a gida saboda larurar lafiya da take fama da ita da shafi matsanancin ciwon huhu.
Ta ce: "wannan kamara wani duka biyu ne a gare mu.
Ina jin wannan ya fadarwa da mutane da yawa gaba.
"Za mu ga karshen abin.
Kowa da kowa na zaune kalau tare da karfin gwiwa da kuma zama tare."
Makomar wurin zaman dabbar koala a arewacin Brisbane ya fada hannun kotun tsare-tsare
Majalisar ta ce, baya da kasancewar mazaunin mai matukar muhimmanci ne ga dabbar koala, da kurege, da kuma goshawk mai ruwan toka, babbar mahada ce tsakanin hanyoyin zuwa korama Kabejin Tree da kuma mashigar daji na koramar Albany.
Masu haɓaka kadarorin sun yi kira ga ƙin amincewar majalisar a Kotun Tsare-Tsare da Muhalli, suna jayayyar cewa gina wurin ya bi ƙa'idar tsarar birane na shekarar 2014, zai kuma gamsar da tsarin gari da ba a iya cimma sa ba, kuma biyan buƙatar al'umma kuma za a iya "aiwatar da shi ba tare da wani tasirin da ba a za a yarda da shi ba."
Adawa mai ƙarfi na al'umma yana ci gaba kan aniyar da ake da ita na giggina gidaje na zamani.
Masu son gina wurin, yayin da suka dage kan cewa aikin da suke so za su yi ya, ya yi daidai da tsarin habaka birane, suna mai jayayya da cewa za a iya canza tsarin gine-ginen don kaucewa duk wani rashin bin ƙa'idoji maimakon a hana su aikin baki dayansa.
Ci gaban kamar yadda yake a yanzu, ya ƙunshi matakai da yawa, ciki har da gidan mai, cibiyar kula da yara, da kuma gidajen gari 39.
Fiye da mutane 120 ne suka gabatar da ra'ayoyinsu a lokacin sauraron shawarwarin, mafi yawansu suna adawa ne da aikin ginin a ya yiwa wurin girma kuma bai dace da wurin ba.
Shugaban ‘yan adawar BCC Jared Cassidy ya ce majalisar na bukatar siyan karin wasu filayen ne filin don kare dabbar koala.
"[Mai girma Magajin gari] Adrian Schrinner na bukatar dakatar da barnatar da kudaden masu biyan haraji a shari'ar kotun tsara birane, da tafi ya sayi wannan fili don kare namun dajin Brisbane," in ji Cr Cassidy.
"Wannan wuri yana daya daga cikin wurare masu muhimmanci na dazukan da ke kusa da mashigar manyan tsirrai na bakin ruwa kuma gida ne ga babbar al'umar Koala"
Cr Schrinner a wannan makon na mai cewa majalisar na son ganin an kare mazaunin dabbar Koala a garin.
"Mu ba mu yarda cewa wannan shirin giggina gidaje ya dace da wannan wurin ba," Cr Schrinner ya na mai cewa.
"Na fahimci cewa wannan batu na gaban kotu, mu dai fatan abin da muke son gani a matsayin sakamako shine kyakkyawan hukunci wanda zai sa wannan matsuguni na wadannan kananan dabbobi ya zama an kare shi."
Cr Schrinner ya ce taswirar mazaunin koala aiki ne na hadin gwiwa tsakanin majalisa da gwamnatin jihar, inda gwamnatin jihar ke da alhakin cikakken taswirar koala da hukumomin yankin za su yi amfani da ita wajen nazarin takaradu neman izinin yin gina-gine na zamani.
Abin ba karamin fito-na fito ba ne!
Coleen Rooney ya dau hayar Lauyan Johnny Depp a fafatawar da ke yi tasakaninta da Rabekah-Vardy kan Wagatha Christie
Uwaragida Rooney ta sa David Sherborne shigar da kara kan bata sunan da Madam Vardy ta yi mata
Bayan duk wani kokarin sasantasu ya gagara, 'yan gazagani na sa ran a yi kare-jini, birin jini na ban mamaki
Coleen Rooney ta dau hayar wani fitataccen Lauyan jarumin fina finai Johnny Depp da ya ke tsaya masa a shari'arsa. Shine zai tasya mata a shari'ar da ta ke na "Wagatha Chritie" da Rabekah Vardy.
Jaridar The Mail mai fitowa ranakun Lahadi ta fahimci cewa Madam Rooney ta umarci David Sherborne da ya shigar kara kan zargin bata sunan da Misisi Vardy ta yi mata na tsegunta wasu bayanai daga sahafinta na sada zumunta na Instagram ga wata jarida.
Wannan labari na zuwa ne bayan wasu 'yan kwanaki da aka mika wasu takardun shigar da kara a wata babbar kotu a inda ake zargin cewa uwargida Vardy, wacce ke auren dan wasan kwallon kafa ta kungiyar Leicester City Jamie Vardy, ta cutu a jiki da kuma kwakwalwa sakamakon azabtarwar da ta samu daga zarge-zargen da Misisi Rooney ta yi mata.
Takardun sun kuma ce 'yar 38 da haihuwa kuma uwar 'ya 'ya biyar "ta samu cutuwa daga tsananin azaba da tashin hankali wanda ya hakan ya bayyana ta yadda ta ke tsoron barin gida". Ta na mai karawa da cewa Varday, wacce ta ke dauke da ciki wata bakwai a lokacin. "an kai ta asibiti sau ukku... tana fama da cutar damuwaa sakamakon bayanan da aka saka da kuma abubuwan da suka biyo baya."
Da kuma wakiltar Depp a kararsa da ya kai jaridar The Sun kan zarginsa da ta yi na cewa jarumin fina finan mai duka mata ne, Mista Sherborne, dan shekara 50 na wakiltar mai sarautar gargajiya na Duke da matarsa Duchess na garin Sussex a karar da suka shigar a keta musu haddi kan kamfanin Associated Newspapers. Masu wallafa jaridar The Mail mai fitowa kowacce ranar Lahadi.
Bayan tattaunawar samun masalaha tsakanin ma karayan biyu,'yan gaza gani sun sa ran ganin tirka-tirka na ban mamaki a kotu a yayin shari'ar.
"Idan ma kana tunanin wannan Sharai'ar da jarumin fina finai wani shirin fim ne, to ka gyara zama ka saha kallon", a cewar wata majiya.
"Lallai danbarwara da ba karama ba ce.  Coleen ba za ta hakura ba, haka ita ma Becky.  Shari'ar za ta ja hankali sosai."
Rooneey ta na zargin cewa wani ya yi amfani da shafin sada zumunta na Instagram na misisi Vardy ya tseguntawa wata jarida wasu labaran karya dangane da ita.
An yi mata lakabi da "Wagatha Christe ne" fbayan ta yi bayanin yadda sanu a hankali ta shafe wata biyar tana rage yawan mutane da ke bibiyarta a shafin sada zumunta na Instagram har ya rage Misisi Vardy ce kadai ta rage.
Misis Rooney sannan ta yi ikirarin cewa, at saka wani labarin karya a shafin nata na sada zumunta na Instagram, wanda kuma labarin ya bayyana a shafin wata fitacciyar jarida.
A na ta karriyar a gaban shari'a. Misisi Vardy wacce ta musanta zargin, ta ce "an dora mata laifukan wasu ne da bada hakkinta ba, bayan da Misisi Rooney ta ce ta yada zarge-zargen ne da gangangan da kuma aniyar cutar da ita, cuta mai tsanani da kuma sa ta cikin tashin hankali"
Amma lauyoyin Misisi Rooney suka kalubalanaci wannan ikirari, suna mai zargin cewa bayanan irirn halin da ta shiga, "wasan kwaikwayo ne kawai" da ka iya dauke hankali daga ainihin gaskiyar lamari.
Wata majiya tna cewa, "takardun da Becky ta shigar a gaban kotu shirme ne, duk ba su da makama."
Rooney wacce ke auren tsohon fitaccen dan wasa kallon kafa Wayne Rooney - Lauya Paul Lunt ne ke wakiltarta a kotu, daga ofishin lauyoyi da ke Liverpool mai suna Brabners.
Vardy kuwa tana tere da Kingsley Napley na wania Kamfani a London, amma har yanzu ba a sani ba ko ta dauki lauya.
Mai magana da yawon Rooney ya ki ya ce komai.
Kungiyar yaki da nuna rashin adalci mai alaka da banbancin launin fata ta Amurka ta gudanar da zanga-zanga
Masu zanga-zanga sun mamaye titinan yawancin biranen Amurka domin jan hankali kan rashin adalaci da ke alaka da launin fata.
Sama da wata biyu ana ta zanga-zanga a Portland, da ke Oregon tun ranar 25 ga watan Mayu bayan mutuwar George Floyd yayin da ya ke tsare a hannun 'yan sanda a Minneapolis da ke Minnesota.
Gwammatin Trump ta aika da jami'an tsaro na gwamnatin tarayya zuwa Portland, wanda hakan ya kara izza wutar zanga-zangar.
Sai zanga-zangar ta rikide ta koma zanga-zangar adawa da zuwan wadannan jami'an garin.
A birnin Seattle 'yan sanda suna amfani da kulake da hayaki mai sa hawaye sun kuma kama mutane 45 a ranar Asabar bayan zanga-zangar da ke goyon bayan zanga-zangar ta birnin Porland ta rikide ta koma tashin hankali.
'Yan sanda suka ce sama da jami'an 'yan sanda 20 suka samu raunuka.
A ranar Asabar da dare a garin Austin ta Texas wani mutum ya rasa ransa yayin da wani yayi harbi a cikin 'yan zanga-zangar Black Lives Matter.
Rahotanni daga kafofin yada labarai na cewa watakila mutumin ne ya je kusa da wata mota da wani a cikinta ke dauke da bindiga, sai aka harbe shi da ita.
" Ni dai abin da na sani shine mutum ya mutu a lokacin da ke zanga-zanga abin da tashin hankali." Magajin gari Steve Daler na Austin ya fada a cikin wata sanarwa.
Adler ya na mai cewa, "na shiga cikin dimuwa da tashin hankali."
A birnin Lousville da ke Kentucky, wasu gungun masu zanga-zanga dake dauke da makami na kiran da a yiwa Breonna Taylor, wata mace bakar fata wacce ta mutu a Lousville a lokacin da 'yan sanda suka kutsa gidanta kwatsam dauke da umarnin kotu na "shiga babu sallama" suka kuma harbeta.
Saurayin Taylor ne ya fara yin harbin 'yan sandan a bisa tunanin cewa masu kutse ne.
An kori wani jami'in dan sanda saboda harbin da ya faru ga Taylor, sai dai sauran 'yan sandan babu abin da aka yi musu.
Shugaban kungiyar NFAC, wata kungiya mai gwagwarmaya da makamai ta bakar fata zalla da ke cikin masu zanga-zangar ta ce tana son 'yan sanda su binciki kisan da aka yi wa Taylor, sannan binciken a yi shi a bayyane.
'yan sanda sun ce uku da ga cikin 'yan kungiyar ta NFAC sun samu raunuka a ranar Asabar a lokacin da bindigar da daya daga cikinsu ta tashi abisa kuskure.
Kasar Poland za ta fice daga yarjejeniyar Turai da ke nufin hana cin zarafin mata
Gwamnatin Poland mai sassaucin ra'ayi ta ce za ta janye daga yarjejeniyar Turai dake kokarin hana cin zarafin mata.
Yarjejeniyar ta Santanbul ita ce ta farko da kasashen duniya ke shirin aiki da ita kan yadda za a hana cin zarafin mata, amma ministan Shari'a na kasar ta Poland Zbignew Ziobro ya bayyana kudirin da cewa yana da "illa" saboda ya bukaci cewa a koyawa yara game da jinsi daga mahanga ta mu'amilla da ilimin zamantakewar jama'a.
Ziobro ya na mai cewa a karshen mako, ranar Litinin zai fara shirye-shiryen bin matakai da ka'idojin janyewa daga yarjejeniyar.
"Wannan bangare na akida yana da nasaba da wajibcin canza ilimi a makarantu da wajen shirye-shiryen makarantu, dangane da ilmantarwa, da halaye, da hukuncin da samari 'yan asalin kasar Poland suka yi, a ra'ayinmu, zaton da ake yi na cewa ilimin jima'in halittu na gargajiya ne, kuma a zahiri duk abin da ya bayu ne ga yanayin zamantakewar al'umma da al'adu da kuma jinsi. "
A ra'ayin Ziobro, ƙudurin da a ka zartar da ya shafi ilimintar da yara da matasa da kuma dangantakar iyalai da ke tsakanin masu dabi'ar mata-maza da luwaɗi da maɗigo cikin yanayin zamantakewa, ba za'a yarda da shi ba.
"Haka kuma ba za mu amince da shigar da dabi'ar mata-maza da maza masu neman maza, da mata masu neman mata, wajen yada wannan dabi'a da 'yan rajin kare hakki da kuma 'na luwadi da ke son mayar da akidarsu zama doka kan jama'a", a cewarsa.
A ranar Lahadi Majalisar Turai ta ce ta "kadu" da cewa kasar Poland na janyewa daga yarejeniyar.
A garin Warsaw a ranar Juma'a, kimanin mutane 2,000 ne ciki har da kungiyoyin mata da kuma sauran masu rajin kare hakki ne suka yi wata zanga-zanga a kofar ofishin Ordo Luris, wata kungiyar da ke goyon bayan janyewar kasar daga yarjejeniyar.
"Ba za mu yarda a cucemu ba" Suna ta fada cikin rewa waka.
An kuma gudanar da irin wadannan zanga-zangar a wasu biranen kasar ta Poland.
Kasar Poland na daga cikin kasashen da suka sa hannu a yarjejeniyar da aka kulla a birnin Istanbul kan yaki da cin zarafin mata da kuma fadace-fadace na cikin gida a watan Disambar shekarar 2012 aka kuma zartar da ita a shekarar 2015.
"ku yi abin da ya ke daidai, amma kuma kun kasa yin daidai"
Paul Roberts wani tsohon mawaki kuma kafinta ya zama mai kirkirar manhaja a Hukumar Kula da Sarayin Samaniya ta Amurka NASA.
Shi da matarsa, wata tsohuwar Nas wacce ta yi ritaya daga Asibitin Methodist, da ke kiran kanta "wacce tara take ba ta cika goma ba". Na yin wata mujalla a yanar gizo, suna kuma halarta tarukan shirin ban dariya na Comic Con a shekarun da suka gabata.
Suna haduwa tare da 'ya 'yansu mata biyu da surukinsu da kuma jikansu dan shekara 7 a kowanne mako suna wasan jigsaw da kuma ludo na cikin nishadi.
"mutane ne masu abin ta'ajibi" a cewar misisi Roman yar shekara 38, game da iyayenta.
Sheryl Roberts 'yar shekara 65, ta fahimci hadarin da ke tattare da wannan annobar-tana da ciwon sugar, da Asma, da kuma ciwon zuciya wanda ka iya jefata cikin hadari babba.
Mijinta yana da ciwon huhu mai tsanani yana kuma dauke da wani abu da aka sa mi shi da zai bude hanyar jinin da suka toshe.
"Muna ta taka tsantsan, da matukar kiyayewa da kuma kauracewa jama'a" in ji Misisi Roberts.
Mijinta ya soma aikia daga gida da bazara a lokacin da jihar Washington da New York da kuma wasu sauran wuraren da ke kasar suka shiga wani hali mai wuya.
Mista Roberts a wani lokaci ya kan je siyayya a babban kantin sayar da kaya a wata sa a da aka ware na "dattawa" abin da za iya cewa shine "abin a zo a gani" na ma'aurata a 'yan watannin nan. Misisi Roberts tana mai cewa, shine mu zauna daga mota mu rika kallon fulawoyin da suka fito a filin Allah.
'Yar karamar 'yarsu ta na da kwazo sosai ita ma.
Amma daga ranar da ta dawo gida daga aiki tana attishawa wata rana a tsakiyar watan Yuni zuwa Yuni ana tunanin kan jiki ne.
Sai kuma ta soma tari, da zazzabi, da ciwon kai, da gudawa, ta kuma daina jin dandano da wari ko kamshi, wasu alamu na kamuwa da cutar Koronabirus.
"Ta fada min cewa, "ban san abin da ke faruwa ba mama, kuma ina sa takunkumi, ina sa safar hannu, ina kuma wanke hannuna""Misisi Roberts ta ce.
"Kana yin duk abinda ya dace, kuma sai da ka kamu da ita."
Elaine Roberts, wacce gwajin da aka yi mata ya nuna ta kamu da cutar Korona birus, ba ta kamu da mummunan rashin lafiya ba.
Amma ga iyayenta hakan sai ya fi tabarbarewa.
Mista Roberts da matarsa suna soma yin attishawa, sannnan sai tari, kamar dai yadda 'yar su ta yi, sai kuma ta soma zazzabia da kuma jiwon jiki.
Sannan sai ya "kwanta rashin lafiya cikin gaggawa" Sheryl Roberyts na iya tunawa.
Sai ya dimauce a ranar 22 ga watan Yuni.
Cikin tashin hankali, sai ta gwada karfin shakar iskar Oxygen din sa.
Gejin ya yi kasa, sai ta kira babbar 'yar ta na mai ba ta umarnin ta kai shi Cibiyar kula na gaggawa, ziyara ta biyu a cikin kwanakin biyu.
Sojoji sun karkashe tare da ragargaza sansanin 'yan bindiga a jihar Zamfara
Rundunar sojojin sama na gamayyar sojojin da suke yakin da aka labawa suna operation HADARIN DAJI sun yi raga-raga da wani sabon sansanin'yan bindiga da ke karkashin jagorancin wani mai suna “Dangote” a dajin Doumborou da ke jihar Zamfara.
Babban Jami'in da ke lura da ayyukan yada labaran da suka shafi tsaro, Manjo Janar John Enennche ya ce harin ta sama da aka kai wanda ya yi sanadiyyar mutuwar 'yan bindigan da dama, an aiwatar da shi ne bayan wasu rahotanni na lekan asiri na dan adam (HUMINT) da kuma tabbatattun hujjoji da aka samu na leken asirin da aka yi ta yi ta sama.
Manjo Janar Enenenche ya ce tsarin leken asiri na mutum da mutum da ake kira HUMINT ya tabbbtar da cewa 'yan bindigan su da kayan muhimman bukatunsu, da ababen hawansu da kuma daruruwan shanun sata, sun tashi daga inda a da suke, zuwa wannan sabon wuri kusa da wani wuri mai tsaunuka a cikin dajin
Enenche ya ce bangaren sojin sama na rundunar da ke yaki da 'yan bindigan daga bayan ta ya aika da wani rukuni na jiragen sojin saman Najeriya wada nda suka kunshi jirage masu saukar ungula masu dauke da manyan bindigogi da suka kai jerin hare-hare a kan sansanin.
A cewarsa, jirgen da suka kai harin yayi aikinsa yadda ya kamata a wurins ta inda ya dau sauti daidai ba tare da kuskurewa ba ya ragargaji 'yan bindiga da hakan ta sa ywancinsu suka rasa rayukansu.
Sauran wadanda suka yi kokarn su gudu cikin figici kuma an hallaka su a wani harin da aka kai musu ta  kasa."
A sakonsa na jinjina ga sojin sama na rundunar yakin mai lakabi da HADARIN DAJI Shugaban sojojin sama na Najeriya Air Marshal Sadique Abubakar ya yi kira ga sojin saman da su kara zage damtse a aikin da suke yi na kai hare-hare ga 'yan bindigar.
Shugaban sojin sama na Najeriya ya yi kiransu da su cigaba da tallafawa rundunar sojin da suke aiki tare da kariya ta sama domin a kawo karshen duk wani ta'addanci da masu dauke da makami ke yi domin dawo da zaman lafiya a yankunan arewa maso gabas da kuma gabas ta tsakiya na kasar.
Guguwar Hanna ta kayar da bishiyoyi yayin da ta ratsa ta kudancin Texas
Guguwa mai dauke da ruwan sama ta Hanna ta sassauta gudunta da karfinta bayan da ta fada a gabar teku na kudancin Texas a ranar Asabar 25 ga watan Yuli, amma jami'ai sun yi gargadin cewa guguwar har yanzu na kafin da zata kai ga matakin "barazana ga rayuwa" na ambaliya ruwa.
Hukumar Kula da Yanayi ta kasa (NWS) ta ce ruwa mai zuba da bakin kwarya ta kasance babbar barazana a kudancin Texas da kuma arewa maso gabashin Mexico a lokacin da gaguwar ta soma matsawa zuwa yamma -kudu amso yamma a ranar Lahadi.
Jorge Castillo ya yada wannan karamin bidiyon a Tuwita, ya kuma bayar da labarin da ya dauka, ya kuma dauki wannan bidiyon ne a kofar gidansa a Combes a Texas a ranar Lahadi da safe.
Rahotanni na cewa Amurka na matsin lamba 'yan kwangilar Nord Stream 2- RT labaran kasuwanci
Gwamnatin Amurka ta sake wani yunkuri na tilastawa wasu kamfanonin Turai da sua watsar da aikin da Russia ta ke jagoranta na shimfida butun iskar Gas na Nord Stream 2, Welt am Sonntag ce ta bayara da rahoton, tana mai bayar da misalai da mutanen da ke da masaniyar tattaunawa kan batun.
A cewar jaridar, Jami'ai daga ofishin kula da harkokin waje na Amurka, da kuma ofishin Baitul mali, da Ma'aikatar kula da makamashi sun tunkari 'yan kwangilar Tarayyar Turai da su tattabatar sun fahimci abin da ka zai iaya faruwea da su idan suka cigaba da yin aikin.
Kusan Jami'an Amurka sama da dozin ne aka bayar da labarin cewa sun tattauna akalla sau biyu ta yanar gizo da wakilan kamfanonin a 'yan kwanakin nan.
Yayin da yake magana cikin "sakin fuska" bangaren da Amurka ya jaddada cewa ya na so ne ya hana kammala aikina Nord Stream2, a cewar wasu masu sa ido kan tattaunawar.
"Na yi imani cewa barazanar da gasken-gaske ce ", a cewar daya daga cikinsu ga kafar yada labaran ta harshen Jamusanci.
Wadannan baraza sun zo daidai da wasu kalamai na Sakataren kula da harkokin waje na Amurka Mike Pompeo a makon da ya wuce, a inda ya ke gargadin cewa kamfanonin da suke cikin wannan aiki su "gaggauta fice yanzu" ko kuma su fuskanci hukuncia a karkashina sashi na 232 na dokar Kalubalantar Masu Adawa da Manufofin Amurka ta Hanyar Takunkumi (CAATSA).
Baya ga babban kamfanin samar da Makamashi na kasar Russia Gazprom wanda kan gaba a aikin, wasu kamfanoni da kasashen Turai sun shiga cikin aikin.
Kamfanonin su ne Engie na kasar Faransa OMV na Austria, da Royal Dutch Shell na UK- Dutch, sannan da Wintershall da kuma na kasar Jamus Uniper.
Yayin wata hira da ya yi da Welt am Sonntag, jaridar na mai cewa kokarin Amurkla na zagon kasa ga "muhimmin aikin samar da kayan more rayuwa" kutse ne cikin kwarya-kwaryar 'yancin gashin kai kasashen Turai.
A farkon makon nan dai, Majalisar Wakili Amurka ta amince da wani gyara a dokar Izinin Tsaro ta Kasa wacce aka fadada don shigo da takunkumi kan kamfanonin da ke cikin aikin samar da bututun iskar Gas na Russia na Nord Stream 2.
A cewar daya daga cikin wadanda suka gabartar da kudurin, matakan da za a dauka zai shafi kamfanoni ne da ke samar da, ko taimakawa jiragen ruwa, ko inshora ko kayan sukewa da dukar kaya a bakin gabar ruwa, ko turkewa da kulawa na wadannan jiragen, da kuma wadanda suke bayar da takardar shaidar inganacin aiki na Nord Stream 2.
Dukkannin harkokin kasuwanci na kasashen Turai da jami'an gwamnatoci sun yi ta Allah wadai da kokarin da Amurka ke yi na katsaladan a harkokin samar da makamashi na kasashen Turai ta hanyar saka takunkumi kan aikin Nord Stream2, wanda har wasu sun yi kira ga Brussels da soma tunanin matakan ramuwar gayya.
Mascow ma ta yiwa Washington kaca-kaca tana mai kiran wannan mataki da cewa karfa-karfe ne.
A farkon makon nan ne dai, Dmitry Presko wani mai magana da yawun shugaban kasa ke cewa Russia za ta fito da wani sabonn tsari na yadda za ta kammala aikin idan har Washington ta ci gaba da wannnan mataki mai azabtarwa.
Sebastian Vettel ga Red Bull: Fitaccen dan gasar tseren motoci na Fomula 1 a koma wajen Max Verstappen saboda rashin wani mutum daya
"Ina mai tabbatar da cewa da haka ba ne, Kuma Sebastian ya na sane da hakan."
Za a dawo gasar tseren motoci na F1 a karshen mako mai zuwa, tare da gasar tsere na kan-kan-kan da za a yi a Silverstone.
Lewis Hamilton na fatan tagomashi a gasar tserensa bayan ya cinye biyu daga gasannan tseren uku na babban gasar tun lokacin da aka dawo da kakar gasar a tsakiyar annobar cutar Koronabirus.
Vettel na fatan ganin samun cigaba a ayyukan da ya ke yi daga Ferrarinsa wacce aka daina yayinta.
Octavia Spencer ta yi kira ga 'yan Hollywood da su kara mutanen da ke da nakasa a finafinai
Wannan na daga cikin sabon shirinta na jan hankali PSA da ke kira da a kara yawan wadanda ke da nakasa a harkar nishadantarwa.
Wannan gangami da ta soma ya zo daidai da bikin murnar cika shekara 30 ta Lahadi da samar da dokar Amurkawa nakasassu (ADA).
Bidiyon da ta yi ya nuna Spencer ta na tattauna muhimmancin na kowa ya ga kansa da kuma rayuwarsa an nuna ta yadda ya kamata a fina finai da talbijin.
"Babu wani abin da zai maye gurbin rayuwa ta hakika da kuma wakilci na gaskiya" ta na mai cewa.
"Don haka yake da matukar muhimmanci mu sa jarumin da ya dace a gurbin fim din da ya dace."
Spencer ta yi magana akan tasirin da ta ke ji na kallon da banbancin launi a a akwatunan talbijin a lokacin da ta ke yarinya ta ke kallon shirin "Good Times."
Shririn na talbijin mai dogon zango wanda CBS ta rika sa wa daga shekarar 1974 zuwa 1979, Norman Lear ne ya kirkire shi kuma hakan ya duk wasu shinge a matsayin shirin da talbijin na farko da ya nuna 'yan Amurka masu asalin Africa na iyaye biyu a wasan barkwanci.
Shugaban likitocin kasar Ukraine dan shekara 48 ya mutu daga cutar Koronabirus
Anaton Hudae, likitan kungiyar kwallon kafa ta kasar Ukraine ya mutu sakamakon kamuwa da ya yi daga cutarkoronabirus yana dan shekara 48, a cewar wata sanarwa da kungiyar kwallon kafa cikin a ta kasar (UAF)ta fitar.
"A madadin shugaban kungiyar kwallon kafa ta Ukraine Andriy Pavelka, da babban mai hoaras da 'yan wasan kungiyar kwallaon kafa ta kasar Andriya Shevenko da kuma daukacin 'yan wasan kwallon kafar kasar, muna masu mika ta'aziyya ga iyalinsa",  a sanarwar da kungiyar AUF da ta fitar ke cewa.
"daukacin kungiyar kwallon kafar kasar na cikin matukar juyayi"
Hudaev kuma yana daya daga cikin likitocin wata karamar kungiyar kwallon kafa meatalis Khakiv.
Kwayar cutar ta hallaka sama da mutane 1.600 a Ukraine wacce ta sanar da cewa mutane kuasan 65,000 sun kamu da ita.
An gina gada ta farko a aikin jirgi mai tafiya a kasrkashin kasa na Delhi a kashin aikin na 4
Aikin gina jirgi mai tafiya a karkashin kasa na birni Delhi ya cimma wani mataki mai muhimmanci yayin da ya shiga wani kashi a aikin-4 yayin da a ka gina gada ta farko a kan mashigar yamma na Janakpurita R K Ashram Marg, A cewar wasu jami'ai a ranar Lahadi.
An yi aikln gadar ne a Keshopur a kan wani tudu da ke tsaknin Keshpur da Mukaba Chowks a daren Asabar.
"Hukumar kula Jirgin karkashin kasa ta birnin Delhi ta sake samun kai wa ga wani babban mataki na 4 aikin da ta ke yi na fadada layin dogo na karkashin kasa da samun nasarar ginin karfe na wata gada a wata mashiga hanyar jirgin karakashin kasa ta yamma a Janakpuri RK Astta Marg," a cewar wata sanarawa da Hukumar DMRC ta fitar.
Wannan "babban nasara da aka samu a wannan aikin ginin layin dogo" an same ta ne duk da karancin ma'aikata da kuma wasu matsalolin jigila da kai-kawo saboda annobar cuta da ake fama da ita, a cewar wani jami'i.
Matsakaicin tsayin wannan gada ta wannan mashiga shine mita 10.
Sai daia sauran gadojin zasu zama masu tsawon mita 20 a Madhun Chowk (wurin tsallakawa n a 1)da kuma mita 25 a Haderpur Badli Mor a inda wannan layin dogo zai tsallaka wani layin dogon na 2.
A Haider, pur Mor, gadar da za ta dauki layin dogon da zai wuce ta wurin zai kasance mita 28, wanna shine mafi girma a tarihin layin dogo na birni Delhi, a cewar sanarwar.
A yanzu dai wuri ma fi tsawo shine wanda ya ke Dhaula Kuan, a inda layin dogo na 7 da ke kan gada ya wuce har tsawon mita 23.6.
A tsarin kimiyyar gine-gine ana yin ginshikin gine-gine ne a tsatstsaye domin su tallafin nauyin ginin da ke zama kamar gada a kan ginshikan biyu na gefe da gefe.
Wadannan su suka zama kamar ginshikan da suka tallafi tudun da aka dora layin dogon mai wucewa a kai.
Gadojin da a ka dora layin dogo na jirgin karkashi kasa da dora su a tsakiyar hanyoyin mota a birnin Delhi ta kan su ne aka giggina mashigar jiragen karkshin kasa.
Yawanci wadannan gadojin sun sa sun zama fittatun kuma ababen kwantace a wajen bayar da adireshi a birnin Delhi.
Mashigar layin dogo ta Janakpurin yamma - RK Ahsram ita ce ma fi tsawo da tsawon kilomita 28.92, ita ce karin layin dogo na MAgenta za ta kuma dauki tashohi 22.
Yayin da kilolmita 21.18 na wannan mashigar za a daga shi, yayin da 7.74 kilomita na wannan layi zai kasance a karkashin kasa.
An soma aikin ginin wannan sashi a watan Disambar shekarar da ta wuce.
A ranar 17 ga watan Yuli, a ka soma aikin ginin sashen karkashin kasa na mashigar wanda aka fara da gina bangon D a tashar jirgin karkashin kasa na wurin shakatawar Krishna.
A ranar 24 ga watan Yuli, Hukumar ta DMRC ta soma kakkafa karafunan zuba kankaren durakai da kuma ginshikai don daga layin dogon wannan bangare na mashigar layin dogon.
A karkashin wanna rukunin aiki na 4, kilomita 61. 679 na sabbin layukan dogo za a giggina a kan mashigai daban-daban guda uku da za su kunsh tasoshi 45 na jirgin kakshin kasa.
Wannan sabon sashi zai samar da wata babbar mahada a tsakanin shiyoyin daban-daban na jiragen karkashin kasa na birnin na Delhi.
A cikin wannan adadi, Kilomita 22.35 duk za su kasance a karkashin kasa ne yayin da sauran za su kasance a kan gadoji.
Masu zanga-zangar wariyar launin fata sun yi arangama da 'yan sanda a Seattle
An yi arangama da tsakanin 'yan sanda da masu zanga-zangar nuna wariyar launin fata wanda ya haifar da kame mutane da yawa a ranar Lahadi, yayin da fushin al'umma ya ke karuwa akan a shirin Donald Trump na "kara" yawan jami'an tsaro na tarayya a manyan birane.
Jerin zanga-zanga kan banbancin launin fata da kuma zaluncin 'yan sanda ya samo asali ne daga kisan George Floyd wani bakar fata ba Amurke dan asalin Africa a Minneapolis wanda ba ya dauke da makami a watan Mayu.
Masu zanga-zangan a Seattle sun yanka tayoyin motoci da kuma farfasa tagoginsu a yayin zanga-zangar a ranar Asabar, wanda hakan ya sa 'yan sanda su kaddamar da yaki da tarzoma su kuma tarwatsa su ta yadda za su bude tituna tare da yin feshin barkonon tsohuwa da kuma tayar da kananan abubuwan fashewa.
Masu zanga - zanga sun cinnawa wasu kananan motoci na wasu kamfanonin gine-gine da ke ginin swara cibiya ta tsare matasa.
'Yan sanda sun ce mutane 45 aka kama yayin da jami'an 'yan sanda 21 aka ji wa ciwo.
Zanga-zangar na goyon bayan irin wannan zanga-zanga ne Portland da ke kusa, Oregon.
Portland ta zama cibiyar gumurzu da Jami'an tsaro na gwmantin tarayya wanda a bisa umarnin Trump da suka janyo cece-ku-ce, daya daga cikin wanda ba shi da goyon bayan jami'ai na garin da suka ce an fi amfani da karfi da ya wuce kima.
Masu zanga-zangar sun yi fito kan tituna a Austin ta Texas da kuma Louisville ta Kentucky; da New York; da Omaha ta Nebraska; da Oakland ta California da Los Angeles, da kuma Richmond da ke Virginia.
A Austin, an kashe wani mutum a wani harbe-harbe da ya barke a daren Asabar wata zanga-zanga da aka yi a tsakiyar babban birnin Texas a cewar 'yan sanda.
Wadannan zanga-zanga na zuwa ne bayan da Trump ya ke fuskantar wani kalubale mai wuya na neman a sake zabarsa a watan Nuwamba, kuma a yayin da yake yakin neman saka zaben nasa a kan "tabbatar da doka da oda."
Israilawa suna cigaba da zanga-zanga kan yadda Firayi ministan kasar ke tukarar wannan annoba
Birnin JERUSALEM (AP) - Dubban yahudawa ne suka gudanar da wasu jerin zanga-zanga a fadin kasar kan Firayi Ministan kasar a ranar Asabar, yayin da babbar zanga-zanga aka yi ta a birnin Jerusalem a kofar gidan Benjamin Netanyahu.
An yi ta gudanar da zanga-zangar har na tsawon makonni, a kan abin da masu suka ke gani a matsayin gazawar gwamnati na yadda ta ke tafi da halin da aka shiga mai tashin hankali dangane da cutar Koronabirus bayan da a farko ta na mai kore barazanar a cutar a kasar.
Tuhumar da ake yiwa Netanyahu na cin hanci ya dada izza wutar zanga-zangar.
"Bini ka tafi gida", a wani rubutu da wani mai zanga-zanga ya ke rike da shi.
Wani kwalli ma an rubuta "kowa dai yana ganin cewa sarki a tube ya ke ya zub da kayansa na sawa"
Daruruwan masu zanga-zanga ne a ranar Asabar suka taru a kofar gidan Netanyahu da ke bakin wara gaba a wata unguwar masu hannu da shuni da ke garin Caesarea.
A makon da ya wuce, 'yan sanda sun yi amfani da ruwa mai karfi daga bututu don a tarwatse taron jama'a a Jerusalem.
Bayan wani abin da aka kira shawara ta gaggawa mai cike da kurkurai na bude tattalin arziki a watan Mayu, yawan wadanda suka kamu da cutar ya karu da kiyasin sabon wani ya kamu a kowacce rana a 2,000.
Tattalin arzikin kasar ya yi raga-raga sakamakon bayyanar cutar da kokarin dakileta ga kuma yawan marasa aikin yi da ke tashin gwaron zabi zuwa kusan 20%.
Masu zanga-zanga suna cewa tallafin da gwamnati ta ke bayarwa ba sa kaiwa ko ina ballatana su kai ga isa.
Zanga-zangar na zuwa ne bayan da ake zargin Netanyahu da laifin cin hanci wanda za a cigaba a wannan watan.
Za a ci gaba da sauraron shari'ar a watan Janairu.
Ana tuhumarsa da zamba da cin amana da kuma karbar cin hanci a cikin wasu jerin abin kunyar da ya aikata.
Mata nakasassu, marasa matsuguni na cikin rundunar Chennai masu yaki da cutar COVID 19
Shantri a wani mai sana'ara dinki mai fama da nakasa, ta kan ziyarci gidaje 250 a kowanne rana don ya gano mutanen da ke dauke da alamomin cuta a tsakanin mutane da ke zaune Kodambakkam, wata unguwa da cutar Korana ta yi kamari a Chennai da ke dauke da wadanda suka kamua da cutar su kimanin 10,000.
A kowacce rana ta kan soma fita ne da sasafe da kimanin karfe 7:30 ta kuma gama zagayenta da misalin karfe 4:00 na yamma.
Ta kan bincika zafin jikin mazuna unguwar, ta kan yi musu tambayoyi dangane da alamomin cutar da yaduwarta da kuma wayar da kai akan muhimmancin sa takunkumi, da yawan wanke hannu, da nisanta juna.
Irin ayyukan da ta ke yi ya taimaka wajen ganewa da wuri da kuma warkewar mutane hudu da suka kamu da cutar.
Shanthi na daga cikin ma'aikata 16,000 ma'akatan kamfanin birnin Chennai wadanda ba mai'aikatan lafiya ba da ke bi gida-gida suna yin gwaji.
Wannan yunkuri, a cewar mahunkuta ya kai ga samun raguwa yaduwar cutar da kashi 50 a alkaluman wadand suka kamu da cutar a kullum a yayin da alkaluman suke tashi a wasu yakunan na Tamil Nadu.
Shanthi ta ce ba duk mazauna wuraren ne ke ba ta hadin kai ba.
Sannan ta kuma kara da cewa, "Yawancin mutane na bayar da hadin kai idan sun ga mata nakasassu ne ke ba su agaji.
Wasu kuma abi na ba su haushi.
Bazan damu ba.
Ni dai burina shine mutane su kasance ba sa cikin hadarin kamuwa da cutar.
Idan na ske ziyartarsu washegari sai su zama su na mutuntani.
Samun kyakkyawar fahimta na taimakawa."
Da akwai wasu da yawa irin Shanthi wadanda suke zauna a inda kamafanin ya tanada na marasa matsuguni na mata nakasa suke taikamakawa a yakin da ake da curtar COVID -19.
Dan nesa kadan daga Kodambakkam, Kavita wacce ita ke fana da wata nakasa ta shiga bayar da ta nata gudunmawar a matsayin mai sa ido.
Duk da cewa tana amfani ne da keken guragun na musamman, Kavitha tana tafiya ne tare da taimakon wasu sanduna biyu wanda da haka ta ke ganawa da mutane.
"Ina cikin farin ciki," ta kuma yi magana kan raguwar yawan adadin da ake samu, amma saia ta kara da cewa "Ina so wannan adadadin ya sauko kasa sosai zuwa kamar 100 a rana.
Kuma ina da karfin gwiwar cewa za mu iya kaiwa ga hakan."
A kasan bene inda aka yiwa marasa matsuguni, inda su biyu suke zaune, MatildaFunceca wata 'yar wasan kwallon kwando da ke amfani da keken guragu, da kuma Manimekalai, wata malamar makaranta, suna aikawa da bayanan da kimanin mata 40 suka aiko musu zuwa ma'adanar bayanai na kamfanin.
Matilda ta ce ita ba ta tsoron kamuwa da cutar Koronabirus.
"Cikin taimakon wasu, Allah zai karemu" ta cigaba da cewa.
Da aka tambayerte game da irin matakan kariyar da suke dauka, Manimekalai ta yi bayanin cewa:"Ina sa takunkumi sannan ina bayar da tazara ina kuma wanke hannunna akai-akai.
Sannan ina kuma shan Kabasura Kudineer, wani abin sha mai inganta sinadarin kariya na Siddha."
A 'yan watannin da suka wuce a lokacin da cutar Korona ta bulla a Chennai wadannan mata maus nakas sun yi amafani da lokacinsu da basirarsu wajen dinka takunkumi da hannu ga mai'aikatan tsabta a garin.
Dabkta Aiswanya Rao darakataa mai kula da cibiyar Bincike da samar na Dorcas mai da matsugunin ya ce. "su kan bayar da taimakon ne daidai da irin bukatara da ake da ita.
A da, ana bukatar takunkumi sai suka yi kokarin samar da shi.
Yanzu kuma ana bukatar tamakawa al'umma nan ma ba su gajiya ba."
A dadin wadanda suka kamu da cutar ta Koronabirus a Tamila Nadu ya haura gejin dubu biyu da karin  6,989 na sabbin alakluman sabbin wadanda suka kamu da cutar a cikin awanni 24 wanda kuma shi ne karuwa ma fi girma a ranar daya, kamar yadda alkaluman gwamnati suka nuna.
Mutane tamanin da tara suna mutu, yayin da 7,758 suka warke daga cutar a ciin awa 24 da suka wuce.
Yawan adadin wadanda suka kamu da cutar a jihar yanzu ya kai 2,06,737.
Mick Fleetwood ya yi ta'aziya ga Peter Green: 'wakokinsa za su cigaba da wanzuwa'
Mick Fleetwood ya mika ta'azziyarsa ga Peter Green, daya daga cikin wanda suka kirkiro Fleetwood Mac, wanda ya mutu ya na dan Shekara 73.
Green na daya daga cikin kungiyar makada na tarihi na asali, tare da wanda muka anbata a baya Mick, da kuma Jeremy Spencer.
Duk da cewa ya bar kungiyar makadan a shekarar 1970 kafin babbar nasarara da suka samu da faifan album dinsu kamar Rumours, Mick ya jajantawa tsohon abokin kidansa, yana mi tabbatarwa da masoyansa cewa "wake-waken da ya yi za su wanzu"
Fleetwood ya fadawa PA cewa: A gareni, kowanne dan kungiya na da, dana yanzu na Fleetwood Mac, rashin Peter kasurgumi ne.
"Peter shine mutumin da ya soma kungiyar Fleetwood Mac tare da ni kaina, da John McVie da kuma Jeremy Spencer.
Babu wanda ya taba shiga rigar Fleeetwood Mac ba tare da ya yabawa Peter Green da kuma baiwar da Allah Ya yi masa, da kuma gaskiyar cewa kida da waka ya zama mai haskakawa da kuma a koda yaushe ya ana yinsa da kauna ta gaskiya."
Dan shekara 73 mawaki tsoho mai ran karfe ya kara da Peter zan yi kawar ki, amma ka kwanta lafiya, wakarka zata cigaba da wanzuwa.
Na yi godiya matuka da ka ba ni damar zama mai kidanka a duk tsawon shekaru nan da suka wuce.
Mun yi mai kyau. Da kuma bude hanya a tafarkin waka da wasu da yawa za su hau su kuma ji dadi.
"Allah ya kiyaye hanya, babban abokina....  Ina mai kaunarka Mick Fleetwood."
Tabbatar da mutuwar Green, a wata sanarwa daga ofishin lauyoyi na Swan Turton na mai cewa: "Cikin matukar alhini iyalan Peter Green ke sanar da Rasuwarsa cikin wannan karshen makon, a cikin salama a yayin kwaciyar barcinsa.
"Wata karin sanarwar za ta biyo baya nan da'yan kwanaki"
Green ya mutu ya bar 'yarsa mai suna Rosebud Samuels -Greenbaum wacce kuma 'ya ce ga tsohuwar matarasa Jane Samuels.
Green ya kafa kamfann Fleetwood Mac tare da abokan kidansa Mick Fleetwood da Jeremy Spencer, da kuma sunan kungiyar na asali Peter Green Fletwood Mac tare da Jeremy Spencer.
Sai dai kuma, mawaki mai kuma rubutawa zi bar kungiyar a shekarara 1970 bayan sun wallafa kundin wakoki har guda hudu.
Fleetwood Mac za ta je ta cimma tashe da farin jini na duniya tare da karin wadanda suka shigo ciki da suka hada da Lindsey Buckingham da Stevie Nicks tsarin wakokin wanda ciki har da Rumours da kuma Tusk.
An dai karya kashin bayan duk wata hadaka.  Cutar koronabirus kuma na iya tabarbare al'amarin.
"Bullar wannan annobar kadai ita ma manuniya ce da kuma kira ga zababbu shugabanninmu na irin shugabanci da hangen nesan da yakamacemu a lokacin rikici irin wannan", a cewar wani rahoto wanda da aka samar bayan hirarraki da Leonard Steinhorn, wani Farfesa na kimiyya sadarwa da ke Jami'ar Amurka, shi da Mark Sobol marubuci kuma kwararre kan sanin tsari da shugabanci suka gudanar.
"Amma kuma muna fuskantar wani babbaba tabo na zunubin asali kuma na cikin gida na kasar nan dangane da rash
Bincien ya gangara a hankali cikin a abubun da aka saba da su a wajen nazarin halin takaici na halin majalisa ta ke ciki: Zaman'yan marina da ake yi da juna wanda ya dakushe duk wata dama ta mu'amilla ta hakika, karfin iko bakii dayansa na hannun shugabanni, bukatar a tara musu kudi a kai-a kai, rashin karfafa gwiwar hadaka na jami'iyyun da suka banbanta a manufinsu da akida, da mummunan tasirin kakafen yada labarai maus aikijn ba dae, ba rana, da kuma hakikaninn cewababbab abin da ke gaban yawancin 'yan majalisa shi ne cin zabe, da kuma dankwafe 'yan jami'iyyarsu masu ra'ayin da suka sha ban-ban da nasu.
Ya kuma yi gargadin cewa mayar da harkokin majalisa zuwa yanar gizo a sakamakon wannan annobar, kamar samar da wani tsarin yin zabe a majalisa ta hanyar wakilci da zai ba 'yan majalisar damar kada kuri'arsu ba sai sun je birnin Washinton ba, zai iya dada lalata lamarin da ake ciki.
Idan har shawarar gudanar da zaman majalisa da hanyar yanara gizo ya samu amincewa, a cewra rahoton, hakan ba karamin ci baya zai kawowa yunkurin da ake yi na samun hadaka da kokarin hada hannun a tsakanin jam'iyyu masu banbancin akida ba.
"Bullar wannan annoba, ya tilasatawa majalisa gudanar da yawancin harkokinta ta hayar yanar gizo, kuma mun ka fahimci daliln da sa a yi hakan," a cewar rahoton.
"Amma duk da cewa yin hakan ya zama dole babu yadda za a y, kar a fassara hakan da cewa yin hakan nagarta ne."
Bayanin rahoton ya ci gaba da cewa Majalisa na bukatar "sababai na 'yan majalisa su hadu da juna da kuma yin mu'amilla ba akasin haka ba.
"Da akwai bukatar su mazabun junansu, su tattauna ta fahimtar juna da zai samar da wata dama ta dinke duk wata barakar da ke tsakaninsu da samun amintar juna da ka iya kai wa ga samar da maganin matsalolin da suka damu a'umma"
A makon da Dan Majalisar Wakilai Ted Yoho da jam'iyyar Republican daga Florida haka kawai ya zazzagi dan majalisar wakilai Alexandria Ocasio-Cortez dan jam'iyyar Democrat daga New York da kuma lokacin da aka 'yan Republicans suka yiwa dan uwansu Dan Majalisar Liz Cheney daga Wyoming, taron dangi na yi masa kaca-kaca, hakan ya dada fito da bukatar kara samun wayewa da mutunta juna.
Wata Kotu a Gurugram ta yi sammacin Kamafanin Alibaba, da Jack Ma a bisa wata kara da wani tsohon ma'aikaci ya yi
Gurugram ranar 26 ga watan Yuli. A wani cigaban kuma, Kamfanin Alibaba da kuma wanda ya kirkiri kamfanin wata kotu a gurugram ta yi sammacinsu bayan da wani tsohon ma'aakacin kamfanin ya yi zargin cewa an kore shi daga aiki saboda ya bijirewa tantacewa da kuma labarin karya na manhajar kamfanin.
An shigar da karar ne a wata Kotu da ke lardin Guragram wacce wani alkali Sonia Sheokand ta bayar aika da takardar sammaci ga Kamafanin Alibaba da kuma Jack Ma da kuma karin wasu su kusan goma sha biyu tare da umartarsu da su bayyana a gabanta aranara 29 ga watan Yuli a cewar rahotanni.
Alkalin ya kuma bukaci amsar tuhumar a rubuce daga kamafanin, a cewar wani rahotoi na kamafani labarai na Reuters.
Parmar wanda a da, yake aiki a ofishin UC Web a Gurugram kafin sallamarsa a watan Oktobar shekarar 2017 ya na neman a biya shi diyyar $268,000 a matsayin diyya, in ji takardun shigar da kara na Kotun.
"Ba za mu yi kasa a gwiwa ba wajan sadaukar da kai ga kasuwar Indiya da kuma jin daɗin ma'aikatanta na gida, kuma manufofinta suna bin dokokin ƙasa.
Ba mu da ikon yin tsokaci kan karar da aka shigar, " UC India ta bayyana a cikin wata sanarwa.
"Shari'ar ta kuma ƙunshi" jerin wasu kalmomin masu iya haifar da rudani "tare da wasu kalmomi irinsu a cikin yaren Hindi da Ingilishi kamar" iyakar Indiya da China "da" Yaƙin Sino-Indiya "wadanda kotun da ke suararon karar ta yi zargin cewa UC Web ne ya yi amfani da su don tantance abubuwan da ke cikin dandamalinta a Indiya, "Reuters ta ruwaito.
A watan da ya gabata, ma’aikatar cikin gida ta dakatar da manhajojin wayar hannu 59 na kasar Sin da suka hada da UC News, UC Browser a cikin rikicin kan iyaka a tsakanin kasashen biyu.
Hambararren shugaban CAR Francois Bozize ya sanar da aniyarsa ta sake tsayawa takarar shugaban kasa
Hambararren shugaban kasar Jamhuriyar Africa ta tsakiya Francois Bozize a ranar Asabar ya sanar da aniyarsa ta sake tsayawa takara a zaben shugaban kasar da za a gudanar a watan Disamba duk da cewa Majalisar Dinkin Duniya ta sa masa takunumi kuma za a iya kama shi don fuskantar hukunci a bisa zargin da a ke yi masa na aikata laifukan yaki.
Ya bayar da wannan sanarwar ce a wani jawabi da ya yi a gaban dubban jama'a magoya bayansa a taron jam'iyyarsa Kwa na Kwa (aiki sai mai shi) a babban birnin Bangui.
Dan shekara 73 da haihuwa Bozize tsohon janar din soja ne kuma shugaban rundunar sojojin kasar da wasu gamayyar kungiyoyin tawayen 2013 wanda yancinsu musulmai ne daga arewacin kasar suka yiwa juyin mulki wanda hakan ya jefa kasar da yawancinta Kristoci ne cikin wani kazamin yaki da kuma matsalar 'yan gudun hijira mai tsanani wanda har yanzu bai yanke ba.
"wannan kasa na bukatar mutum mai gogewa da son zaman lafiya da kuma ka'ida." Bozize ya na mai fadi a wani jawabi da yayi wanda ya kuma yi kakkausar suka ga shugabancin Faustin-Archange Touadera wanda ke kan kujera.
Bozizie ya jagoranci kasar ne bayan wani juyin mulki da ya yi a shekarar 2003 ya kuma shugabanci kasar har na tsawon 10 kafin ya tsere ya bar kasar a shekarar 2013.
Sanbuwar gwamnatin Kasar ta nemi a kama shi ne a bisa zarginsa da aikata laifukan yaki da kuma tunzura jama'a da hakan ya kai ga aikata kisan kiyashi, amma kuma ba a kama shi ba tun da ya dawo kasar daga gudun hijira a karshen shekarar da ta wuce.
Ba dai san yadda takardar izinin kama shi ba, da kuma takunkumin da kasashen waje suka sa masa zai iya shafar takarar ta sa.
A wataan Janairu, Bozize ya ce zai bukaci ta dage takunkumin da sa mi shi a bisa zargin da ake yi mi shi na goyon bayan kungiyar Kiristoci masu dauke da maka ta Anti - Balaka a shekarar 2014.
A yanzu Touadera ne ke mulkida taimakon wata babbar runduna rwanzar da zaman lafiya ta Majalisar Dinkin Duniy da ke da dakaru 13,000 na 'yan sanda da Soji.
An zabe shi a sheklarar 2016, a na kuma sa ran zai sake tsayawa takara na wa'adi na biyu a zaben da ake shirin yi ko da yake ba a tabbatar da hakan ba tukunna.
An shirya soma zagayen farko na yakin neman zaben a ranar 27 Disamba.
A cikin watan Fabarairu 2019 Gwamnatin kasar ta sanya hannun wata yarjejeniyar zaman lafiya da wasu kungiyoyi 14 masu dauke da makamai da suke ikirarin kare muradin wasu al'umma ko wani addini.
Tuni dai tashe-tashe hankali ya lafa, sai da akan samu daidaiku mummunan tashin hankli nn da can mai kamar kullum nasaba da fada kan mallakar arzikin kasa yayin da yawancin arzikin lu'lun da ke kasar na yankunan da ba sa karkashin ikon gwamnati.
Wannan tashin hankali ya tilastwa mutane sama da milyan 1.5 tserewa daga gidajensu.
Gottlieb ya yi gargadin cewa "zai yi matukar wahala a bude" makarantu da kaka a wuraren da aka kasa dakile yaduwar cutar Koronabirus
Birnin Washington - Dakta Scott Gottlied, tsohon shuguban Hukumar kula da ingancin abinci da magunguna, ya yi gargadin cewa, abubuwa za su yi "tsananin matuka" ga makarantu a gundumomi su bude don soma katatu a shekarar karatu mai zuwa na shekara mai zuwa idan har da akwai rashin dakile yaduwar cutar Korona Birus a wuraren.
Ga makarantun da ke unguwanni da ke gundumomi, Ina ganin suna da bukatar da su rinka kallon dalilan da ke sa cutar ta yadu a wurare.
Idan aka samu matsalar yaduwar cutar a unguwanni ba a iya da dakile ta ba, zaj zo da matular wahala a bude a cikin irirn wannan yanayi." Gottlieb ya ce a "shirin Face the Nation."
Da kusantowar zangona kaarutun na kaka a 'yan makonni, gwamnatin Trump ta na ta kira ga makarantu a gundumomi da su bude azuzuwansu domin dalibai su soma daukar karatu a tsarin gani - gaka a kwnaki biyar na kowanne mako.
Amma wannan matsin lamba daga Shugaba Trump da kuma Sakataren Ilimi Betsy DeVos na zuwa ne a lokacin da Mista Trump ya yi gargadi a makon da ya wuce yana mai cewa cutar Koronabirus na iya " ta'azzara kafin ta yi sauki " sannan suka yarda da cewa makarantun da ke gundumomi a wuraren da ke zafi su jinkirta budewa da 'yan makonni.
Duk da haka, Cibiyar kula da yaduwar cuttuka da dakile su, ta fitar da wata sanarwa a ranar Alhamis kan yadda za a bude makarantu domin dalibai su dawo ba tare da yiwuwar kamuwa da cutar ba.
Sanarwar jagorar na kira ga makarantu da su bi ka'idar bayar da tazara, na kira ga dalibai da kuma malamai su sa takunkumi su kuma sa dalibai a da'irori domina rage cudanya da juna, kadan daga cikin sauran jagororin.
Sai dai hukumar ta CDC ba ta bayar da wani ma'auni na yadda shubannin makarantu za su iya daga karatunsu ko kuma rufe makarantun baki daya idan an samu labarin wani ya kamu da cutar ta Korona, wacce Gottlied ke cewa, " abin takaici ne."
"Cikin halin yanayi na kila-wa-kala da kuma rashin fadin takarmaimai yadda za a ci gaba da barin makarantun a bude, ina jin dai iyaye da yawa za su yi kuskure a wajen daukar matakan kariya" yana mai cewa.
" Shi ya sa ya ke da matukar muhimmanci a samu takamaiman bayani kan ma'auni mai wuya da hukumar ta CDC ta hankalinta bai kai wurin ba."
Gottlied ya ce kamata ya yi makarantun da ke gundumomi su rika tunani kan afkuwar lamarin a wuraren da suke da kuma yadda za a yi gwajin cutar ta yadda za a iya tsai da shawarar uadda za a tunkari lamarin da kuma kom za ci gaba da barin makaranta a bude ko kuma a koma baki daya zuwa karatun ta hnayara yanar gizo.
Yiwuwar kamuwa da cutar tsakanin 5% zuwa 10% ya na mai cewa, "hankula zai soma tashi" yayin da sama da kashi 10% ya zama "matakin da sai ka yi taka tsan-tsan tere da tunanin ko yakamata ka rufe makaranta a yankin baki dayansa."
" Wannan shine alamar cewa lallai annobar ta doso wannan wuri gadan - gadan" Gottlieb yana mai cewa, zai abu ne mai wahala ga wasu yankuna na jihar Florida wacce ta kasance cibiyar annobar Koronabirus a Amurka, da zai sa su bude maukarantunsu a koma karatu kamar yadda a ka saba gani-gaka.
Sama da jihohi 30 ne da kuma gundumar Columbia ne ke fuskantar karuwar wadanda suka kamu da cutar ta Korona, yayin da Sun Belt ya zama cibiyar yaduwarta.
Amma Gottlieb ya ce da akwai abubuwan da suke nuna cewa a wasu jihohi ciki har da Arizona da kuma Texas za su kai kololuwa.
Duk da dai Gottlieb ya ce akwai "alamun da ba za a iya ganewa ba" annobar tana tafiyar hawainiya a wasu jihohin a fadin Sun Belt, tana "ɗumama" a wasu, ciki har da South Carolina, da Alabama, da Indiana da kuma Illinois.
Gwamnoni da yawa sun kafa doka da ke buƙatar mutane su sanya takunkumi lokacin da suke cikin jama'a kuma sun dakatar da sake buɗe wuraren taron jama'a, a cikin yunƙurin rage yaɗuwar ƙwayar cutar ta Koronabirus.
Gottlieb ya ce ya kamata jihohi su yi duba yiwuwar rufe mashaya, da iyakance yawan mutane a gidajen abinci, da rufe gidajen sinima da ma sauran wuraren nishadi na cikin rufaffunn wurare, da aiwatar da dokar rufe fuska don dakile yaduwar annobar, matakan da za su ba jihohi damar dakatar da koma baya ga mafi tsauraran da hani aka sanya a farkon bullar cutar a watan Maris.
Baya ga jihohin da ke bayar da umarnin rufe fuska, yawancin kamfanoni na buƙatar kwastomomi da suma su sanya abubuwan rufe fuska.
McDonald's na daga cikin waɗanda suka buƙaci rufe fuska, da kuma babban wurin sayar da abinci Walmart, Starbucks da sauransu wajen aiwatar da ƙa'idojin kansu na takunkumi.
Gottlieb ya ce yana fatan ganin karin wuraren kasuwanci za su aiwatar da umarnin rufe fuska a wurarensu, musamman ma wadanda ake ganin suna da matukar hadari.
"Idan da gaske ne za mu iya magance cigaba da yaduwar cutar har zuwa lokacin hunturu har sai mun kai ga samun allurar rigakafi ko wani nau'in magani wanda ke canza yanayin tafiyar wannan rashin lafiyar, a likitance, kawai tare da abin rufe fuska wanda zai zama wani abu mai sauƙi wanda za mu iya yin hakan ba zai canza rayuwarmu da gaske ba, kuma yana ba mu damar kiyaye abin da ke da muhimmanci a gare mu kamar buɗe wasu kasuwancin a buɗe, kamar dawo da yaranmu zuwa makaranta, "in ji shi.
Yayin da Mista Trump ya ce ba zai sanya dokar rufe fuska ba a duk fadin kasar, ya bukaci Amurkawa a makon da ya gabata da su sanya makari, yana mai cewa yayin ganawa da manema labarai na Fadar White House "suna da tasiri."
"Ba na son in zama kamar McGregor in rika nuna cewa ina da kudi
Na zo nan ne don in taimaki mutane'- a cewar Chimaev bayan ya kafa tarihi gasar dambe  na UFC da a ka yi a fight Island
Ana jinijinawa Khamzat Chimaev a matsayin tauraron gasar damben UFC na gaba bayan da ya kafa tarihi a tsibirin Fight Island sai dai dan daben kuma dan asalin kasar Rashaya ce ba shi da wani shiri na nuna kasaita da baza dukiya irin su Conor McGrgor
Chimaev ya na ragargaji dan asalin Ireland ta kudu Rhys Mckee a karwar da suka yi don cin kambin ajin matsakaita a Abu Dhabi a daren Asabar, a inda ya kaia abokin karawarsa kasa tare da yi masa rubdugiu da naushi mintuna 3 da dakika 5 a zagayen farko na karawarsu
Wannan nasara ce ta shigar da sunan Chimaev a cikin kundin tarihin wasana damben UFC ba wanda ya taba yin nasara a cikin lokaci kankani na karawa damben a wannan zamani na yayata abubuwa, wanda ke zuwa kwanki 10 kacal bayan da ya cinye John Phillips wani dan Britamiya ta irin wannan ragargazar - a kuma a irin wannan aji na matsakaita.
Zakaran dambe Chimaev wanda ya soke $50,000 a aljihunsa a matsayin kari na bajintar da ya yi a dambensu da McKee wanda hakan kuma ya sa hankalin kungiyar dambe ta MMA ta Duniya ta koma kansa, yana nuni da cewa shine zai zama  mgajin 'Khabib 2.0 - wartakla wani kwatankwaci na dole ganin yadda Chimaev ya nuna irin wannan mamaya na gasar kambin UFC ajin marasa nauyi. An haife shi a Chechnya mai makwabtaka da Dagestani garin da Khabib ya fito.
Duk da wannan sabuwar daukaka da tarin dukiya, mai tattusar magana Chimaev ya ce ba zai yi facaka da nuna isa da dukiyar da ya samu ba irin yadda  gwarzon MMA mai takama da kudi Connor Mcgregor ko kuma dan wasan damben boxing  Floyd Mayweather Jr. suka yi ba
"Na yi hakan ba don kaina kawai ba, na yi hakan ne domin kowa da kowa da zan iya taimakawa."
Ni ba na son in zama irin su Mayweather da McGregor ba, in rika dagawa da facaka da kudi da sauransu.
I na so in taimakawa mutane, in ji Chimaev a lokacin da aka tambaye shi a tsibirin na Fight Island kan yadda zai kashe kyautar kudin davya samu.
Wani mutum da ya ja hankalinsa shi ne abokin damben Conor Mc Gregor kuma dan gani-kashe-nin dandanlin sada zumunta naTuwita, Dllon Danis, wanda ya hau dandalin yana mai ikirarin cewa zai iya dankwafar da Chimaev cikn sauki
Hakan gayyato kakkausar martani daga dan damben da ake yiwa lakabi da "Borz' ko kuma "kerkeci" a yarensa na Chechen - wanda ya ce sai "na hada masa jini da maijina ido rufe"
Chimaev wanda yanzu yake sana'ar dambensa a wajen Stockholm ta kasar Sweden, ya bar kasar ne yana dan shekara 19, zai yi kankan da kai wajen taka tsan tsan a harkar kudi, amma ba shi da dama idan aka zo da maganar dambe.
"Zan iya ragargazar kowa...
'yan damben nawa ne a ajin matsakaita?
Duk sai in ragargaje su, "yana mai cewa.
"Ba ni zakaran nauyin Kilo 77 (ajinna kusa da matsakaita), zakaran nauyin  masu kilo 64 (Ajin matsakaita) zan iya yi musu raga-raga dukkanninsu a rana daya"
An ga wani mai kamun kifi 'ya jefi giwan ruwa da kwalbar giya' a Devon
Wani wanda ya ke fatsa ya jefi wata dabbana ruwa da kwalbar giya a lokacin da dabbar ta katse masa tarunsa, a cewar wata kungiyar agaji.
Wasu hotuna da aka dauka a Hope Nose, kusa da Torquay, na nuna wani mutum ya jifan dabbar ruwan da wani abu daga bakin wata gaba.
Duncan Kenny wanda ya dauki hotunan ya ce, dabbar ruwan ta fito kiwo ne a lokacin da mai kamun kifin ya kurbe abin da ya ke sha a wata kwalba kafin ya jefi dabbar da ita a inda ya same ta a baya.
Mista Kenny ya kira lamarin "tashin hankali da nuna rashin sanin yakamata."
Mutumin yana mai cewa yana tattara shara ne a wurin shakatawa na Devon tare da 'yan kungiyar agaji mai rajin tattalin kare dabbar ruwan, a lokacin da ya ga mutumin ya kai wannan hari a safiyar Lahadi.
"Dabbar ruwan dai ta yi kokarin kaiwa ga fatsar da mutumin ya jefa ne" a na mai cewa.
"Mai kamun kifin da ya kwankwade giyarsa, sai kawai ya jefi dabbar ruwan da ita.
"Kwalbar ta sami dabbar ruwan an bayansa da hakan ta sa ya bi ruwa ya yi tafiyarsa."
Mista Kenny ya na mai cewa "an dai sa a dabbar ruwan tana da aukin jiki, "amma dabbar ta na yin abin da ya ke dabi'arta ne kawai.
"Wannan jifanta da ya yi da kwalba hana ta yin farautarta ya yi" in ji mutumin.
Shirin kula da dabbar ruwan na mai cewa, "wannan ba sabon abu ba ne" dama ta sha samun rahotanni na faruwar irin wannan halin mugunta a baya-bayannan."
A wani sako da ta sa a shafinta na dandalin sada zumunta na Facebook, ta ce masu aikin sa kai sun tattara shara tare da jikankuna 12 a yayin wannan ziyara da suka kai Hope's Nose suna kuma lura da "misalai na halaye marasa kyau."
Dukkannin dabbobin ruwa na karkashin kariyar dokar kula da kuma alkinta dabbar ruwa, kuma ana shawartar mutane da su rika kauce wadannan dabbobin.
Kasar Serbiya ta nemi karin jiragen saman yaki a tsaka da tashin hankali na Balkan
BELGRADE, Serbia (AP) - Serbia za ta karfafi sojojinta kuma yayin da ta ke neman ta sayo karin jiragen yaki ana tsaka da tsananin tashin hankali a cewar shugabana kasar ta Serbia a ranar Lahadi.
Shugaba Aleksandar Vucic ya ce "wasu matakai" a cikin bin su domin a sayo wasu jerin jiragen saman yaki samfurin fighters bomber, ta na zargin Amurka da kuma wasu kasashen yamma da ba kasar Serbia wacce ta ke makwabciyar kungiyar NATO wacce ta balle daga tsohuwar lardin Kosovo.
"Amurkawa da Turkawa da kuma Jamusawa suna kokarin kulawa da 'ya 'yansu abin masonsu " in ji Vucic, yana nufin Kosovo.
Ya ce yana Amurka a kwanan nan ta kai wa sojojon Kosovo motoci masu sulke masu yawa.
A yayin da ya ke ziyarar rundunar sojojojin yakin motocin sulke, Vucic ya ce kasarsa ba za ta iya gasa da makwabtanta ba da ake yi"kyautar da kungiyar NATO ba ta fuskar makamai", don haka dole ne mu yi mu kadai da kanmu."
Vucic bai fada takaimaimai irin jiragen saman yakin da Serbia ta ke da shirin saya ba. Amma kafofin yada labarai masu goyon bayan gwamanati na cewa gwamnatinsa a hukumance ta bukaci Amurka da ta ba su jiragen saman yaki guda 20 samfurin fighters-Bombers.
Rahotanni na cewa Washington ba ta ce komai ba dangane da bukatar ta Belgrade in kuma ta ki, toh, da akwai da yiwuwar za ta sayi jiragen na yaki guda 25 na kasar Russia samfurin Sukhoi na kai hari.
Kasar Serbia, wacce ta yi ikirarin matsayi 'yar baruwanmu ta fuskar soji, a baya-bayan nan ta karbi wasu na'urori na zamani da kakkabo jiragen sanman yaki daga Russia, wacce kuma ta bata jiragen yaki, da jiragen saman masu saukar ungulu na kai hari da kuma motoci masu sulke.
Wata kawar Serbia, China ta kai mata taimakon jirage masu sarrafa kansu na soji.
Jami'an Amurka a baya sun yi magana a bayyane akan kakabawa Serbia takunkumi idan Mascow ta sake aika mata da karin wasu makamai, musamman wadanda za su iya jefa harkar tsaron kasashen NATO mai makwabtaka cin hadari.
Kasashen yamma da kuma wasu makwabtan Serbia na kallon samar da makaman da kasar China da Russia ke yi da faraba.
Hankula na kara tashi yankin na Balkan, wacce ta ke farfadowa daga wani kazamin yakin basasa a shekarun 1990.
Kungiyar Tsaro ta NATO ta shiga tsakani a Serbia domin dakatar da yawan zub da jinin Serbi kan 'yan aware Albaniyawa a Kosovo a shekarun 1999.
Duk da cewa ta nemi ta shiga cikin Kungiyar Tarayyar Turai, Shugaban Serbia mai farijn jini ya kara inganta alakar siyasa da sojin kasar da Kremlin da kuma Beijing.
Serbia da Russia da kuma China ba su amince da 'yancin cin gashin kan Kosovo ba, wacce ta samu amincewar Amurka da kuma yawancin kasashen Turai.
Masu zanga-zanga a Seattle sun yi arangama da 'yan sanda shirin karo yawan jami'an tsaro na tarayya
'Yan sanda a Seattle sun yi amfani da abubuwan fashewa marasa hadari da barkonon tsohuwa a ranar Asabar kan masu zanga-zaga wadanda suka cinna wuta kan motocin gine-gine da ke ajiye a kofar wani gidan yari na matasa ana tsaka da fushi kan shirin Shugaba Donald Trump karo jami'an tsaro na tarayya a manyan birane.
Karar fashewar abubuwan akai-akaina ya cika kan tituna da ke cikin birnin jihar Washington, hayaki ya tashi daga wuraren da ake yin zanga-zangar a inda suka cinnawa motocin masu gine-gine da aka ajiye a kofar wata cibiyar tsare matasa da ake ginawa.
Masu zanga-zangar sun yanka tayoyin motocin tare da farfasa tagoginsu.
'Yan sanda a cikin shirin yaki da tarzoma su yi taho mu gama da 'yan zanga zangar wandanda yawancinsu suna rike da lema don kare kansu daga burbushin barkonon tsohuwa da ake fesawa.
Jaridar Seattle Times ta bayar da rahoton cewa 'yan sanda sun ce sun kama mutane 16 a bisa zargin kai hari kan Jami'an 'yan sanda, da tare hanya da kuma kin fashewa daga wurin.
An Kama Uba da dansa da tabar Heroin da darajarsu ta kai Rs 1.54 a Mizoram
Tabar Heroin, wacce darajarta ta kai Rs 1.55 a cikin kasuwar cikin gida, an yi sumoga dinta ne daga Myanmar: Cops
An kama wani mutum da dansa da tabar heroin mai nauyin kilogiram 1.9 a gundumar Hnahthial da ke Mizoram kusa da kan iyakar Myanmar, in ji ‘yan sanda ranar Lahadi.
Tabar ta heroin din, ta kai kimanin Rs 1.55 a kasuwar cikin gida, an shigo da ita ne daga Myanmar, in ji su.
'Yan sanda sun ce an kama Duhkima (62) da dansa Remthangpuia (33) tare da tabar a daren Juma'a daga kauyen Ngharchhip.
Jami'ai sun ce sun kuma yar da kimanin giram 280 na tabar, wanda ya kai Rs 15 dubu daria, yayin da suke iyo a cikin kogi yayin da suke kokarin tserewa daga 'yan sanda.
A cewar 'yan sanda, wannan kamun ta yi amannar cewa shine babbar wanda kuma ba a taba irinsa ba a kamen da ake yi a jihar.
Za a tuhumi wadanda ake zargin ne a karkashin sassan Dokar Abubuwan sa maye da kuma abubuwa masu gusar da hankali (NDPS) ta shekarar 1985.
Duk da cewa iyakokin tsakanin jihohin da wanda ke Myanmar sun kasance a kulle sakamakon barkewar annobar kwayar coronavirus, an ci gaba da shigo da muggan kwayoyi da sauran haramtattun kayayyaki ba kakkautawa, in ji majiyar ‘yan sanda.
A kwanan nan ne kungiyar tsaro ta Assam Riffles suka kama wasu manyan motoci guda 25 cike da goro, wadanda darajarsu ta kai Rs 4, ana fasa kwabrinsu daga Myanmar, in ji su.
Wani jami'in hukiumar kashe gobara ta birnin New York FDNY, ya ce'babu makawa' daidai ne a cire ma'aikacin kashe gobara farar fata daga faretin gabatar da laumin hukumar
Jami'an kula da banbancin na hukumar kasha gobara ta birnin New York FDNY ya ce tabbas hakkan daidaine a cire mai aikin kashe gobara farar fata daga faretin bikin gabatar da launukan hukumar don kawai a bar bakaken fata zalla ma'aikata don gudabar da faretin, a cewar wani sabon rahoto.
A wani ma'aikacin kashe gobara farar fata mai suna Laftanar Daniel Mc Williams ya shigar da kara a kotu a inda ya kalubalanatar wannan nunin wariyar launin fata bayan an cire shi daga bikin faretin tutocin hukumar a watan Nuwamba shekarar 2017 a wani bikin na tunawa da wadanda suka rasa ransu 'yan kungiyar Vulcan ta 'yan kashe gabara bakar fata zalla.
Hakan kuma jami'in kula da banbance-banbance da samar da daidaito, kuma lauya Cecila Loving, ta kare wannan mataki da a wata shari'ar da a ke yi a bangarren kula da hakkin bil adama na yankin jiha a birnin New York, a a wani rahoton da jaridar New York Post ta yi.
Mc Williams na daya daga cikin masu aikin kashe gobara uku a FDNY a wani hoto na tarihi da suke rike da tutar Amurka a inda so dogayen binayen nan suka ruguje bayan harin ta'addanci da ka kai na 9/11.
A cewar takaradar koken da Mc Willaims ya shigar, ya ce ya na daga cikin wadanda bangaren sshiryta bukukuwa na hukumar kashe gibara ta FDNY ta zaba da za su rike tita a bikin faretin gabatar da launukanta a bikin tunawa da wadanda su ka mutu.
Kasancewa daya daga cikin wadanda ke rike da tuta a wurin bikin 'bakaramin abin alfahari ba ne' ga Mc Williams, a cikin karar da ya shigar, kamar yadda gidan talbijin na CNN ta ba da labari.
A lokacin da ya zo wurin bikin, Sai a ka hana Mc Willaims shiga bikin faretin gabatar da launuka wanda tsohon shugaban Vulcan din Regina Wilson ta yi, saboda ta bukaci bakaken fata ne zalla su kasance masu dauke da tutocin a faretin tunawa da wadanda suka mutu din.
Sannan sai ta tambayi McWilliams dan shekara 29 da haihuwa tsohom ma'aikacin FDNY da je ya taimaka mata wani aikin da daban.'
Cikina ayyukan da ta ya ce ta sa shi shine matsara da farar huka daga in da suke a wurin bikin da kuma shirya 'yan uwansa maus damara da cikin tsarin da ya dace kuma a nrsa daga wurin bikin.
MC Willams ya kuma e a cikin takaradar karara da ya shigar aya akotu ya tambaye ta ko ceacire shin da aka yi daga cikin maus fareti na da alaka da kasancerwarsa shi baki ne.
Jami'ar ta amsa da cewa Eh, haka ne. A cewar sa.
Wani mai suna Wilson dan shekara 21 da haihuwa kuma mai aikin kashe gobara wanda shi ma da shi aka fafafata a ceton masifar da ta faru na 9/11, shi ya samar da wanda ya canji Mc wiliams daga cikin 'ya 'yan kungiyar sauran mazan jiya na Vulcan.
Mc Willams ya kuma ce ta bar wurin bikin ne saboda ya kasa jure wannan wulkancin da cin zarafi da kum cin mutunci' Saboda duk sa-in-sar da suka yi a wurin 'yan uwa da sauran abokan aiki duk suna ji, arahoton JaridarNew York Daily News.
A yayin zamana sauraron karar, Lauyar wanda ya shigarv kara Mc Willaims Keith Sullivan, ta tambayi Lovin - shin wanene bakar fata - don haka shin bukatar da a yi fareti da bakaken fata zalla ba nuna wariya ba ne?'
'A'a ba haka ba ne, Lovon ta ce, a wani rahoto na jaridar New York Post.
Sullivan ta kuma tambayi Loving shin ko yayi daidai da a samar da farenti na bakaken fata zalla bukatar da ta ce 'kwarai da aniya'
A cikin bayaninta, Loving ta ce ba laifi bane a sauya farara fata da bakar fata don kawai a fito da martabar banbance-bancenmu da kuma harsunanmu na asali don kawai a samar da yarda da junma da kawaciyara hankali da kuma taimakon juna a unguwanninmu'
Mc Williams ya dai shigar da kokensa ne kan nuna wariyar da aka yi masa a FDNY ne a cikin watan Janairun 2018.
Daga baya kuma ya shigar da karar Wilsos da kuma Hkumara FDNY da Hukumar kula da birnin New York da kuwa wasu mutanen da ba a bayyana ba a watan Mayu na 2019.
Bayan shigar da koken na sa ne, Sullivan ya ce Mc Willaims ya soma fuskantar barazana da kuma takura daga magoya bayan Wilson.
Har sai da kai a wani lokaci daya daga cikin magoya bayana Wilson ya daga kafadar Mv Willaims ya na mai ce masa 'na samu larin game da kai, na kuma abinda ka aikata, yanzu dai ka shida ni.'
A cikin jawabinsa na shigara da kara Mc Williams ya rubuta cewa, cire shi da aka yi daga faretin abin 'kyama ne' kuma wata alama ce ta munafirci a wannan hukumar kashe gobara.
' Idan kai bakar fata ne ka kuma nuna wariya ga fara fata a wurin aiki, tsananin abin da za a yi maka shi ne a dan zungure a hannu.' haka Sullivan ya rabuta.
Wilson a cewar takardara shigar da karar, 'an zaunar da iita an bata shawarwari na awa guda' kan irin abin da ta yiwa Mc Williams.
A daya bangaren kuma, idan farar fata ne ya nunawa bakara fatar wariyar launin fata 'a kan ja masa kunne, da kuma horo da ladabtarwa mai tsanani' a cewar Sullivan a rubutun da ya yi.
'HukumarFDNY ta kirkirarawa kanta wani tsarin karkatar da doka tare da bayar da uzururruka marasa tushe wajen kawar da kai ga irin abin da 'yan kungiyar Vulcan-wdanda ke aikata wasu aiyyuka na nuna wariyar launin fata, kuma dole ne a taka mu us birki haka', Sullivan ya kuma rubuta.
Wilfred Zaha na so ya bar kungiyar Crystal Palace a cewar Roy Hudgson: "Ci gaba da sa ido a wannn gurbin"
Mai kula da kungiyar Crystal Palace Roy Hodgson ya fadarwa da 'yan kallon gaba a gabannin karshen kakan wasanni a yayin da ya fadi cewa mai farin jinin Wilf Zaha mai kai hari na kungiyar na shirin barin kungiyar wasan kwallon kafar.
Dan asalin kasar Cote d ivore kuma tauraron kasa da kasa da ya dade da Selhurst Park har na sama da shekaru biyar, yanzu ya soma tattara kayansa zai matsa gaba, bayan da shahararsa ake alakantar da ita ga Arsenal da kuma Bayern Munich.
A shekara 27 da haihuwa kowa ya nade hannnnsa domin ganin ko manya-manya kulod irin wadannan na da sha'awara yi masa ruwan kudi, musamman ma a wannan bazara da ke cike da fargabar koma bayan tattalin arziki a harkar wasanni, Bayan fatatawar da aka yi a in da Zaha ya ci kwallaye hudu ya kuma samu nasarar taimakawa a ci har sau biyar don samun gurbi a kungiyar Palace wanda hakan bai yiwu ba.
Yayin da ya ke jawabi bayan fafatawar da aka yi a wasan karshe, Hodgson ya fadawa Alex Crock na shirin 'TalkSport' cewa "ka sa ido kan wannan gurbin" dangane da kila-wa-kala na barin Zaha kulob din bayan ya amsa cewa, dan gaban ya "fito karara" cewa yana ganin cigabansa ne a can wani wuri nesa da wannan kungiya.
Dan wasan gaban har yanzu yana da sauran shekaru uku da suka rage a yarjejeniyarsa da kungiyar Palace kuma a shekarar da ta wuce suna masu cewa suna da bukatar Fam miliyan 100 idan suna so su yakice shi daga kungiyar.
Bangaren Hodgson sun kammala jerin wasannin da suke yi ne da shan kashi har sau bakwai a jere da kuma kunnen doki a ranar karshe wanda hakan ya sa suka koma mataki na 14 a tafiyar.
Zaha da kansa ya ci kwallo sau daya ne kawai a tsakiyar watan Disamba da kuma a karshen kakar wasan, wani diba mai dogon zango na rashin samun nasara ga kungiyar Chelsea.
An bayar da rahoton cewa ya mika takardar neman sauya kungiyar a bazarar da ta wuce a kokarinsa na ya kaucewa abin da ake gudu, amma hakan bai yiwu ba da har zai ja hankalin kungiyar Palace din ta sayar da shi.
A wani kokari na zahiri na habaka damarsa na barin kungiyar, Zaha ya sauya ajen din sa a watan Janairu da kuma muhimman abubuwan da ke gabansa na makonni masu zuwa na nuna karara cewa shine ya bar kungiyar.
An shirya cewa Zaha ne zai taka rawa a yawancin mintunan wasan gasar Primier a wannan kakar wasa da kungiyar Palace za ta yi, baya da cewa shine kadai da wasan da ke kasa da shekara 28 da haihuwa da zai yi wasa har na tsawon mintuna 1,100 ko sama da haka, duba da yadda aka da bukatar yin garanbawul a 'yan wasan da wasu karin kudi da aka yiwa mai buga lamba 11.
Matsaikaicin Farashin man fetur a Amurka ya karu da kwabo daya a cikin makonni biyu zuwa $2, 25 gallon daya.
Camarillo, jihar California  - Matsakaicin farashin man fetur a Amurka ya dan hau da kwabo a cikin 'yan makonni zuwa $2.25 galan daya.
Wannan shine santi 56 kasa da matsaikacin farashin da ake sayarwa a gidan mai daga yadda farashin ya ke a shekarar da ta wuce.
Mai nazari a harkar Trilby Lunderberg Survey yana mai cewe a ranar Lahadi, a wannan shine kari mafi kankanta da aka gani tuna watan Afrilu.
Tana mai cewa farashin danyen mai sun kasance a wuri daya ga kuma wadataccen mai da ake samar da shi a Amurka domin cimma bukatar 'yan kasa.
A kasar baki daya, mafi kololuwar abin da za a biya na manfetur shine a birnin San Francisco sashin bakin teku a farashin $3. 27 a gallan daya
Mafi karanci a farashi kuwa shinne Baton Rouge, a Lousiana a farashin $2.79 a gallan daya.
Farashi matsakaici na man Dizel a garin Survey da  aka dauka a ranar Juma'a ya tasaya cak daga makonni biyu baya a bisa farashin $2.54 a gallan
Wasannin gasar motsa jiki na Olympics rukunin matasa an jinkirta shi zuwa shekarar 2026
Wasannin gasar motsa jiki na Olympics da aka sa za a yi a Dakar ta kasara Senegal a shekara mai zuwa, an daga shi zuwa shekarar 2026 saboda bullar annobar cutar Koronabirus, bayan yarjejeniyar da aka cimma tsakanin hukumar shirya gasar ta Olympics ta kasa da kasa (IOC) da kuma kasar Senegal.
Dage wannan wasa na Olympics na farko da za a yi a nahiyar Afrika ya zamo babba cikas ga yawancin matasa 'yan wasan motsa jiki.
An tabbatar da fitar Pedro Chelsea yayin da abokan buga kwallonsa suka rausaya da sarewa a walimar ban kwana da suka shirya a dakin canjin kaya.
Shugaban kungiyar kwallon kafa ta Chelsea Frank Lampard ya yabi mai buga gefe Pedro Rodriguez bayan wasansa na lig na karshe wa kungiyar a ranar Lahadi.
Dan shekara 32, ya sa hannu a wani dan kari a kwantiraginsa da zai mayar da shi kulob din AS Roma a wani sauyin sheka na kyauta da zaran sun gama da wannan kakakar wasan
Dan kasar Spania na kasa da kasa, wanda da zo daga Barcelona a shekarar 2015, ya dan taka leda na dan wani lokaci a karkashin Lampard a wannan kakar da somin tabi guda takwas na gasar firimiya da kuma taka wasanni 21 a jerin wasannin
Shugaban 'yan shudin gida ya tabbatar da tafiyar Pedro bayan da kungiyar ta yamma da birnin Landan ta kai mataki na hudu a kasa bayan ta lallasa kungiyar Wolves 2 da nema, wanda daga bisani tsohon dan wasan ya taso daga kan benci domin buga kwallonsa na karshe.
"Pedro ya bugawa kungiyar kwallonsa na karshe tare da ita", Lampard yana mai shedawa shirin talbijin sky sports.
" Abokan kwalllonasa sun karrama shi da wata 'yar walima a dakin canza kaya kuma hakan ya yi daidai saboda da irin nasorin da ya samu a sana'arsa ta buga kwallo da kuma kungiyarsa.
'Wannan shine wasansa na karshe a gasan firimiya, amma irin tasirin da gudunmawar da ya bayar na da girma.
Ina mai kara mika godiyata ga Peds tare da yi mi shi fatan alheri a kungiyar da ya koma.
"Yana nan don karasa kakar wasan da ta rage, amma duk lokacin da wani babban dan wasa ya bar kungiya sai yanayina sauran abokan wasan nasa ya sauya  kamar yadda na a lura".
A sakon ban kwana da Pedro ya sa a shafinsa na dandalin sada da zumunta na Tuwita, dan wasan na mai cewa: "wasana na kashe filin  Stanford Bridge"
Ina godiya da daukacin magoya bayana da dukkannin goyon bayan da ku ka bani tsawon wannan shekaru, ga Kulob kuwa ina godiya da damar da aka ba ni na zama mai daura launin shudi ga abokan wasana kuma
Ina mai cewa a garesu kuna cikin ruhin zuciyata har abada.
Dan haka mu dage don yin yakin cin kofin FA !!
JINJINA GA 'YAN UWANA 'YAN SHUDIN GIDA"
Tsohon dan gaba na Barcelona ya bar Chelsea bayan ya taimakawa kungiyar tun shekarar 2017 a karkashin Antonio Conte ya kuma ciwo kofin FA a shekarar 2018, da kuma kofin Europa a gasar Lig bayan shekara a karkashin Maurizio Sarri.
Ciwon zuciya: Cin cakulan sau ɗaya a mako na iya rage haɗarin fadawa cikin wannan mummunan matsayi
Wani sabon bincike ya yi nuni na hakika cewa soma wannan dabia na iya zama mai kyau ga tsokar zuciya.
Menene shi?  Kuma ta yaya za ta iya rage yiwuwar hadarin kamuwa da ciwon zuciya?
Masu bincike sun gudanar da wasu bincike-bincike da nazari na tsawon sama da shekaru biyar suna duban cututtukan da suka shafi kahon zuciya (CHD).
CHD - wannan kuma ana kiranta da sunan cututtukan zuciya na ischemic - yana da manyan alamomi guda uku: ciwon kirji (angina), bugun zuciya da gazawar zuciya.
Sauran alamun cutar na iya haɗawa da bugun zuciya da kuma rashin numfashi mai ban mamaki.
"Cakuleti na dauke da sinadaran da ke samar da lafiyar zuciya kamar flavonoids, da methylxanthines, da polyphenols da kuma stearic acid wanda ka iya rage kumburi da kuma kara kyastarol mai kyau. "
Kyakkyawan cholesterol, da aka san shi da babban nauyi na lipoprotein (HDL), yana tattara “mummunan” cholesterol - nau'in da ke buɗe jijiyoyin zuciya - kuma ya ɗauke shi zuwa hanta.
A cikin hanta, "mummunan" (low-density lipoprotein) cholesterol yana narkewa sannan kuma ya fita daga jiki a matsayin najasa.
Sai dai, sabon binciken bai yi nazarin girman rabo, ko nau'in cakuletin ko kuma irie-irensu da ya kamata a ji dadinsu ba.
Ba a bayyana ba ko wadanda aka yi binciken a kansu sun ci cakulan mai duhu ne, ko cakuleti mai madara ko mai dauke da kayan marmari na kuma mai dauke da koko.
Sakamakon binciken ya ta'allaka ne akan binciken da aka yi a baya wanda ya tabbatar da cewa shan koko (wanda ake samu a cikin cakuleti) ya na rage barazanar kamuwa da ciwon zuciya.
Masana kimiyya sun yi imani da cewa flavonoids da aka samo a cikin cakulan na rage hawan jini sanna ya kuma inganta aikin jijiyoyin jini.
Aikin jijiyoyin jini yana nufin yadda jini ya ke sadar da iskar oxygen da abubuwan gina jiki a cikin jiki da yadda fitar da abubuwa marasa amfani daga jikin.
Dangane da sabon binciken, ba a bayyana cewa ko abubuwan tafi da rayuwa an fifitasu a cikin sakamakon ba.
Dokta Alice Lichtenstein ta yi tsokaci kan bayanan, tana mai nuna cewa wadanda suka yarda da cin cakulan na iya samun "lafiyar jiki mai nauyi."
Ta kuma kara da cewa za su iya "tsunduma a kai a kai" a ayyukan motsa jiki kuma su zama "wadanda ba sa cikin damuwa."
Ta ci gaba da cewa: "Kowane abu na iya yin tasiri na kashin kansa a lafiyar jijiyoyin da suka shafi zuciya."
Wani dan jarida na gidan talbijin ya yabawa wani mai kallo sakamakon lura da yayi na wani dunkulen cutar kansa
TAMPA, Fla.  (AP) - Wata mai ba da labarai a talabijin a Florida ta yabawa wani mai kallon mai idanun mikiya saboda lura da wani dunkulewar da ke wuyanta da kuma yi mata wasikar email yana mai cewa ya kamata ta je a duba ta.
Victoria Price wata 'yar jarida ta gidan talbijina na WFLA a Tampa, bayan jin wannan shawara ta ce an duba ta an kuma gano cewa tana da Kansa.
A wani sako da ta aika ta shafinta na sada zumunta na Tuwita ta ce za a yi mata aiki a ranar Litinin a inda za a cire mata kurjin da kuma wasu kaluluwa da sula fito mata.
"Likita ya ce yana yaduwa, amma ba shi da yawa, kuma muna fatan cewa wannan shine aikin da za a yi min na farko kuma na karshe. In ji ta.
Mai kallon a wasikar email din ya aika mata a watan da ya wuce yana mai cewa wannan kumburin na tuna mata irin wanda ita ta yi.
Price 'yar shekara 28 da haihuwa 'yar jarida mai binciken kwakwaf, ta ce a wannan makon taken tashar talbijin da ta ke shine "8 da ke tare da kai"
"Amma sai ga shi a kwanan nan yanayin ya canza, a lokacin da na samu dan kallo a bangarena, kuma ina cike da godiya" in ji Price.
"Ba zan taba mantawa da matar da ta yi wannan sadaukarwar ba ta aika min da wannan wasikar email, babu wata sanayya tsakanina da ita.
Babu abin da ya shafeta da ni, amma ta nuna ta damu.
Yi magana akan kasancewa a bangarenka na hakika, ko? "
Kwamitin yakin neman zabe ya ki ya yi hira da gidan talbijin na Fox News a shirinsa na Sunday Interview, mako 1 bayan zaman dirshan na Chris Wallace kan shugaba Trump
A hirarsa da Chris Wallace a makon jiya, shugaba Trump ya tambayi shin ko dan takarar shugaban kasa a jam'iyya Democrat Joe Biden zai iya da irin jerin tambayoyin da Wallace ke yiwa shugaba Trump.
Amsar wannan tambaya dai - a halin yanzu dai- ba za mu san amsar ba tukunna.
A ranar Lahadi Wallace ya sanar da masu kallonsa cewa, kwamitin yakin neman zabe na Joe Biden ya fadawa Fox News cewa " ba zai samu damar halartar" shirin hira da shi ba.
"A hirar da mu ka yi da shugaba Trump a makon da ya wuce, ya tambayi cewa shin ko cewa dan takarar shugabancin kasa da na jam'iyyar Democrat abokin adawarsa, zai iya da irin wannan tambayoyi na kawkwa", A cewar Walace.
"wannan mako, mun tuntubi kwamitin yakin neman zaben Joe Biden don yin hira ta musamman sai suka ce tsohon mataimakin shugaban kasa ba zai samu halarta ba."
Sannan ya kara da cewa, " Za mu ci gaba da tambayarsa a ko wane mako."
'Yan kwamitin yakin neman sake zaben shugaba Trump ya caccaki Biden har na tsawon watanni saboda gujewa taron gangamin yakin neman zabe da kuma tarukan 'yan jaridu a yayin da su, suka cigaba da yin hira da 'yan jaridu ana tsakiyar fama da annobar Koronabiarus.
Yayin da Biden a baya-bayan nan, ya koma na kashin baya, Trump shi da abokansa sun cigaba da yiwa tsohon mataimakin shugaban kasa zambo da cewa "ya buya" a gidansa na da ke can Delaware.
Sai dai Hakurin Biden na kin tararrukan jama'a babu wata illa ta ku zo ku gani da hakan ya yiwa farain jininsa, kamar yadda wani sakamakon jin ra'ayin jama 'a ya nuna cewa a tsanake Biden ya ba shugaba Trump tazaraa matain kasa baki daya da kuma wasu muhimman jihohi da suka zama filin daga.
Alkaluman sakamakon binciken da ke nuna farin jinin dan siyasa na ya nuna karara cewa Shugaba Trump yi kasa da maki 7 jihar Florida, a Pennsylvania ya yi kasa da maki 6.7, a Michigan 8.2, a kuma Wisconsin ya yi kasa da maki 6.4.
Trump da kyar ya ci wadannan jihohi hudu a shekarar 2016, ya karkata akalarsu daga launin shudi zuwa Ja, yayijn da ya ci zaben zuwa fadar White House.
Labaran gidan talbijin na Fox na baya-bayan nan ya ce Biden na kan gaba a Minnesto da MIchigan, da kuma Pennsylvania wandan da suka yi fintinkau.
Sakamakon zaben ya nuna cewa Biden yana kan gaba kadan a Ohio da North Carolina da Arizona kuma wasu muhimman jihohi guda uku da suka yi kunnen doki a wannan zagaye.
Haka kuma wani bincike ya nuna cewa a baya wasu jihohin 'yan gani kashenin jami'iyya mai launi ja kamar Texas da Georgia yanzu duk tarwatsu a tsakanin Trump da kuma tsohon mataimakin shugaban kasa.
A zaben shugaban kasar da shugaban kasa mai ci ke takara ta komawa karagar mulki a karo na biyu a fadar White House ana kallonsa a wani lokaci kamar wani ma'auni na farin jini shugaban ne,- haka kuma ake kallon wannan fafatawa a wannan zabe na shekarar 2020 tsakanin Trump da Biden.
Muhimman batutuwa sune cutar Koronabirus da kuma tattalin arzikin kasa wacce annobar ta yiwa mummunan illa da kuma irin matakin da shugaban ya dauka na magance su.
"Yan sanda na aiki kan zirga-zirgar matashi da aka kashe a Halensburg na karshe kafin rasuwarsa
'yan sandan masu bincike na binciken matuwar wani matashi a Halensburg, suna kakarin na tattaro bayanan zirga-zirgann da yayi a lokutansa na karshe kafin mutuwarsa.
An gano gawar Kirk Allan ne a wani wuri da ke Johnson Court da kimanin karfe 06:25 rarnar Asabar
An tsare wani mutum dan shekara 30, 'yan sanda kuma sun tabbatar da cewa ana tuhumarsa dangane da mutuwar matashin.
Za a gurfanar da mutumin a gaban kotun  Dumbarton Sheriff a ranar Litinin.
Mai binciken 'yan sanda sifeto Steve Martins ya ce: "muna jajantawa iyalan Kirk da abokansa da basu hakurin wannan rashi
Jami'anmu za su cigaba da aiki ba a ciki da wajen unguwannimu don samar da kwanciyar hankali.
"Ana cigaba da yin tambayoyi domin gano sahihinn abin da ya faru, musamman irin zirga-zirgan da mamacin ya yi a kwanakin kadan kafin rasuwar tasa, sai dai wannan na nufin da akwai wani takamaimai da muke nema ba dangane da kisan.
